### ISSUE TITLE
j.clients.currencylayer

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#10]
config manager

**Comment by despiegk** [comment]
needs to be as singleton, I think there is bug there, need to check

**Comment by despiegk** [comment]
singleton removed, now more clean with just the config base class

**Comment by zgorizzo69** [comment]
so we don't need a singleton ? Is this doc is still relevant ? https://github.com/threefoldtech/jumpscaleX/blob/24ed9db4b3092259e301b21214c6a42038199a8d/docs/baseclasses/config_singleton.md

**Comment by despiegk** [comment]
we are ok nothing to do
