### ISSUE TITLE
installer doc (needs to be ported)

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#102]
https://github.com/threefoldtech/jumpscaleX/blob/master/install/install.md

install should be in system for now (should be the default because sandboxes not done)

lets test on OSX & Ubuntu

**Comment by abom** [comment]
What's needed to be ported exactly? the link is broken.
Cannot get what needs to be done.

**Comment by serboctor** [comment]
I asked Kristof for more info, he says he already ported some docs, and that nothing needs to be done here and the ticket can be closed.
