### ISSUE TITLE
authorize ssh needs to be ported from prefab

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#105]
![image](https://user-images.githubusercontent.com/6021844/50482252-07d46980-09e6-11e9-8071-102358b249c0.png)

e.g. use login/passwd to get in then push the local sshpub key

**Comment by Dina-Abd-Elrahman** [comment]
verification steps:

```
j.builder.system.ssh.authorize(USER, KEY)
```

 - use this command to add the given key to the '.ssh/authorized_keys' for the given
user.
