### ISSUE TITLE
j.clients.etcd

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#11]
- config manager new
- basic test

**Comment by waleedhammam** [comment]
- Follows the new config manager.
- Test at: https://github.com/threefoldtech/jumpscaleX/commit/367ada77628da32ab1c2338b4eac4aaad373d160

**Comment by Dina-Abd-Elrahman** [comment]
### branch: `development` , 9e5f629f40e47a6ca5b4e2ff4cc83ca89eab3943

verified.
