### ISSUE TITLE
tmux.execute fails with pytest

### ISSUE THREAD

**Issue by serboctor** [threefoldtecharchive/jumpscaleX_archived#111]
Executing with tmux fails only if the code is run using pytest, and it specifically fails becaise this line doesn't start the tmux server.
https://github.com/threefoldtech/jumpscaleX/blob/master/Jumpscale/tools/tmux/Tmux.py#L65

to quickly reproduce it, create a file, test.py, with the following content:
```
from Jumpscale import j

j.tools.tmux.execute('y', window='main', pane='main')
```

Make sure the tmux server isn't running, and run `pytest test.py`, it will fail because the server doesn't get started.
Make sure the tmux server running, and run `python3 test.py`, it will work fine.

Tested using a docker running jumpscale

**Comment by serboctor** [comment]
Fixed by https://github.com/threefoldtech/jumpscaleX/commit/7ce956d15c3457b45bb2769f3b5b9aa204caae43

**Comment by Dina-Abd-Elrahman** [comment]
## Verification steps:

- kill tmux sessions :
```
   j.tools.tmux.kill()
```

- create test.py file and try to run it using pytest
```
 vim /tmp/test.py

pytest /tmp/test.py
```
