### ISSUE TITLE
component testing

### ISSUE THREAD

**Issue by rkhamis** [threefoldtecharchive/jumpscaleX_archived#118]
Some of  our basic components are in desperate need of good integration testing.
Of these:
 - **config manager**: 
   - ensure saving of an instance gets saved correctly in zdb
   - indices are correctly set
   - encrypted values are in encrypted in backend
   - can retrieve any instance
   - can find any instance based on the indexing 

- **jinja code generation**:
  - we generate a lot of code using jinja. We need to be sure the code generated is exactly what we intend.
   - check the templates

- **gedis**:
   - to be defined 

To be added to as we go along

**Comment by zaibon** [comment]
I ported all my work regarding gedis from 9.6.0 version to digitalmeX: https://github.com/threefoldtech/digitalmeX/commit/bca144b4f0fe25ad3588451d80c64a074673e9a0

This include a beginning of some testing for gedis there.
This only covers super basic flows. We need to add more testing:
- [ ] test all the possible serialization format
  - [ ] using schema_in, schema_out:
  - [x] using list of objects: https://github.com/threefoldtech/digitalmeX/commit/73e7ea6806304722ab22bdb05c4abcd33a63e38c
  - [ ] schema define in doc strings
  - [ ] .... I probably forget a lot

**Comment by 0xIslamTaha** [comment]
I'm gonna test the config manager

- Test all possible clients get actions

**Comment by despiegk** [comment]
branch: development_builders

**Comment by 0xIslamTaha** [comment]
gedis testing:
- Load an actor
- Use this actor via the client
- Load actor with schema
- Use this actor via the client

**Comment by 0xIslamTaha** [comment]
out of date docs
https://github.com/threefoldtech/digitalmeX/tree/development/docs/Gedis

**Comment by 0xIslamTaha** [comment]
there is a bug while starting the gedis server
https://github.com/threefoldtech/digitalmeX/issues/249

**Comment by 0xIslamTaha** [comment]
closed the bug

**Comment by 0xIslamTaha** [comment]
reviewing the existing gedis tests

**Comment by 0xIslamTaha** [comment]
there is a bug related to actors_list
https://github.com/threefoldtech/digitalmeX/issues/250

**Comment by 0xIslamTaha** [comment]
I dont knw what this code do there
https://github.com/threefoldtech/digitalmeX/blob/development/DigitalMe/servers/gedis/GedisServer.py#L238

**Comment by 0xIslamTaha** [comment]
There is a not used file, so why do we have it?
https://github.com/threefoldtech/digitalmeX/blob/development/DigitalMe/servers/gedis/JSAPIServerNOTUSED.py

https://github.com/threefoldtech/digitalmeX/tree/development/DigitalMe/servers/gedis/templates

**Comment by 0xIslamTaha** [comment]
error in GedisCmd file
https://github.com/threefoldtech/digitalmeX/blob/development/DigitalMe/servers/gedis/GedisCmd.py#L32
https://github.com/threefoldtech/digitalmeX/blob/development/DigitalMe/servers/gedis/GedisCmd.py#L40

**Comment by 0xIslamTaha** [comment]
bug when I tried to run tests
https://github.com/threefoldtech/digitalmeX/issues/251

**Comment by 0xIslamTaha** [comment]
verify config manager:
```bash
eval "$(ssh-agent -s)"
ssh-add
source /sandbox/env.sh
kosmos --init (yes)
gedis = j.servers.gedis.configure(name="test", port=8888, host="127.0.0.1", ssl=False, password="123456")                                                       
gedis.save()
gedis.actors_add("/sandbox/code/github/threefoldtech/digitalmeX/packages/extra/examples/actors", "ibiza")
gedis.start()
```
another shell
```bash
eval "$(ssh-agent -s)"
ssh-add
source /sandbox/env.sh
kosmos
client = j.clients.gedis.get("gedis_test_config", port=8888, namespace='ibiza')
client.actors.painter.echo("test") # output test
```

another shell
```bash
eval "$(ssh-agent -s)"
ssh-add
source /sandbox/env.sh
kosmos
client = j.clients.gedis.get("gedis_test_config")
client.actors.painter.echo("test") # output test
```

**Comment by 0xIslamTaha** [comment]
**Gedis status:**
**Bugs**
https://github.com/threefoldtech/digitalmeX/issues/250
https://github.com/threefoldtech/digitalmeX/blob/development/DigitalMe/servers/gedis/GedisCmd.py#L32
https://github.com/threefoldtech/digitalmeX/blob/development/DigitalMe/servers/gedis/GedisCmd.py#L40
https://github.com/threefoldtech/digitalmeX/issues/251

**Archived code**
https://github.com/threefoldtech/digitalmeX/blob/development/DigitalMe/servers/gedis/GedisServer.py#L238
https://github.com/threefoldtech/digitalmeX/blob/development/DigitalMe/servers/gedis/JSAPIServerNOTUSED.py
https://github.com/threefoldtech/digitalmeX/tree/development/DigitalMe/servers/gedis/templates

**Comment by AhmedHanafy725** [comment]
**Schema testsuite:**
https://github.com/threefoldtech/jumpscaleX/tree/development/Jumpscale/data/schema/tests/testsuite
