### ISSUE TITLE
clients/gdrive/GDrive.py

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#12]
- does not use right paradigm, needs to use proper factory class
- use config manager
- basic test

**Comment by andrewayoub** [comment]
refactored and tested manually but it's hard to write integration tests for it because it depends on google account credentials

**Comment by Dinaamagdy** [comment]
verified by 
- get credentials from google drive rest apis .
- then use it in google drive client on jumpscale 
``` gclient= j.clients.gdrive```
- get file from my drive using  js client 
```
gclient.credfile="path/to/cedfile" 
gclient.getFile("file Id")
```
