### ISSUE TITLE
Builder for freeflowpages

### ISSUE THREAD

**Issue by rkhamis** [threefoldtecharchive/jumpscaleX_archived#120]
A builder for humhub [see freeflow](https://github.com/threefoldgrid/freeflow) is needed. This will allow any user to serve their own humhub easily by launching an flist in a container.

This flist must have autostart,

**Comment by PeterNashaat** [comment]
- FreeFlow flist autostart is done.

**Comment by despiegk** [comment]
check https://github.com/threefoldtech/jumpscaleX/issues/155

**Comment by despiegk** [comment]
branch: development_builders

**Comment by andrewayoub** [comment]
progress can be tracked here https://github.com/threefoldtech/jumpscaleX/pull/167

**Comment by Dina-Abd-Elrahman** [comment]
- after i build the freeflow and test it the apache doesn't started on it, @Pishoy trying to fix it now.

**Comment by Dina-Abd-Elrahman** [comment]
### Verification steps:

- j.builder.apps.freeflow.build(install=True)
- j.builder.apps.freeflow.install(install=True)
- j.builder.apps.freeflow.sandbox(reset=True, zhub_client=zhub_client, create_flist=True)

and merged it with ubuntu 18.04 flist, and test it locally 

![ff](https://user-images.githubusercontent.com/21218053/57459125-e7110000-7272-11e9-9825-3f5af02ca717.png)

**Comment by Dina-Abd-Elrahman** [comment]
@Pishoy the builder is working , but still we need start and stop methods

**Comment by Pishoy** [comment]
stop and start methods are added https://github.com/threefoldtech/jumpscaleX/commit/aa3ab264dc71c6750fbad94e35d941f5e317b97b

**Comment by Dina-Abd-Elrahman** [comment]
start and stop methods are working correctly now, freeflow builder test cases is added b72520d
