### ISSUE TITLE
Builder for openresty

### ISSUE THREAD

**Issue by rkhamis** [threefoldtecharchive/jumpscaleX_archived#121]
A builder for openresty to will allow any user to serve their own wikis easily by launching an flist in a container.

This flist must have autostart,

**Comment by serboctor** [comment]
Added builders for openresty and lapis. Readme for using the flists can be found here https://github.com/threefoldtech/jumpscaleX/tree/development/docs/flist

**Comment by despiegk** [comment]
branch: development_builders

**Comment by Dinaamagdy** [comment]
build works but still flist doesn't work correctly as mention here
https://github.com/threefoldtech/jumpscaleX/issues/186

**Comment by Dina-Abd-Elrahman** [comment]
- outdated , we can close it.
