### ISSUE TITLE
Builder for filemanager

### ISSUE THREAD

**Issue by rkhamis** [threefoldtecharchive/jumpscaleX_archived#124]
A builder for filemanager [see filemanager](https://github.com/itsyouonline/filemanager).

requires: #123

This flist must have autostart,

**Comment by abom** [comment]
Caddy builder works fine now (using [caddyman](https://github.com/Incubaid/caddyman/)).
[filemanger](https://github.com/itsyouonline/filemanager) is broken (need to build against older dependencies), will try to add vendoring as @muhamadazmy suggested.

**Comment by abom** [comment]
Vendoring gave more errors (trying to use older versions that produce other dependencies that want more older versions!).

We added some changes to [caddy-integration](https://github.com/itsyouonline/caddy-integration) with iyo and [caddyman](https://github.com/Incubaid/caddyman), and at least we now have iyo authentication with the latest [filebrowser](https://github.com/filebrowser/filebrowser) (not our fork), Our filebrowser fork need to be synced with upstream and the changes [here](https://github.com/itsyouonline/filemanager/pull/1) need to be ported though.

**Comment by abom** [comment]
[An issue](https://github.com/filebrowser/caddy/pull/22#issuecomment-457826185) in setting root directory for the filemanager has been fixed, will rebuild the flist.

**Comment by hossnys** [comment]
Verified but with  2 notes :
1- for the access with IYO to the file manager anyone with IYO account can access the file manager container as there is no check on the scope of IYO orgainzation which need to be added later.
2- the builder is working good but i uploaded the flist manually as there is error in the client of zhub when creating hub instance.
```
TypeError: Object of type ModelOBJ is not JSON serializable
```
![screenshot from 2019-01-28 16-47-18](https://user-images.githubusercontent.com/26298009/51892826-bdab2300-23ab-11e9-8a9a-b7ab93bd4067.png)

![screenshot from 2019-01-28 16-46-59](https://user-images.githubusercontent.com/26298009/51892827-be43b980-23ab-11e9-84da-7338a9a5a460.png)
