### ISSUE TITLE
Builder for webgateway

### ISSUE THREAD

**Issue by rkhamis** [threefoldtecharchive/jumpscaleX_archived#125]
This builder should already exist, but we need to have one flist that encompasses all the components required for the webgateway.

Flist should autostart

**Comment by zaibon** [comment]
The webgateway is a combination of multiple things:
- etcd cluster
- traefik 
- coredns

These things need to all run in  different container, so you probably need different flists.

**Comment by rkhamis** [comment]
Indeed.
In that case we need to have very explicit documentation. Each component must have autostart, and there's documentation on how to launch a webgateway using those flists.

**Comment by despiegk** [comment]
check https://github.com/threefoldtech/jumpscaleX/issues/155

**Comment by despiegk** [comment]
branch: development_builders

**Comment by andrewayoub** [comment]
progress can be tracked here https://github.com/threefoldtech/jumpscaleX/pull/167

**Comment by rkhamis** [comment]
Webgateway is already built and flists done in #167
