### ISSUE TITLE
Building Tools

### ISSUE THREAD

**Issue by andrewayoub** [threefoldtecharchive/jumpscaleX_archived#129]
This ticket is to discuss the building strategy for JumpscaleX, there are two proposed strategies:
1- Builders should be aware of how to sandbox itself (this is the currently used strategy):
 * the builder by default builds on the system
 * the builder has a list of all files, dirs and bins needed
 * the sandboxer collects the files and dirs defined in the builder and copy it to the building directory
 * the sandboxer runs ldd to find the dependencies of the binaries defined in the builder
 * the sandboxer copies the bins and the libs to the build directory
 * the flist creator tar the build directory and upload in to the hub  

2- Builders should NOT be aware of how to sandbox itself:
 * the builder is not aware of sandboxing or what does it need to be sandboxed
 * by default the builder should be designed as it is building on the local system 
 * the sandboxer should provide tools from which we can:
   * create a container with base flist and run the builder on it
   * runs a builder on this container
   * creates a new flist containing all files added or modified during the build by comparing to the base flist

**Comment by zaibon** [comment]
You know that if you use [0-flist](https://github.com/threefoldtech/0-flist) once you have your binaries and libs properly laid out in your filesystem, 0-flist does the upload of the data to the hub and create the flist.
So no need to do anything special except building what you need.

**Comment by despiegk** [comment]
check https://github.com/threefoldtech/jumpscaleX/issues/155
