### ISSUE TITLE
clients/gitea

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#13]
- don't use python classes for data, use new config manager (uses BCDB behind)
- this will hugely simplify it

**Comment by ranatrk** [comment]
Client uses new config manager:
https://github.com/threefoldtech/jumpscaleX/commit/e7f21e1f8dd59f882e617a14441e67c61c13432f

**Comment by Dina-Abd-Elrahman** [comment]
## verification steps:
- client = j.clients.gitea.new(name="test")
 - client.save()
client.data_update()
client.view()
client.data
client.edit()
client.data
client.data_update()
client.delete()
