### ISSUE TITLE
find a way how to use ptpython embed() in gevent

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#131]
example for asyncio

https://github.com/prompt-toolkit/ptpython/blob/master/examples/asyncio-python-embed.py

we need same to work in gevent, so we can use the shell and in back the gevent functionality is still working (e.g. monitoring)

also need to see how can we integrate with the ptpython shell using e.g. https://github.com/xtermjs/xterm.js so we can seamless go to backend

**Comment by despiegk** [comment]
see for example of shell to web: ttyd
we cannot use this for kosmos/digital access

**Comment by despiegk** [comment]
best case would be
- xtermjs talks over e.g. websockets to gevent server of DM
- where we terminate on ptpython terminal directly
- this would allow multiple sessions all in the running shell

**Comment by arahmanhamdy** [comment]
For the gevent part is it what we needed?:
```python
from ptpython.repl import embed
from gevent import monkey, sleep, spawn, joinall
monkey.patch_all()


counter = [0]


def print_counter():
    """
    greenlet that prints counters and saves it in a global variable.
    """
    while True:
        print('Counter: %i' % counter[0])
        counter[0] += 1
        sleep(10)


def interactive_shell():
    """
    greenlet that starts a Python REPL from which we can access the global counter variable.
    """
    print('You should be able to read and update the "counter[0]" variable from this shell.')
    embed(globals=globals())


def main():
    job1 = spawn(print_counter)
    job2 = spawn(interactive_shell)
    joinall([job2])
    job1.kill()


if __name__ == '__main__':
    main()
```

**Comment by despiegk** [comment]
branch development_shell
