### ISSUE TITLE
put dict support in JS schema

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#136]
have specific type: dict (in core type system)

do serialization using msgpack of the dict, store as binary in capnp

changes should be minimal, its in the typesystem basically should normally not be more

**Comment by despiegk** [comment]
where can I find docs? How to use?
also dont find the commit?

**Comment by zaibon** [comment]
https://github.com/threefoldtech/jumpscaleX/commit/19ecf03d08e318524d089ff3671bfd7d622b8ebe
https://github.com/threefoldtech/jumpscaleX/commit/e3e8ca65e557b940d30699a8cce320abf9590077
?

**Comment by BolaNasr** [comment]
commit : e3e8ca6 
docs of schema :
https://github.com/threefoldtech/jumpscaleX/tree/master/docs/schema
test of dict type : 
https://github.com/threefoldtech/jumpscaleX/blob/master/Jumpscale/data/schema/tests/testsuite/testcases/test_schema.py#L832

``` python
scm = """
        @url = test.schema
        info = (dict)
        init_dict = {"number": 468} (dict)
        """
        schema = j.data.schema.get(scm)
        schema_obj = schema.new()
```

**Comment by zaibon** [comment]
@BolaNasr 
> docs of schema : https://github.com/threefoldtech/digital_me/blob/development_960/docs/schema/README.md

Can you move this to the proper repository please.

**Comment by despiegk** [comment]
why (dict) all are 1 letters e.g. I, F, ... why like this?

**Comment by despiegk** [comment]
<img width="1739" alt="image" src="https://user-images.githubusercontent.com/6021844/51597672-12f2ba80-1efc-11e9-97b6-5cfc760f97dc.png">

I am having some issues sometimes since this weekend

**Comment by despiegk** [comment]
<img width="1657" alt="image" src="https://user-images.githubusercontent.com/6021844/51597744-41709580-1efc-11e9-80ae-98ae3d4a1cce.png">

my test code
```
        scm = """
        @url = test.schema
        info = (dict)
        init_dict = {"number": 468} (dict)
        """
        schema = j.data.schema.get(scm)
        schema_obj = schema.new()

        j.shell()
```

**Comment by BolaNasr** [comment]
@despiegk 
we used (dict) because D is used in date type
