### ISSUE TITLE
Add travis nightly job for builders

### ISSUE THREAD

**Issue by rkhamis** [threefoldtecharchive/jumpscaleX_archived#138]
A nightly cron job that runs all the builder tests.
Make sure that the builder tests ONLY RUN during this job, and never on each commit, as they take too long.

it should produce a nice report of which tests are passing and which are failing and why they're failing

**Comment by zaibon** [comment]
What are the result fo these tests ? New nightly build of all flist ? 
So that means we could promote any of them if test are green if needed ?

**Comment by rkhamis** [comment]
@zaibon I think for now, let's keep an eye for errors, because in all cases, the nightly flist eventually needs to include the kosmos version of jumpscale and we're not ready for that yet

**Comment by Dina-Abd-Elrahman** [comment]
can someone check ?
https://github.com/threefoldtech/jumpscaleX/pull/140

**Comment by Dina-Abd-Elrahman** [comment]
can someone check ?
https://github.com/threefoldtech/jumpscaleX/pull/143

**Comment by despiegk** [comment]
think this can go away, we have other cards about testing where we do the basis in our OVH server
