### ISSUE TITLE
j.clients.github

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#14]
- config manager
- basic test

**Comment by waleedhammam** [comment]
- Follows the config manager
- Minor fix at: https://github.com/threefoldtech/jumpscaleX/commit/c8e968520883f52cbe9685bad8c0fdbd00f046ae, https://github.com/threefoldtech/jumpscaleX/commit/9e5f629f40e47a6ca5b4e2ff4cc83ca89eab3943  
- test should be manual for saving the login and password or secret, readme at: https://github.com/threefoldtech/jumpscaleX/blob/development_jumpscale/Jumpscale/clients/github/README.md

**Comment by Dina-Abd-Elrahman** [comment]
#### branch: `development`, commit: e7861c107223496c370df06ce0d54cbf2aed3745

#### Verification steps:

- test_client = j.clients.github.get("test_client", token="**********")
- test_client.save()
- test_client.repo_create("repo_test", description="this is a repo created from github client", auto_init=True)
- repo = test_client.api.get_repo("username/repo_test")
- repo.clone_url
- repo.create_issue("test_issue", body="test an issue")
- repo.delete()
