### ISSUE TITLE
suboptimal usage of builders

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#141]
![image](https://user-images.githubusercontent.com/6021844/51788296-a0dcd880-217c-11e9-8f4a-0f28b9363792.png)

please use everywhere self.tools.run(...

other lines not needed

**Comment by despiegk** [comment]
branch: development_builders

**Comment by rkhamis** [comment]
Already within the scope of https://github.com/threefoldtech/home/issues/126
