### ISSUE TITLE
debug support in kosmos shell [types]

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#149]
because of logging in debug mode auto completion does not work well

e.g. ssh.me 
results in:

![image](https://user-images.githubusercontent.com/6021844/52191311-bf159900-284c-11e9-9a88-c9c498f73894.png)

can we check if j.tools.logger.debug is True
if yes

do 10 lines at bottomn (where the docu strings come)
![image](https://user-images.githubusercontent.com/6021844/52191346-ee2c0a80-284c-11e9-8fd3-e51a6d75c554.png)

which stay there

do all the logs & docu strings at that level

not sure how/if this can be done

**Comment by despiegk** [comment]
branch development_types

**Comment by despiegk** [comment]
not working for me
also some autocompletion does not work e.g. when not j...
but x=j.... then x...

**Comment by abom** [comment]
> not working for me

How? steps?

> also some autocompletion does not work e.g. when not j...
> but x=j.... then x...

Need some examples

**Comment by abom** [comment]
Scrolling debug pane should work (sometimes it doesn't work, should test outside of tmux too).

**Comment by abom** [comment]
Scrolling the pane is fixed in https://github.com/threefoldtech/jumpscaleX/commit/2c34dd70d7c853f0584ad60f7630cdb418a47904

Auto completions won't work on e.g. a client if this client has some errors (because we evaluate the line to get completions), also to show the debug pane, make sure DEBUG is set.

**Comment by AhmedHanafy725** [comment]
works fine

![image](https://user-images.githubusercontent.com/41957921/56091019-a9a29800-5ea9-11e9-8f64-8bc940e713f6.png)

and scrolling is working fine too
**Verified**
