### ISSUE TITLE
test the syncer, put doc in howtos of jsx

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#151]

**Comment by ranatrk** [comment]
Fixes in syncer:
- Change ftp.put to ssh_client.copy_file, and ftp.remove to ssh_client.exec_cmd in handler
- Ignore .swp and .swx files in handler when any change triggered
- Add steps to sync host and remote using syncer in howtos

https://github.com/threefoldtech/jumpscaleX/commit/b29e3c34d43f6e934b14a7bc155509a272ea54cf
https://github.com/threefoldtech/jumpscaleX/commit/426170be46eca4e88a88c50e1fffab3e299f6b24

**Comment by Dina-Abd-Elrahman** [comment]
# Verification steps:
 
--> we should install js on two nodes to test Syncing host to remote machines. 

- Create SSHKEY client instance:

```  j.clients.sshkey.get(name="test", path="/root/.ssh/id_ras") ```

- Create SSH client:

```
ssh_client_instance = j.clients.ssh.get(name="test_name", 
                                        addr="192.168.122.219", 
                                        port=22, 
                                         sshkey_name="test") 
```

- To make sure the host and remote are connected:

``` 
In [11]: ssh_client_instance.isconnected                                                             
Out[11]: True
```

- Create Syncer instance:

```
syncer_client = j.tools.syncer.get(name="syncer_test", 
                                   sshclient_name="test_name", 
                                    paths="/test") 
```

-    Sync host to remote directories
``` 
syncer_client.sync() 
```

**Comment by Dina-Abd-Elrahman** [comment]
- the sync server is working fine in two cases:

-- when it asked for password and i entered it. 
-- when i put the public key in authorized_keys file in remote server 

but it doesn't work if i pass the remote host server password as a parameter.

**Comment by ranatrk** [comment]
The public key needs to be added to the authorized keys of the remote server to grant access to the host

**Comment by Dina-Abd-Elrahman** [comment]
- you can find more info here :
https://github.com/threefoldtech/jumpscaleX/blob/development/docs/howto/sync_host_remote_with_ssh.md
