### ISSUE TITLE
autotests for schema, bcdb, zdb... using ONLY our own tools

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#153]
on development branch run the basic tests
make sure all is ok

**Comment by despiegk** [comment]
all work done to fix issues here need to be on branch:
'''development_tests'''

put all the basic tests in $JSXrepo/test.py

on OVH server, run JSX machine
which has following script

```python
#start container with Ubuntu 18.04
#install jsx in that system with openresty as well (use the install.py -1 -y -p -w)
#run test.py from the repo
#post the success or not (with error) if any to telegram group: tf_prod_jumpscaleX
```
for the telegram group, create client using config manager so the script does not need secret inside

this script needs to be in JSXREPO/scripts/autotest.py

run the script every hour between 5am in morning & 8pm (CEST)

this test cannot take longer than 5 min

**Comment by despiegk** [comment]
branch: development_testing

all bugs related to this or found when doing this work need to be on this branch

**Comment by AhmedHanafy725** [comment]
https://github.com/threefoldtech/jumpscaleX/issues/163

**Comment by rkhamis** [comment]
This issue is currently blocked on having an unattended installer. 

See storycard addressing this behavior [here](https://github.com/threefoldtech/home/issues/127)

**Comment by 0xIslamTaha** [comment]
I can see that server is working fine with the PR but we need more docs about how to run test cases and how to run the server itself in any vm. 

I noticed that the running VM is so slow when there are only two PRs

**Comment by AhmedHanafy725** [comment]
A new machine is created with more cpu cores and memory and it works fine with 5 PR at the same time.
