### ISSUE TITLE
wiki local install instructions & test & basic features done

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#157]
## tutorial

- [ ] start JSX in ZOS container or in Docker (use our installer with -w option)
- [ ] call script which will start required components
- [ ] as example checkout the TF Foundation wiki's (grid, ...)
- [ ] test the wiki page responds (some http get test to the web page)
- [ ] create documentation where wiki's are and how to be reached
- [ ] point to docu for macros (see if docu for macro's good enough)
- [ ] explain how to use the errors page

## wiki features

- [x] #195 link features wiki
- [x] #196 include features wiki

branch=development_types

**Comment by rkhamis** [comment]
child of #166

**Comment by despiegk** [comment]
this is not a child of #166

**Comment by abom** [comment]
>   start JSX in ZOS container or in Docker (use our installer with -w option)
>   call script which will start required components
>   as example checkout the TF Foundation wiki's (grid, ...)
>   test the wiki page responds (some http get test to the web page)

All of this is done and working, for automated testing, the whole publishing platform will have their own tests (QA).

Here are some links to documentation:

- [Wikis](https://github.com/threefoldtech/digitalmeX/tree/development/docs/publishing_platform/wiki)
- [Macros](https://github.com/threefoldtech/digitalmeX/tree/development/docs/publishing_platform/wiki/macro)
- [Errors document](https://github.com/threefoldtech/digitalmeX/blob/development/docs/publishing_platform/wiki/macro/README.md#errors)

Developer documentation are still in progress (many new changes are made with a new tool called [open_publish](https://github.com/threefoldtech/digitalmeX/tree/development/DigitalMe/tools/openpublish)).

**Comment by abom** [comment]
Closing as other newer issues are tracking the progress instead:

- https://github.com/threefoldtech/home/issues/162
- https://github.com/threefoldtech/home/issues/166
- https://github.com/threefoldtech/digitalmeX/issues/42
- https://github.com/threefoldtech/digitalmeX/issues/44
