### ISSUE TITLE
Markdowndocs: include part of file using the paragraph argument doesn't work correctly 

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtecharchive/jumpscaleX_archived#162]
As declared here https://github.com/threefoldtech/jumpscale_weblibs/blob/master/docsites_examples/test/blog/include_test.md#possibility-2-use-the-paragraph-argument 
that using paragraph method in include should just include tha part of find changes function ,but what happen that it return from the start of find changes function to the end of the file

**Comment by despiegk** [comment]
not clear what you mean

**Comment by Dinaamagdy** [comment]
https://github.com/threefoldtech/jumpscale_weblibs/blob/master/docsites_examples/test/blog/include_test.md#possibility-2-use-the-paragraph-argument
I used paragraph argument example there and it return the lines of def find_changes functions and the other functions after it in the file not  find changes function only as declared on the example

**Comment by abom** [comment]
The file itself has a problem and include macro was not working at all, until i figured that in this macro that uses `paragraph=True`, the first line is not `!!!include`, it's `macro`. it's a known issue that was stated [here](https://github.com/threefoldtech/jumpscaleX/issues/196#issuecomment-471277872).
I [removed it ](https://github.com/threefoldtech/jumpscale_weblibs/commit/cde13001cab8cea5ca7378009ad049a01fd3dad7) and it's working now., but the output as @Dinaamagdy stated, starts from `deg find_changes` until the end of the file.

````
```
!!!include
name = "Fixer.py"
repo = "https://github.com/threefoldtech/jumpscaleX/tree/master/Jumpscale/tools/fixer"
start = "def find_changes"
paragraph = True
codeblock = True
```
````

Yields

https://github.com/threefoldtech/jumpscaleX/blob/8a1d631a6bd98af3a11517c23f5eadef080db4af/Jumpscale/tools/fixer/Fixer.py#L50-L93

**Comment by abom** [comment]
I'm having a problem understanding `paragraph` parameter, neither the documentation nor the implementation are clear enough.

The docstring says:

>     :param paragraph: if True then will include from start till next line is found which is at same prefix (basically taking out a paragraph)

It's a very strange implementation that doesn't match what was described in docstring and only covers very basic cases.

https://github.com/threefoldtech/jumpscaleX/blob/2a7369c59686e11ae177e6ddc68433727a3dae80/Jumpscale/tools/markdowndocs/macros/include.py#L17-L21 

Need more input about this parameter usage.

**Comment by abom** [comment]
This [commit](https://github.com/threefoldtech/jumpscaleX/pull/218/commits/425f0cd950542bce12578e0de2c18c2a713ec7ab) uses indentation levels to detect paragraphs (line breaks start a new paragraph).

Now this:
````
```
!!!include
name = "Fixer.py"
repo = "https://github.com/threefoldtech/jumpscaleX/tree/master/Jumpscale/tools/fixer"
start = "def find_changes"
paragraph = True
codeblock = True
```
````

Yields:

https://github.com/threefoldtech/jumpscaleX/blob/8a1d631a6bd98af3a11517c23f5eadef080db4af/Jumpscale/tools/fixer/Fixer.py#L50-L53

**Comment by abom** [comment]
Updated the docs of macros/include.md too.
