### ISSUE TITLE
jsx installer

### ISSUE THREAD

**Issue by rkhamis** [threefoldtecharchive/jumpscaleX_archived#166]
All installer options need to be working

- install in sandbox
- install in docker
- install in system

and should be working with optional installer of openresty + lua

relates to #160

**Comment by abdulgig** [comment]
There are issues while installing openresty / lua in the JSX installer. The ./configure options are not correctly set when doing the build / install. The directories are missing.

Installation Options,

```
Installer choice for jumpscale in the docker
--------------------------------------------

Do you want to install
 - in system (development)                : 1
 - using a sandbox                        : 2
make your choice (1,2): 1

Do you want to redo the full install? (means redo pip's ...) = y
Do you want to pull code changes from git? = y
Do you want to install lua/nginx/openresty & wiki environment? = y

Jumpscale X Installer
---------------------

 - jumpscale will be installed in the system.
 - location of code path is: /sandbox/code
 - will install wiki system at end

Ok to continue?
make your choice (y,n): = y

```
Attached is the screen shot of the error !
![lua-resty](https://user-images.githubusercontent.com/25789764/52774617-0ecb4000-3057-11e9-8ccf-5d0530a772d6.png)

**Comment by abdulgig** [comment]
The errors are still there !

Also, with docker install, the error is attached herewith
![docker_issue](https://user-images.githubusercontent.com/25789764/53167715-35a6ea80-35f2-11e9-820f-b6fde296c6d9.png)

**Comment by Dina-Abd-Elrahman** [comment]
- I'm was trying to install JumpscaleX with ( In system ) option and give me this error 

![error](https://user-images.githubusercontent.com/21218053/53803202-acc27400-3f4c-11e9-94a8-462fe48ac9ad.png)

**Comment by Dina-Abd-Elrahman** [comment]
- when i try to install it using sandbox, i got this error. 

![error](https://user-images.githubusercontent.com/21218053/53805731-a5eb2f80-3f53-11e9-8dc9-7b71cc25d650.png)

**Comment by Dina-Abd-Elrahman** [comment]
- error when I was trying to install jumpscaleX on docker 

![error](https://user-images.githubusercontent.com/21218053/53815169-c6be7f80-3f69-11e9-9da4-aca00d9fb5c1.png)

- however, when i login to the docker and execute source /sandbox/env.sh and then js_shell it was working correctly 

![error](https://user-images.githubusercontent.com/21218053/53816739-c673b380-3f6c-11e9-95d5-6226ae60a909.png)

**Comment by despiegk** [comment]
should retest on development_types
