### ISSUE TITLE
j.clients/builder.influxdb

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#17]
- config manager
- implement installer & basic test

**Comment by despiegk** [comment]
split in 2 files: factory, instance

**Comment by despiegk** [comment]
also implement j.builder....
look at readme in that builder directory & TEMPLATE dir

**Comment by despiegk** [comment]
- implement j.client
    - [learn how to do it in template for client](https://github.com/threefoldtech/jumpscale10/tree/master/Jumpscale/clients/TEMPLATE)   
- implement j.builder....
    - [learn how to do it in template](https://github.com/threefoldtech/jumpscale10/tree/master/Jumpscale/builders/TEMPLATE)

**Comment by waleedhammam** [comment]
Duplicate of #522

**Comment by waleedhammam** [comment]
Implemented Build, Install. Still on the rest of the builder

**Comment by waleedhammam** [comment]
**Refactored builder at: https://github.com/threefoldtech/jumpscaleX/commit/963828c9e433aaaf33216ba1d2e2ffda2915dc0f**
* Implemented Build, Install, Sandbox, Start, Stop, Test

**Comment by Dina-Abd-Elrahman** [comment]
- build, install, start, stop, snadbox and test are working fine
