### ISSUE TITLE
js_shell 'j.clients.sshagent.test()'

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#172]
need to fix & put in main test.py

**Comment by despiegk** [comment]
check sshkey implementation too
see todo in /sandbox/code/github/threefoldtech/jumpscaleX/Jumpscale/clients/sshkey/SSHKey.py

**Comment by ranatrk** [comment]
Fix : 
- j.clients.sshagent.kill()
- j.clients.sshagent.test()

Add in test.py:
-  j.clients.sshagent.test()
-  j.clients.sshkey.test()

https://github.com/threefoldtech/jumpscaleX/commit/9ea2c22247925bd82222f6645ccdfe16c24b1b63

**Comment by Dina-Abd-Elrahman** [comment]
### Verification steps:

- j.clients.sshagent.kill()
- j.clients.sshagent.check()
- j.clients.sshagent.test()
- j.clients.sshagent.keys_list()
- j.clients.sshkey.test()
- j.clients.sshkey.new(name="test")
