### ISSUE TITLE
copy paste does not work from kosmos

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtecharchive/jumpscaleX_archived#181]

**Comment by abom** [comment]
To select text you need to use your current mode shortcut (emacs or vi)
https://github.com/prompt-toolkit/ptpython#additional-features

**Comment by LeeSmet** [comment]
Trying to use the commands as described in the link don't seem to work for copying. It does not seem like I am in any mode. How do you go into vim or emacs mode?

**Comment by abom** [comment]
@LeeSmet You can know which mode you are in by opening the menu (F2 key), also the Shift key works with me (just press Shift and try to select).
