### ISSUE TITLE
missing start and stop methods in etcd builder 

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtecharchive/jumpscaleX_archived#185]
there is no start and stop methods in etcd builder 
![image](https://user-images.githubusercontent.com/24386802/53098361-1d6c9800-352c-11e9-9dcd-4e48c5e664a6.png)

## branch |
development_builders

**Comment by waleedhammam** [comment]
It's there and working 
![Screenshot from 2019-05-01 11-40-05](https://user-images.githubusercontent.com/10658229/57012280-ed193800-6c05-11e9-96c2-79724fe38b61.png)

**Comment by AhmedHanafy725** [comment]
**Verified** 
Builders #299
