### ISSUE TITLE
openresty flist generated from openresty builder doesn't work correctly

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtecharchive/jumpscaleX_archived#186]
## Steps 
- j.builder.web.openresty.build()
- j.builder.web.openresty.sandbox()
- I created its flist using the tar file and here are the steps to verify its container
- node = j.clients.zos.get('ac1f6b4575a8', data={'host':'10.102.234.243', 'password_':'*************'})
- cont = node.client.container.create("https://hub.grid.tf/dina_magdy/openresty.flist")
- cont.filesystem.list('/') result the following 
```
[{'name': '_lapis.lua', 'size': 4096, 'mode': 493, 'is_dir': True},
 {'name': '_moon.lua', 'size': 4096, 'mode': 493, 'is_dir': True},
 {'name': '_moonc.lua', 'size': 4096, 'mode': 493, 'is_dir': True},
 {'name': '_moonrocks.lua', 'size': 4096, 'mode': 493, 'is_dir': True},
 {'name': 'lapis', 'size': 350, 'mode': 493, 'is_dir': False},
 {'name': 'lua', 'size': 3026880, 'mode': 493, 'is_dir': False},
 {'name': 'moon', 'size': 41, 'mode': 493, 'is_dir': False},
 {'name': 'moonc', 'size': 42, 'mode': 493, 'is_dir': False},
 {'name': 'openresty', 'size': 13664200, 'mode': 493, 'is_dir': False},
 {'name': 'resty', 'size': 29476, 'mode': 493, 'is_dir': False},
 {'name': 'restydoc', 'size': 14957, 'mode': 493, 'is_dir': False},
 {'name': 'restydoc-index', 'size': 8452, 'mode': 493, 'is_dir': False}]

```
## Error
cont.system('/sandbox/bin/resty -h').get()
```
STATE: 0 ERROR
STDOUT:

STDERR:

DATA:
fork/exec /sandbox/bin/resty: no such file or directory
```
 cont.system('/sandbox/bin/lapis server').get()    
```
STATE: 0 ERROR
STDOUT:

STDERR:

DATA:
fork/exec /sandbox/bin/lapis: no such file or directory

```
cont.system('/sandbox/bin/lua').get()  
```
STATE: 1127 ERROR
STDOUT:

STDERR:
/sandbox/bin/lua: error while loading shared libraries: libm.so.6: cannot open shared object file: No such file or directory

DATA:
```
## Branch
development_builders

**Comment by ahmadnazih** [comment]
https://github.com/threefoldtech/jumpscaleX/commit/fbf6744bf8e740dfda5e42236f8ee0d150109659

Now we can create a container with the flist and with port forwarding on 8081, then open the browser at the ip of the node and the port 8081 and you should see welcome to openresty page

**Comment by AhmedHanafy725** [comment]
Is this issue still valid ?
as the builders are changed and flist for builders are not done yet.

**Comment by serboctor** [comment]
Yea, you're right. I'll close this and the other task can be used to track instead.
