### ISSUE TITLE
Zero hub client JWT docs are wrong

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtecharchive/jumpscaleX_archived#188]
The creation of the JWT does not work following the docs of the zero hub client.

https://github.com/threefoldtech/jumpscaleX/blob/development/Jumpscale/clients/zero_hub/README.md#jwt-token

**Comment by robvanmieghem** [comment]
the jwt should also only have the `user:memberof:tf-official-apps` scope when uploading to tf-official apps, not the default`user:admin`scope

**Comment by DylanVerstraete** [comment]
closed in https://github.com/threefoldtech/jumpscaleX/pull/203
