### ISSUE TITLE
wiki improvement: implement links

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#195]
specs see /sandbox/code/github/threefoldtech/jumpscaleX/docs/tools/wiki/links.md

make sure the documents are found that way & links created automatically

**Comment by abom** [comment]
Started the implementation as a part of links pre-processing in markdowndocs/Links.py.

As per [links.md](https://github.com/threefoldtech/jumpscaleX/blob/development_types/docs/tools/wiki/links.md), a generic form is `[name](link)` the link can be in the following format:

**`acccount:repo(branch):path`**

* account (optional): will be current doc's account/organization if not given
* repo (optional): will be current doc's repo if not given
* branch (optional): will be `master` if not specified
* path can be a URL (as is)

Also, issue anchors like `#130` should be replaced with a link to this issue on the current account and repo.

given the `account` /  `repo` and `branch`, the path should be found and the link replaced.

**Comment by abom** [comment]
Parsing the link format is done, Finding out how we will deal with external repos (maybe as another docsite).

**Comment by abom** [comment]
Found a bug in the old parsing code of markdown links, it's is broken with the new link format

https://github.com/threefoldtech/jumpscaleX/blob/c7d7750163544d6d3e1852ccff79f362aad179ee/Jumpscale/tools/markdowndocs/Link.py#L42-L45

Testing

```
JSX> source = '[new](theefoldtech:info_tokens(development):docs/new)' 
   2 link_source = source.rsplit("(",1)[1].split(")",1)[0] #find inside () 
   3 link_source = link_source.replace("\"","").replace("'","") 
   4 link_descr = source.split("[",1)[1].split("]",1)[0].replace("\"","").replace("'","") #find inside []                                             
JSX> source                                                                                                                                           
'[new](theefoldtech:info_tokens(development):docs/new)'

JSX> link_source                                                                                                                                      
'development'

JSX> link_descr                                                                                                                                       
'new'
```

This part need to be re-written.

**Update:**
Another pattern bug, already fixed alongside link markdown parsing.

**Comment by abom** [comment]
I suggest to change the format to `acccount:repo:branch:path` instead of the current chosen one `acccount:repo(branch):path`

The parenthesis are too error prone and harder for parsing for cases where the line contain a normal **(** or **)**.

**Comment by abom** [comment]
It should be done now, the old code of parsing markdown links format is fixed and modified to work with the new one.

_**Output:**_

if a link containing another account/repo/branch, the docsite would be pulled and the custom format would be replaced by the path of the actual file in docsites directory:

How to **verify**:

Create or use a repo that contains some docs (like this one [here](https://github.com/abom/test_custom_md)).

using `markdowndocs` tool:

```
url = "https://github.com/abom/test_custom_md/tree/master/docs"
docsite = j.tools.markdowndocs.load(url, name="testmd")        
docsite.write() 
```

This file for example has a link of `[circle template](threefoldfoundation:info_foundation(development):/docs/circles/circle_template.md)`

The docsite of https://github.com/threefoldfoundation/info_foundation should be pulled and the link part should be replaced by the actual docsite file e.g. `info_foundation/docs/circles/circle_template.md`.

You can check the output docsites in `$DIR_VAR/docsites` (e.g. DIR_VAR=/sandbox/var)

**Comment by abom** [comment]
BTW, original implementation gives too many `doc not found` errors.

on development branch (without custom link changes):
`j.tools.markdowndocs.test()`

then check docs/errors.md

**Comment by despiegk** [comment]
see https://github.com/threefoldtech/jumpscaleX/tree/development_types/docs/tools/wiki/macros

**Comment by john-kheir** [comment]
Verified as part of https://github.com/threefoldtech/digitalmeX/issues/42
