### ISSUE TITLE
redis builder/client

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#21]
- check j.client.redisconfig
    - [learn how to do it in template for client](https://github.com/threefoldtech/jumpscale10/tree/master/Jumpscale/clients/TEMPLATE)   
- implement j.builder....
    - [learn how to do it in template](https://github.com/threefoldtech/jumpscale10/tree/master/Jumpscale/builders/TEMPLATE)
   - build & sandbox

**Comment by ranatrk** [comment]
redisconfig client now has get with extra parameters not in schema to configure the etcd_client.
https://github.com/threefoldtech/jumpscaleX/commit/04283570c2ad542be707a41c38db811b5cc1b102

**Comment by ranatrk** [comment]
Builder : https://github.com/threefoldtech/jumpscaleX/pull/310

**Comment by Dinaamagdy** [comment]
according to @ranatrk  there are  changes  in the  client so we need to define this changes and make docs for client

**Comment by Dinaamagdy** [comment]
for redis builder , the branch of it removed   and need to restore it again

**Comment by 0xIslamTaha** [comment]
@Dinaamagdy I updated the redis builder

**Comment by ranatrk** [comment]
@Dinaamagdy  regarding the redis client: 
1. Make sure redis server is already running
2. Get redis-cli instance :
`j.clients.redis.get(ipaddr=localhost,port=redis_server_port)`
3. Commands available: https://redis.io/commands

**Comment by Dinaamagdy** [comment]
I tried alot of redis client commands : set, get, setx , append  and they worked well 
but  client_kill  command doesn't work and give the following error : 
```
--------------------------------------------------------------------------
ResponseError                             Traceback (most recent call last)
/sandbox/bin/js_shell in <module>
----> 1 cl.client_kill("0.0.0.0:6380")

~/.local/lib/python3.6/site-packages/redis/client.py in client_kill(self, address)
    810     def client_kill(self, address):
    811         "Disconnects the client at ``address`` (ip:port)"
--> 812         return self.execute_command('CLIENT KILL', address)
    813 
    814     def client_kill_filter(self, _id=None, _type=None, addr=None, skipme=None):

~/.local/lib/python3.6/site-packages/redis/client.py in execute_command(self, *args, **options)
    773         try:
    774             connection.send_command(*args)
--> 775             return self.parse_response(connection, command_name, **options)
    776         except (ConnectionError, TimeoutError) as e:
    777             connection.disconnect()

~/.local/lib/python3.6/site-packages/redis/client.py in parse_response(self, connection, command_name, **options)
    787         "Parses a response from the Redis server"
    788         try:
--> 789             response = connection.read_response()
    790         except ResponseError:
    791             if EMPTY_RESPONSE in options:

~/.local/lib/python3.6/site-packages/redis/connection.py in read_response(self)
    640             raise
    641         if isinstance(response, ResponseError):
--> 642             raise response
    643         return response
    644 

ResponseError: No such client
```

**Comment by ranatrk** [comment]
It works well when I tried it. The problem was only that the address given in the form ip:port was probably incorrect. According to https://redis.io/commands/client-kill: '_The ip:port should match a line returned by the CLIENT LIST command (addr field)._'

![Screenshot from 2019-05-12 11-01-03](https://user-images.githubusercontent.com/17128393/57580108-a3eaa300-74a5-11e9-8a91-1fe96efa6ced.png)

**Comment by Dinaamagdy** [comment]
## steps 
## for redis builder 
- j.builder.db.redis.build()
-j,builder.start()
but sandbox doesn't work as still all builder need sandbox implementation https://github.com/threefoldtech/jumpscaleX/issues/299
 
## for redis client 
redis_cl = j.clients.redis.get(ipaddr="0.0.0.0", port=6192) 
        and test most of its command
