### ISSUE TITLE
Multiple tfchain client with the same name

### ISSUE THREAD

**Issue by zaibon** [threefoldtecharchive/jumpscaleX_archived#210]
I don't think this is something that should be possible to do, but I now have 2 tfchain client with the same name.
![2019-02-28_781x645_scrot](https://user-images.githubusercontent.com/303164/53566602-efefa200-3b5c-11e9-907c-9cf785dfa4fd.png)

**Comment by GlenDC** [comment]
Seems that you can have as many clients with the same name as possible, when using the new() function. After calling 3 times `j.clients.tfchain.new('testnet')`, I get the following output:

```
JSX> j.clients.tfchain.find()
## tfchainclient Instance: 'testnet'
- explorer_nodes      : []
- id                  : 1
- name                : testnet
- network_type        : STD
## tfchainclient Instance: 'testnet'
- explorer_nodes      : []
- id                  : 2
- name                : testnet
- network_type        : STD
## tfchainclient Instance: 'testnet'
- explorer_nodes      : []
- id                  : 3
- name                : testnet
- network_type        : STD
[, , ]
```

Note that a client does only show in the find results when it is saved, not sure if this is intended @rkhamis, but it seems like a bug to me.

**Comment by GlenDC** [comment]
It seems under the hood these have a different ID (as you also can see in the log above), but the name is the same, so this is clearly a bug on the JBaseConfigs level. Will need further investigation to check how we'll resolve this.

**Comment by rkhamis** [comment]
@GlenDC should be resolved with #236

**Comment by BolaNasr** [comment]
now it works good : 
![Screenshot from 2019-03-17 17-56-34](https://user-images.githubusercontent.com/10259267/54493956-0d06cd80-48de-11e9-8fc9-4b394bd9dd42.png)


if you need make specific  attributes  unique just add & before the name : 

```
schema = """
@url =  jumpscale.test.1
giturl =  "" (S)
&dest =  "" (S)  #unique attribute
enable = true (B)
"""
```

**Comment by zaibon** [comment]
I tested it seems to work ok indeed. 
@GlenDC I let you decide if this solution is good enough for you, if yes we can probably close the issue

**Comment by GlenDC** [comment]
Seems to be OK indeed. Are there unit tests for this written @BolaNasr?
Also how come I didn't have to put the `&` before my schema's name property? Probably it should be there as well, no?

**Comment by BolaNasr** [comment]
@GlenDC  i didn't write unit tests for that but i will soon ..
we have two features to be unique : 
- **name** : is unique by default without any specific char ( should be unique to save in our bcdb )
- **any attribute** : if you want  specific attribute to be unique like ( port , email , phoneNumber .. etc ) 
should be add ``` &``` before the attribute to be unique 

```
schema = """
@url =  jumpscale.test.1
name * = ""  #unique by default 
giturl =  "" (S)
&dest =  "" (S)  #unique attribute
&email =  "" (S)  #unique attribute
enable = true (B)
```

**Comment by despiegk** [comment]
lets quickly write a test & close

**Comment by Dina-Abd-Elrahman** [comment]
- i just checked with @AhmedHanafy725  and he mentioned that he finished unit test and waiting for @BolaNasr to complete fixing the bug

**Comment by AhmedHanafy725** [comment]
https://github.com/threefoldtech/jumpscaleX/issues/236#issuecomment-484122385
