### ISSUE TITLE
Reservation of capacity in tfchain client

### ISSUE THREAD

**Issue by zaibon** [threefoldtecharchive/jumpscaleX_archived#214]
Child of https://github.com/threefoldtech/home/issues/101

The goal is to integrate the reservation of capacity to the tfchain wallet. So user can order workload using the client

Reservation API:
I propose to add a reservation property to the [TFChainWallet Class](https://github.com/threefoldtech/jumpscaleX/blob/682c9be0b68b0c7d56ab21c658bce406aaaed773/Jumpscale/clients/blockchain/tfchain/TFChainWallet.py#L31)
The the flow could be something like:
```python
reservation = wallet.reservation.new()
reservation.type = 's3' # this is an enum that have allt he supported workload we currently support to reserve
reservation.duration = '..'
reservation.size = 2
reservation.email = 'user@mail.com' # email where to send connection information after deployment
reservation.3bot_id = 'mybot.user1' # can also be the numeric ID
wallet.reservation.send(reservation)
```
The send method will do multiple things:
- add a timestamp
- create a signature of the reservation
- encrypt the reservation with the pubic key of the grid broker
- put the reservation and signature to the notary
- create a new transaction containing the hash of the schema put in the notary and the amount of TFT required to pay the reservation

We probably want to save the hash of the reservation schema for further lookup from the notary as well as the transaction ID of the reservation.
Something like
`reservations = wallet.reservation.list()`

**Comment by LeeSmet** [comment]
just thinking but maybe we want to allow an additional data field where a user can enter data in a specific format, this seems to be useful / needed for some other workloads we want to support

**Comment by zaibon** [comment]
Hum I don't think so. I would like to have something strict define without arbitrary data. If we have to extend to support new workload, then we need to release a new version of the client with the added options. 
Otherwise it is a bit hard to maintain something clean I think

**Comment by LeeSmet** [comment]
I see your point, though it does mean that it will depend on keeping their installation up to date. 
Other than that, I think the data is fine

**Comment by zaibon** [comment]
Indeed, but I think this is fine. New feature, new version. make sense I think.
User will have to pull correct version of jumpscale, so I think its manageable.

**Comment by GlenDC** [comment]
let me know once I can review tfchain client code, would like to do that before it is merged in

**Comment by zaibon** [comment]
Of course, there will be a PR.
I already open a draft PR if you already want to discuss it: https://github.com/threefoldtech/jumpscaleX/pull/216
