### ISSUE TITLE
CI broken because stuck on interactive questions

### ISSUE THREAD

**Issue by zaibon** [threefoldtecharchive/jumpscaleX_archived#225]
All the travis build/test fails because one of the test ask a question interactively and makes the full test suite to hang
```
sandbox/code/github/threefoldtech/jumpscaleX/Jumpscale/data/schema/tests/testsuite/testcases/test_schema.py::SchemaTest::test013_validate_numeric_type Provide a strong secret which will be used to encrypt/decrypt your private key: 
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by serboctor** [comment]
This error is not there anymore. However, there was another pytest error. I fixed it and now I am looking into failing tests.

**Comment by serboctor** [comment]
I added a nacl configure step but the github client by default changes http urls to ssh and fails because there is no ssh key. I am looking into the client and into propagating the property the controls this change,

**Comment by rkhamis** [comment]
We should not be looking into travis anymore. We have our own CI which you can subscribe to here: https://t.me/joinchat/AAAAAEw5_dMQ9QN1UEL7GA

**Comment by rkhamis** [comment]
And as you can see in our CI, tests are passing

**Comment by zaibon** [comment]
Then you can completely remove the .travis.yml file from the repo.

**Comment by serboctor** [comment]
I'll remove the file. Is our own CI linked to github somehow? will we still be able to see when a PR breaks the build and easily track things?

**Comment by serboctor** [comment]
And what about emails when someone breaks the build? is there a way to get properly notified other than following the chat which doesn't make much sense.

**Comment by despiegk** [comment]
resolved in development_install 
way how we deal with interactivity
