### ISSUE TITLE
ansi chars in kosmos not ok

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#233]
![image](https://user-images.githubusercontent.com/6021844/54102370-6ba4e680-43c8-11e9-8416-2b73bde17b3a.png)

the ansi characters are not ok

when showing an object in shell should nicely show the colors

**Comment by abom** [comment]
There's a problem with development_types branch, installation is broken (i cannot just checkout to it and start kosmos, it gives more errors, and @rkhamis mentioned that there're more changes to base classes).

on `development`, there's no problem with something like:

![Screenshot from 2019-03-17 22-37-58](https://user-images.githubusercontent.com/511438/54497626-9e3d6a80-4905-11e9-9b07-b711c3b7374a.png)

Need to know which branch and steps you made to get such output (also the terminal emulator used would help too).
