### ISSUE TITLE
Unique attributes in schemas

### ISSUE THREAD

**Issue by rkhamis** [threefoldtecharchive/jumpscaleX_archived#236]
What we need is a way to define that certain attributes are unique in the schema.
Meaning that they cannot pre-exist in any other object in the bcdb.

Suggestion is to denote uniqueness using `!`

This will resolve issues with duplicate instance names and can have long term added value of defining unique attributes that would resolve conflicts in kosmos
(For instance, defining open ports on a certain server)

Should resolve these issues:
 - parent of: #211
 - parent of: #210

**Comment by BolaNasr** [comment]
now it works good : 
![Screenshot from 2019-03-17 17-56-34](https://user-images.githubusercontent.com/10259267/54493956-0d06cd80-48de-11e9-8fc9-4b394bd9dd42.png)


if you need make specific  attributes  unique just add & before the name : 

```
schema = """
@url =  jumpscale.test.1
giturl =  "" (S)
&dest =  "" (S)  #unique attribute
enable = true (B)
"""
```

**Comment by AhmedHanafy725** [comment]
@despiegk  @rkhamis 
1- A unit test can be found here [unique attributes](https://github.com/threefoldtech/jumpscaleX/blob/development/Jumpscale/data/schema/tests/testsuite/testcases/test_unique_attribute.py) and can be run using pytest or nosetest
2- And also here [unique attribute](https://github.com/threefoldtech/jumpscaleX/blob/development/Jumpscale/data/schema/tests/8_unique_data.py) and can be run from kosmos `j.data.schema.test('unique_data')`

But the second way is not well organized, more hard to read and will have duplicate code for `setUp` and `tearDown` if threre are more tests.
If these methods can be supported in the second approach, that will be great.

**Verified** on 2c367702c1dd8b07f20408ba8a3e812c4b863f59
