### ISSUE TITLE
representation of complex jsx object not ok

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#238]
- check /sandbox/code/github/threefoldtech/jumpscaleX/Jumpscale/data/schema/tests/3_embedded_schema.py

![image](https://user-images.githubusercontent.com/6021844/54516822-539d0c00-4960-11e9-9773-c64a4d76435c.png)

![image](https://user-images.githubusercontent.com/6021844/54516831-57c92980-4960-11e9-8ada-96855a424bb9.png)

is not ok, should be only 1 cmd as sub

**Comment by despiegk** [comment]
on development_types

**Comment by abom** [comment]
~Too much [dirty hacks](https://github.com/threefoldtech/jumpscaleX/blob/d899d086bcbbf79687b3f344d0fce8d665239a14/Jumpscale/data/schema/DataObjBase.py#L211), too much wasted time on nonsense, we should stop using them to cover our bugs!~

A `__str__` that returns empty string is evil, specially if it does `print` instead!

I edited my comment, some words should not be said this way, sorry.

**Comment by abom** [comment]
Right output:

![Screenshot from 2019-03-18 21-39-37](https://user-images.githubusercontent.com/511438/54558847-60087f80-49c7-11e9-9d8f-a0494e7e38e3.png)
