### ISSUE TITLE
Creating a reservation for capacity gives an error with GedisClientFactory

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtecharchive/jumpscaleX_archived#240]
Following this documentation: https://github.com/threefoldfoundation/info_grid/blob/development/docs/capacity_reservation/README.md

Gives me an error when I run this command in JSX branch development

```
result = w.capacity.reserve_zos_vm(
    email='user@email.com', # the email on which you will received the connection information
    threebot_id='my3bot.example', # your threebot id, it can be any of the names you gave to your 3bot
    location='farm_name', # name of the farm or node id where to deploy the workload
    size=1) # each workload have a different size available
```

Stacktrace:

<img width="882" alt="Schermafbeelding 2019-03-20 om 15 08 20" src="https://user-images.githubusercontent.com/17138347/54692843-efc44000-4b25-11e9-83b2-16c5806b7545.png">

**Comment by delandtj** [comment]
same error for me

**Comment by xmonader** [comment]
same here

**Comment by GlenDC** [comment]
same here

**Comment by DylanVerstraete** [comment]
@ahussein Should this also be moved to digitalmeX repo ?

**Comment by ahussein** [comment]
yes, or at least linked to the issue in digitalmeX

**Comment by abom** [comment]
Resolved on digitalmex (development branch).
