### ISSUE TITLE
get acls to work on models

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#247]
/sandbox/code/github/threefoldtech/jumpscaleX/Jumpscale/data/bcdb/tests/5_acls.py

check older code, acl's have partially been removed, needs to be restored so it works again

**Comment by BolaNasr** [comment]
i stoped working on it because the bcdb test fail again i'm try to fix it

**Comment by BolaNasr** [comment]
waiting for changes in **3bot_registration** branch

**Comment by BolaNasr** [comment]
Now all tests works good in ``` development-bcdb``` branch

```
kosmos "j.data.bcdb.test()"
```

**Comment by despiegk** [comment]
Kristof needs to work on this

**Comment by serboctor** [comment]
@despiegk are you working on this? shouldnt this be part of the other bcdb tasks?
