### ISSUE TITLE
zerostor builder/client [development_zstor]

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#25]
- implement j.client
    - [learn how to do it in template for client](https://github.com/threefoldtech/jumpscale10/tree/master/Jumpscale/clients/TEMPLATE)   
- implement j.builder....
    - [learn how to do it in template](https://github.com/threefoldtech/jumpscale10/tree/master/Jumpscale/builders/TEMPLATE)

## remarks

- call j.builders.golang.install()
- build the server & client
- implement some tests
- call the client

**Comment by ranatrk** [comment]
Split into two issues for the #576 builder and the #577 client.
