### ISSUE TITLE
close all open branches 

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#253]
only

- development -> master
- development_types -> development

close ALL other branches

**Comment by rkhamis** [comment]
development is now on master: https://github.com/threefoldtech/jumpscaleX/commit/24ed9db4b3092259e301b21214c6a42038199a8d

**Comment by rkhamis** [comment]
All the testing branches are now merged into development. Preparing an initiary branch for merging all branches, but will not merge it.
