### ISSUE TITLE
call unittests for schema

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#257]
/sandbox/code/github/threefoldtech/jumpscaleX/Jumpscale/data/schema/tests/7_unittests.py

**Comment by andrewayoub** [comment]
The unit tests are failing, I've opened another issue for fixing it https://github.com/threefoldtech/jumpscaleX/issues/460

**Comment by AhmedHanafy725** [comment]
**Verified** on 271f16fbe9cd78f220866ce13838f9817736b8d9
Now schema unittests can be run using `j.data.schema.test('unittests')`
But unique attributes test now is duplicated in unit tests and [here](https://github.com/threefoldtech/jumpscaleX/blob/master/Jumpscale/data/schema/tests/8_unique_data.py), can we remove one of them?

**Comment by andrewayoub** [comment]
> But unique attributes test now is duplicated in unit tests and [here](https://github.com/threefoldtech/jumpscaleX/blob/master/Jumpscale/data/schema/tests/8_unique_data.py), can we remove one of them?

I think this should be discussed in the child issue #460 to keep track of what needs to be fixed and what should be just skipped

**Comment by AhmedHanafy725** [comment]
[test_unique_attributes](https://github.com/threefoldtech/jumpscaleX/blob/master/Jumpscale/data/schema/tests/8_unique_data.py) has been removed as there is same test [here](https://github.com/threefoldtech/jumpscaleX/blob/development/Jumpscale/data/schema/tests/testsuite/testcases/test_unique_attribute.py)
