### ISSUE TITLE
j.clients.etcd.test()

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#260]
- build/start/test

**Comment by despiegk** [comment]
also see we only have 1 implementation

![image](https://user-images.githubusercontent.com/6021844/54876941-7758ca00-4e18-11e9-8fb6-4f515a43b3a9.png)

**Comment by Dina-Abd-Elrahman** [comment]
### Verification Steps:

- cll = j.clients.etcd.etcd_test
- cll.save()
- cll.api.put("url", "jumpscale.etcd.client")
-  cll.user = "dina"
- cll.password_ = "1234"
- cll.save()
- cll.backup( 
      file_obj='snapshot.db', 
    dirs='/root', 
    remote='', 
     AWS_ACCESS_KEY_ID='', 
     AWS_SECRET_ACCESS_KEY='', 
     password='1234', 
    backet='test' 
)
