### ISSUE TITLE
j.clients.traefik.test(build=True)

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#262]

**Comment by rkhamis** [comment]
Please verify test, start, build, install

**Comment by Dina-Abd-Elrahman** [comment]
- get an error when try test method 

![error](https://user-images.githubusercontent.com/21218053/56597567-0a8d4700-65f3-11e9-9e7e-bcb6b4dd0569.png)

**Comment by Dina-Abd-Elrahman** [comment]
#### Verification Steps:

- make client connection to it.
```cl = j.clients.traefik .get(name="traefik_test",etcd_name="traefik_test_etcd", user="root", password="v16ffehxnq")```

- create a proxy object.
``` proxy = cltr.proxy_create('myproxy')```

- set a backend on your proxy.
``` backend = proxy.backend_set(endpoints=['http://172.0.0.2:8080'])```

- add another server to your backend 
``` server = backend.server_add('http://172.0.0.3:8080')```

- set the weight for the load balancing on the second backend server.
``` server.weight = '20'```

- set a frontend on your proxy.
``` frontend = proxy.frontend_set('my.domain.com')```

- write the configuration into etcd
``` proxy.deploy()```

- delete all frontend and backend configuration of this proxy from etcd.
``` proxy.delete()```
