### ISSUE TITLE
bug: j.clients.tfchain.kds.blockchain_info_get()

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#268]
![image](https://user-images.githubusercontent.com/6021844/54881161-65dde500-4e4d-11e9-8a2c-f11068ed6b4b.png)

**Comment by despiegk** [comment]
I put network type on 'TEST' thats maybe the issue
should use an enumerator there

**Comment by arahmanhamdy** [comment]
Fixed: https://github.com/threefoldtech/jumpscaleX/commit/db7263cfec904e152aa1402f3bd3ee9c6b047f03
