### ISSUE TITLE
jumpscale log level to be configurable

### ISSUE THREAD

**Issue by rkhamis** [threefoldtecharchive/jumpscaleX_archived#271]
Currently the log level of jumpscale is hardcoded and should be configurable

**Comment by despiegk** [comment]
it is configurable its in the main config file

**Comment by abom** [comment]
A problem in includes and excludes config caused the log level be always 100 (regardless of what was set in config file `/sandbox/cfg/jumpscale_config.toml`.

**Comment by zaibon** [comment]
@john-kheir so this is solved that you close the issue ?
What is the procedure to set the log level now ?
