### ISSUE TITLE
bcdb as redis server is not working

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#274]
/sandbox/code/github/threefoldtech/jumpscaleX/Jumpscale/data/bcdb/tests/7_redis.py

there seem to be issues with encoding...

also need to get it to work with

RDM = redis desktop manager

so we can see the records as hsets, so easy to work with it graphically

**Comment by arahmanhamdy** [comment]
Had some issues with the tests as the current implementation of bcdb has changed than before.

**Comment by arahmanhamdy** [comment]
Stopped working on it, will continue today

**Comment by BolaNasr** [comment]
working on it

**Comment by BolaNasr** [comment]
i'm fixed bcdb as redis server with **SQLITE Backend** , but still have small issue with **ZDB backend**
**still working on it**

**Comment by BolaNasr** [comment]
now the test works good using **SQLITE Backend** and **ZDB backend**

**Comment by BolaNasr** [comment]
i have problem with redis desktop manager all keys and values **undefined**
![image](https://user-images.githubusercontent.com/10259267/56095427-213dea80-5edd-11e9-976e-82ec3921a872.png)

**Comment by BolaNasr** [comment]
**Now Everything works Good** 
![Screenshot from 2019-04-15 14-30-59](https://user-images.githubusercontent.com/10259267/56136812-ca471c80-5f93-11e9-8b53-3f395ca6db98.png)

**Comment by Dina-Abd-Elrahman** [comment]
- estimate time 3 hours:

**Comment by Dina-Abd-Elrahman** [comment]
### Verification Steps:

- we need to start zdb client and server 
``` j.servers.zdb.start() ```
``` cl = j.clients.zdb.client_admin_get(port=9901) ```

- use bcdb as a redis server 
```  j.data.bcdb.redis_server_start(zdbclient_port=9901)  ```

- check if it running inside tmux 

- and connect to it using ```redis desktop manager``` to connect to it 

![fs](https://user-images.githubusercontent.com/21218053/56355630-10d88900-61d7-11e9-80c1-c9d2f78b921a.png)

**Comment by despiegk** [comment]
![image](https://user-images.githubusercontent.com/6021844/57979737-49f85900-7a22-11e9-88c9-ec0ff4cabf46.png)

there is no data when I look at the schemas?

**Comment by despiegk** [comment]
try with kosmos 'j.data.bcdb.test(name="redis")'
and then connect, should see data

**Comment by BolaNasr** [comment]
@despiegk 
Now should work 
My PR: https://github.com/threefoldtech/jumpscaleX/pull/554 
Branch : development_redis
Need to merge 

![Screenshot from 2019-05-22 12-42-30](https://user-images.githubusercontent.com/10259267/58169087-263a4a80-7c90-11e9-998d-a64ef679bcf0.png)


![Screenshot from 2019-05-22 12-42-49](https://user-images.githubusercontent.com/10259267/58168705-2ede5100-7c8f-11e9-9424-14f6c17d84f4.png)

if you want to see all objects of schema after test 
please comment this line https://github.com/threefoldtech/jumpscaleX/blob/development/Jumpscale/data/bcdb/BCDBFactory.py#L196
because after test we close redis and clean everything

**Comment by Dina-Abd-Elrahman** [comment]
### Verification steps:

- j.data.bcdb.test(name="redis")

and connect to `Redis Desktop Manager`

![ff](https://user-images.githubusercontent.com/21218053/58237212-dd909900-7d44-11e9-9654-9cf4d4fdad58.png)

![ff](https://user-images.githubusercontent.com/21218053/58237323-221c3480-7d45-11e9-9618-ff09b6dd9575.png)
