### ISSUE TITLE
kosmos 'j.data.bcdb.test()' still 1 issue

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#275]
the tests 1-1 do work
as total not
means probably some left overs from previous tests influence new ones

**Comment by BolaNasr** [comment]
Now : ```j.data.bcdb.test() ``` works good

**Comment by AhmedHanafy725** [comment]
The started servers need to be stopped at the end of test as it will fail if start test again.

**Comment by BolaNasr** [comment]
@AhmedHanafy725  DONE fixed

**Comment by AhmedHanafy725** [comment]
It works fine
Verified on  54520f04e71f8e62effdfec6f7a4c3051aec717f
