### ISSUE TITLE
intercom client

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#28]
## implement a proper client using config mgmt

- implement j.client
    - [learn how to do it in template for client](https://github.com/threefoldtech/jumpscale10/tree/master/Jumpscale/clients/TEMPLATE)

**Comment by ranatrk** [comment]
Client uses new config:
https://github.com/threefoldtech/jumpscaleX/commit/f4086b0d93c7b81ef5d3e7391bb919e2215d3e3b

**Comment by Dina-Abd-Elrahman** [comment]
## verification steps :

- client =  j.clients.intercom.new(name='test') 
- client.save
- client.data_update()
- client.edit()
- client.data_update()
- client.delete()
