### ISSUE TITLE
link broken on base classes documentation

### ISSUE THREAD

**Issue by zaibon** [threefoldtecharchive/jumpscaleX_archived#283]
The link pointed by `j.application.JSBaseClass` in https://github.com/threefoldtech/jumpscaleX/tree/development/docs/baseclasses
doesn't point to anything anymore.

**Comment by Dina-Abd-Elrahman** [comment]
- this link https://github.com/threefoldtech/jumpscaleX/tree/development/docs/baseclasses#the-lowest-base-class still redirect to nothing.

**Comment by serboctor** [comment]
@Dina-Abd-Elrahman which branch did you validate on? it is on `development_jumpscale`.

**Comment by Dina-Abd-Elrahman** [comment]
- @serboctor no i was verifying on `development`, but i tried it now on `development_jumpscale` and it's working fine.
