### ISSUE TITLE
https://github.com/Incubaid/caddyman/blob/master/caddyman.sh -> caddy builder

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#287]
is a bad practice, we should implement this functionality directly in builder for caddy
above is too errorprone

**Comment by despiegk** [comment]
remove caddyman repo

**Comment by abom** [comment]
Install/build/start/stop is working, _flist_create is broken.

**Comment by abom** [comment]
The logic of caddyman is already moved to caddy builder (with the new way of [building caddy](https://github.com/mholt/caddy#build) since switching to go modules).

**Comment by abom** [comment]
The logic of caddyman is already moved to caddy builder (with the new way of building [caddy](https://github.com/mholt/caddy#build) since switching to go modules).
