### ISSUE TITLE
digital.me chatbot working

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#289]
- gedis changed (small changes) need to adjust the javascript client

**Comment by rkhamis** [comment]
@ranatrk please verify that chatbot still works with latest javascript fixes

**Comment by ranatrk** [comment]
- Tested with the guide of the following : https://github.com/threefoldtech/digitalmeX/tree/development/packages/system/chat/lapis 
- links used:
``` 
ln -s /sandbox/code/github/threefoldtech/digitalmeX/packages/system/chat/lapis/static/chat /sandbox/code/github/threefoldfoundation/lapis-wiki/static/chat
ln -s /sandbox/code/github/threefoldtech/digitalmeX/packages/system/chat/lapis/views/chat /sandbox/code/github/threefoldfoundation/lapis-wiki/views/chat
ln -s /sandbox/code/github/threefoldtech/digitalmeX/packages/system/chat/lapis/applications/chat.moon /sandbox/code/github/threefoldfoundation/lapis-wiki/app.moon 
```
 
- Fix done https://github.com/threefoldtech/digitalmeX/commit/913e5981b3e43e288a020786dd6f44b06e463fde
- **Successfully tested** chatbot using the following endpoint:  _ip:port/session/food_get_ where food_get is an example chatbot flow

**Comment by Dinaamagdy** [comment]
verified with the following steps
https://github.com/threefoldtech/digitalmeX/tree/development/packages/system/chat/lapis
and use the links rana mention and then start the bot and works well
