### ISSUE TITLE
ipmi client

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#29]
## make sure client is properly implemented 

- implement j.client using our new config mgmt
    - [learn how to do it in template for client](https://github.com/threefoldtech/jumpscale10/tree/master/Jumpscale/clients/TEMPLATE)

**Comment by waleedhammam** [comment]
- client follows the new config manager
- tested with a docker simulator: https://github.com/rhtyd/ipmisim-docker and worked ok
