### ISSUE TITLE
JSX builders do put as separate issues in project builders

### ISSUE THREAD

**Issue by rkhamis** [threefoldtecharchive/jumpscaleX_archived#299]
This is a storycard to track progress on migrating the used builders into the latest builder specs.

new specs are documented [here](https://github.com/threefoldtech/jumpscaleX/blob/development/docs/Internals/Builders.md)

 - [ ] apps
   - [x] BuilderDigitalME.py
   - [x] BuilderFreeflow.py
   - [ ] BuilderGitea.py
 - [ ] blockchain
   - [ ] BuilderAtomicswap.py
   - [x] BuilderBitcoin.py
   - [ ] BuilderElectrum.py
   - [x] BuilderEthereum.py
   - [x] BuilderRipple.py
   - [ ] BuilderTFChain.py
 - [ ] db
   - [ ] BuilderARDB.py
   - [ ] BuilderCockroachDB.py
   - [x] BuilderEtcd.py
   - [ ] BuilderPostgresql.py
   - [x] BuilderRedis.py
   - [ ] BuilderRocksDB.py
   - [ ] BuilderTIDB.py
   - [x] BuilderZdb.py
 - [ ] libs
   - [ ] BuilderBrotli.py
   - [x] BuilderCapnp.py
   - [x] BuilderCmake.py
   - [x] BuilderLibffi.py
   - [ ] BuilderLibs.py
   - [ ] BuilderOpenSSL.py
 - [ ] monitoring
   - [ ] BuilderGrafanaFactory.py
 - [ ] network
   - [x] BuilderCoreDns.py
   - [ ] BuilderZeroBoot.py
   - [x] BuilderZerotier.py
 - [ ] runtimes
   - [x] BuilderGolang.py
   - [x] BuilderLua.py
   - [x] BuilderNIM.py
   - [ ] BuilderNodeJS.py
   - [ ] BuilderPEP8.py
   - [ ] BuilderPHP.py
   - [x] BuilderPython.py
   - [x] BuilderRust.py
 - [ ] storage
   - [x] BuilderMinio.py
   - [x] BuilderRestic.py
   - [ ] BuilderS3Scality.py
   - [x] BuilderSyncthing.py
 - [ ] web
     - [ ] BuilderCaddyFilemanager.py
     - [ ] BuilderCaddy.py
     - [x] BuilderNGINX.py
     - [x] BuilderOpenResty.py
     - [x] BuilderTraefik.py

**Comment by Pishoy** [comment]
I will work in Freeflow

**Comment by Dina-Abd-Elrahman** [comment]
i will work on Postgresql

**Comment by abom** [comment]
Working on caddy and filemanager builders (#287 too).

**Comment by BolaNasr** [comment]
i'm finished etcd builder , and working  in traefik builder

**Comment by ranatrk** [comment]
will work on nginx builder

**Comment by 0xIslamTaha** [comment]
working on redis

**Comment by abom** [comment]
Caddy and caddy file manager are done (#296), with some fixes to golang builder, please unset and remove GO11MODULE from your env.sh if already exists, otherwise, `go get` won't work properly.

**Comment by AhmedHanafy725** [comment]
working on zdb builder

**Comment by 0xIslamTaha** [comment]
working on redis

**Comment by Dina-Abd-Elrahman** [comment]
still working in Postgresql

**Comment by BolaNasr** [comment]
**i'm finished traefik builder and working on Zerotier Builder**

**Comment by Pishoy** [comment]
working in freeflow with mariab_db

**Comment by 0xIslamTaha** [comment]
redis builder
https://github.com/threefoldtech/jumpscaleX/pull/310

**Comment by AhmedHanafy725** [comment]
working on minio builder

**Comment by arahmanhamdy** [comment]
Continued on the lua builder, it had an issue with the openssl, but removed the ospenssl option from luarocks installer and it worked fine. 
it give another error now for paths, working on it

**Comment by Dina-Abd-Elrahman** [comment]
- getting an error with postgresql build, trying to solve it.

**Comment by Pishoy** [comment]
- i finished freeflow builder, going to test it

**Comment by AhmedHanafy725** [comment]
finished minio builder, going to work on CockroachDB builder

**Comment by AhmedHanafy725** [comment]
finished CockroachDB builder

**Comment by arahmanhamdy** [comment]
Fixed the lua rsync command and tested the lua builder and webserver all is running

Started on builderNodejs

**Comment by AhmedHanafy725** [comment]
working on TIDB

**Comment by ranatrk** [comment]
working on nginx

**Comment by Dina-Abd-Elrahman** [comment]
working on postgresql

**Comment by BolaNasr** [comment]
working on BuilderNIM

**Comment by AhmedHanafy725** [comment]
finished TiDB, going to work on Syncthing builder

**Comment by BolaNasr** [comment]
Finished **NIM builder** , going to work on **Rust builder**

**Comment by ranatrk** [comment]
Finished working on nginx builder  https://github.com/threefoldtech/jumpscaleX/commit/7def8034004f475cf8fe249ce9ac8b97ede9e09f, 638f949ee01d22297d41abdd8d5b86f8bcce3e48

**Comment by andrewayoub** [comment]
not working on this currently, working on the minting telegram bot

**Comment by abom** [comment]
Trying to investigate the problems @Dina-Abd-Elrahman had with postgersql builder.

**Comment by AhmedHanafy725** [comment]
still working on syncthing

**Comment by arahmanhamdy** [comment]
still working on Nodejs builder

**Comment by Pishoy** [comment]
error when upload freeflow flist 
```
401 error 
```
checking it ..

**Comment by waleedhammam** [comment]
working on bitcoin builder

**Comment by ranatrk** [comment]
will work on ethereum builder

**Comment by abom** [comment]
Checking what's wrong with go/caddy builders (on a fresh installation).

**Comment by abom** [comment]
Caddy builder should be done (https://github.com/threefoldtech/digitalmeX/issues/41) and https://github.com/threefoldtech/jumpscaleX/issues/309.

**Comment by waleedhammam** [comment]
still working on bitcoin builder, building from source code

**Comment by AhmedHanafy725** [comment]
- Finished syncthing builder
- **CockroachDB** and **TiDB** need just to build from source to be finished.
    - CockroachDB needs also Cmake builder
    - TiDB needs also rust builder to be able to install TiKV

**Comment by ranatrk** [comment]
working on ethereum builder

**Comment by Dina-Abd-Elrahman** [comment]
- error with starting openresty https://github.com/threefoldtech/jumpscaleX/issues/319

**Comment by Dina-Abd-Elrahman** [comment]
- error with minio installation https://github.com/threefoldtech/jumpscaleX/issues/320

**Comment by ranatrk** [comment]
Finished Ethereum builder

**Comment by Dina-Abd-Elrahman** [comment]
error with python build https://github.com/threefoldtech/jumpscaleX/issues/322

**Comment by BolaNasr** [comment]
Finished **RUST builder**

**Comment by waleedhammam** [comment]
Finished Bitcoin builder

**Comment by AhmedHanafy725** [comment]
working on this issue #320

**Comment by Dina-Abd-Elrahman** [comment]
working on this issue https://github.com/threefoldtech/jumpscaleX/issues/316

**Comment by Dina-Abd-Elrahman** [comment]
found an error in Golang https://github.com/threefoldtech/jumpscaleX/issues/327

**Comment by Dina-Abd-Elrahman** [comment]
error with rust builder https://github.com/threefoldtech/jumpscaleX/issues/332

**Comment by Dina-Abd-Elrahman** [comment]
@AhmedHanafy725 fix the minio builder and i tested it and it works fine now

**Comment by Dina-Abd-Elrahman** [comment]
error with capnp builder build https://github.com/threefoldtech/jumpscaleX/issues/333

**Comment by Dina-Abd-Elrahman** [comment]
error with DigitalMe builder https://github.com/threefoldtech/jumpscaleX/issues/335

**Comment by AhmedHanafy725** [comment]
working on a fix for syncthing builder

**Comment by Pishoy** [comment]
error in environment variables in creating Freeflow builder, fixing it ..

**Comment by arahmanhamdy** [comment]
not working on it now, working on https://github.com/threefoldtech/home/issues/164

**Comment by Dina-Abd-Elrahman** [comment]
not working on it working on verification of the issues which is in verification state .

**Comment by waleedhammam** [comment]
fix lua builder https://github.com/threefoldtech/jumpscaleX/issues/342

**Comment by ranatrk** [comment]
not working on it now, working on https://github.com/threefoldtech/home/issues/164

**Comment by ranatrk** [comment]
Fix  in lua builder (sandbox) https://github.com/threefoldtech/jumpscaleX/commit/3eed5d0b9bc988ae57a76a7df7bef3323ec0963e for  issue: https://github.com/threefoldtech/home/issues/160

**Comment by abom** [comment]
Still working on Caddy (and go lang)

Caddy had some problems, more details can be found at https://github.com/threefoldtech/digitalmeX/issues/41#issuecomment-485280830.

Update: the issue has been moved to https://github.com/threefoldtech/jumpscaleX/issues/353.

I did the go tools changes because some builders need to run with custom flags or env variables set.

**Comment by Dina-Abd-Elrahman** [comment]
error in ```syncthing``` related to go_lang and @abom fixing it 

![error](https://user-images.githubusercontent.com/21218053/56498505-45fc1880-6502-11e9-9804-146d10198634.png)

**Comment by abom** [comment]
Go, syncthing, coredns, etcd should be working now (see https://github.com/threefoldtech/jumpscaleX/pull/352).

@Dina-Abd-Elrahman Can you please verify?

**Comment by abom** [comment]
Seems like filebrowser plugin doesn't build since caddy switched to go modules, see [ this issue](https://github.com/mholt/caddy/issues/2549#issuecomment-485712324), also opened [another issue at filebrowser plugin repo](https://github.com/filebrowser/caddy/issues/32).

Until that, an older build with filemanager and iyo can be used from this [flist](https://hub.grid.tf/abdelrahman/filemanager.flist.md).

@rkhamis can we promote this flist to official apps repo at https://hub.grid.tf or so?

**Comment by waleedhammam** [comment]
[fix] build python builder with tags: https://github.com/threefoldtech/jumpscaleX/commit/5e5840b394c15567314b4a5f61cbc36dfee02c94
[fix] build python builder with reset=True: https://github.com/threefoldtech/jumpscaleX/commit/f8b64f2979687c079579dd97408ea6f9dab7b7c5

**Comment by abom** [comment]
Currently, i'm trying to fix some bugs in builder_method decorator in builder base #354.

**Comment by abom** [comment]
Ensuring builders in [this list](https://github.com/threefoldtech/jumpscaleX/pull/352#issuecomment-486201446) are updated to use BuilderGolangTools.

Then will continue to migrate go based builders that uses old spec from this [list](https://github.com/threefoldtech/jumpscaleX/pull/352#issuecomment-486199996).

**Comment by abom** [comment]
Ethereum builder has been updated now at https://github.com/threefoldtech/jumpscaleX/commit/22786099715da907133bf6a43c3e1d45fa87e41e.

Now the following list should be working:

- traefik
- minio
- ethereum
- etcd
- coredns
- syncthing

Started migrating Gitea builder to new spec.

**Comment by waleedhammam** [comment]
Capnp builder & bitcoin builder: https://github.com/threefoldtech/jumpscaleX/commit/f0152cb25eb7070ad387b7ada07c508fd0b310dc
- Fix capnp builder -> add to libsfactory- that fixed python builder
- Fix bitcoin builder -> install with reset=True

**Comment by abom** [comment]
Working on other issues related to open publishing.

**Comment by Dina-Abd-Elrahman** [comment]
- problem in openresty builder ( doesn't stop ) https://github.com/threefoldtech/jumpscaleX/issues/456

**Comment by abom** [comment]
[Fixed etcd builder](https://github.com/threefoldtech/jumpscaleX/commit/35c70361da64ac017eb28c829cc518e34b4ead16) to follow the [latest build instructions](https://github.com/etcd-io/etcd/blob/master/Documentation/dl_build.md#build-the-latest-version) (etcdcrl was missing).

**Comment by Pishoy** [comment]
I have fix php-mysql setup manually in freeflow builder flist with proper configuration , going to automate that ..

**Comment by abom** [comment]
I simplified startup command for etcd builder, we don't need full configuration in a builder (https://github.com/threefoldtech/jumpscaleX/commit/315c65806ca8702e3437623d5e51234268082dfe).

**Comment by abom** [comment]
For caddy builder, things are going to be investigated (see https://github.com/mholt/caddy/issues/2549#issuecomment-490660232).

**Comment by Dina-Abd-Elrahman** [comment]
working in this issue https://github.com/threefoldtech/flist-builder-config/issues/1

**Comment by ranatrk** [comment]
working on the following issue : https://github.com/threefoldtech/jumpscaleX/issues/346

**Comment by 0xIslamTaha** [comment]
![image](https://user-images.githubusercontent.com/17981089/57659949-95ef6c00-75e4-11e9-929f-18dd64d6a0ef.png)
redis-sandbox is working fine now

**Comment by 0xIslamTaha** [comment]
working on zdb sandbox

**Comment by AhmedHanafy725** [comment]
Working on Cmake Builder

**Comment by waleedhammam** [comment]
Will work on ResticBuilder

**Comment by john-kheir** [comment]
Will work on Libffi builder

**Comment by waleedhammam** [comment]
Refactored restic builder at: https://github.com/threefoldtech/jumpscaleX/commit/a3f75fc86659fa11996f62dd051afd7894701011

**Comment by Dinaamagdy** [comment]
workinh in etcd sandbox

**Comment by 0xIslamTaha** [comment]
working on nginx sandboxing

**Comment by Dinaamagdy** [comment]
working in traefik

**Comment by waleedhammam** [comment]
working on capnp sandboxing

**Comment by 0xIslamTaha** [comment]
nginx sandboxing https://github.com/threefoldtech/jumpscaleX/commit/ee05aaacf8d14cc5a752f6c348680367761c7301
![image](https://user-images.githubusercontent.com/17981089/57777327-f7692500-7721-11e9-91eb-78972839d0c9.png)

**Comment by waleedhammam** [comment]
Refactored capnp builder at https://github.com/threefoldtech/jumpscaleX/commit/e153dfc42ccc918cd1f882cf7744e27ead607beb
- build from source code
- fixed installation
- added test
- added sandbox

**Comment by 0xIslamTaha** [comment]
working on BuilderOpenResty sandboxing

**Comment by waleedhammam** [comment]
working on zerotier builder sandboxing

**Comment by waleedhammam** [comment]
Fixed zerotier sandbox at https://github.com/threefoldtech/jumpscaleX/commit/787137f8c786e814f5b1ad7cc3916af58a9eda2f

**Comment by waleedhammam** [comment]
will work on BuilderRipple

**Comment by john-kheir** [comment]
> Will work on Libffi builder

Libffii builder is done https://github.com/threefoldtech/jumpscaleX/commit/a7576179acc86abd29b13ce1f9f0c5c2fc046169

**Comment by despiegk** [comment]
please create separate issues for this one & put in project builders

**Comment by waleedhammam** [comment]
> will work on BuilderRipple

Refactored at: https://github.com/threefoldtech/jumpscaleX/pull/489

**Comment by rkhamis** [comment]
replaced by: #492, #493, #288, #20, #16, #494, #495, #496, #24, #498, #497, #499

**Comment by rkhamis** [comment]
@all please assign yourselves to issues created above
