### ISSUE TITLE
cannot install JSX with insystem option 

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtecharchive/jumpscaleX_archived#300]
- cannot install jsx with option insystem.

![error](https://user-images.githubusercontent.com/21218053/55392897-70c70280-553c-11e9-9420-7e1c46119209.jpg)

### steps:

1- sudo docker run -it -v /home/dina/.ssh:/root/.ssh ubuntu:18.04
2- apt-get update && apt-get install git python3 curl locales unzip sudo python3-pip rsync -y
3- eval `ssh-agent`
4- ssh-add ~/.ssh/id_rsa
5- curl https://raw.githubusercontent.com/threefoldtech/jumpscaleX/development/install/install.py?$RANDOM > /tmp/install.py;python3 /tmp/install.py
 6- I choose option 1 (  in system (development) )

**Comment by Dina-Abd-Elrahman** [comment]
- Note :

it works correctly when i choose installtion without lua or openresty

**Comment by abom** [comment]
Should be fixed by https://github.com/threefoldtech/jumpscaleX/commit/71bc1a6720a70ce0e85241ae8c1511d7141c7931.

**Comment by Dina-Abd-Elrahman** [comment]
it's working now.

**Comment by 0xIslamTaha** [comment]
verified
I can install js in system with lua, openresty and wiki
