### ISSUE TITLE
cannot start kosmos, stuck on nacl/bcdb

### ISSUE THREAD

**Issue by GlenDC** [threefoldtecharchive/jumpscaleX_archived#303]
commit: a7992ad4675dbb565e6f9b1f777eaaf6910ee413
environment: ubuntu within a docker (installed using the approach described here: <https://github.com/threefoldtech/jumpscaleX/issues/250#issuecomment-477207944>

Kosmos wasn't initialised yet, so I did `kosmos --init`, after going through those steps I got stuck on:

```
Tue02 12:29 Schema.py        - 185 - schema:schema                      : L:@url = jumpscale.bcdb.group
Tue02 12:29 Schema.py        - 185 - schema:schema                      : L:name* = ""
Tue02 12:29 Schema.py        - 185 - schema:schema                      : L:dm_id* = ""
Tue02 12:29 Schema.py        - 185 - schema:schema                      : L:email* = ""
Tue02 12:29 Schema.py        - 185 - schema:schema                      : L:user_members = (LI)
Tue02 12:29 Schema.py        - 154 - schema:schema                      : line:user_members = (LI); lineproptype:'li'
Tue02 12:29 Schema.py        - 185 - schema:schema                      : L:group_members = (LI)
Tue02 12:29 Schema.py        - 154 - schema:schema                      : line:group_members = (LI); lineproptype:'li'
Tue02 12:29 Schema.py        - 185 - schema:schema                      : L:
Tue02 12:29 BCDB.py          - 102 - bcdb:bcdb                          : BCDB INIT DONE:system
Tue02 12:29 NACL.py          - 197 - j.sal.fs:systemfs                  : Read file: /sandbox/var/logs/myprocess_default.log
Tue02 12:29 NACL.py          - 388 - j.sal.fs:systemfs                  : Read file: /sandbox/cfg/nacl/default/key.priv
```

Eventually, after waiting for minutes with no change, I aborted out of that process. When I now start `kosmos` (without the `--init` flag) I get the same output, where it seems to be stuck on.

If I try to do `kosmos --init` again, it is stuck on the same thing.

**Comment by GlenDC** [comment]
Pulled latest state to ede05f0d82cac16d9cfdac604b585a6af281a050 seems to resolve this issue for me. Don't like these kind of resolutions, but can no longer reproduce this bug sadly.

**Comment by zaibon** [comment]
This commit is just a merge commit and it contains change only regarding builders....
I don't see how that could impact what you had. To me this still smells fishy...

**Comment by GlenDC** [comment]
I did not link it to indicate that _that_ commit fixed my issue. It was probably something between my last commit and the current commit.

So in case it is not clear, it would have to mean that some change in the following diff fixed it: 

https://github.com/threefoldtech/jumpscaleX/compare/a7992ad4675dbb565e6f9b1f777eaaf6910ee413...ede05f0d82cac16d9cfdac604b585a6af281a050

But than again, looking at that diff, I only see commits related to the telegram bot and builders, so that indeed didn't fix it. So the stability of kosmos is very fishy indeed.

**Comment by rkhamis** [comment]
I've tried reproducing on two new installations using the same steps you described but haven't been able to

@GlenDC if you're no longer blocked, I'll close this issue in favor of revising the NaCl component instead.

**Comment by GlenDC** [comment]
Fine for me. Not sure if it was related to the NACL or BCDB, but I guess you could close it for now.
