### ISSUE TITLE
autocompletion kosmos not ok yet

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#307]
e.g.

```
cl = j.clients.ssh.get(name="remote1",addr="188.166.116.127")
cl.TAB will not show cl.shell()
```

**Comment by abom** [comment]
https://github.com/threefoldtech/jumpscaleX/commit/e8e2c7d5e06e9bffcc1b2d82a89e6f9df85beb60

**Comment by AhmedHanafy725** [comment]
verified 
![image](https://user-images.githubusercontent.com/41957921/55948173-40741800-5c50-11e9-863d-df101b96dba2.png)
