### ISSUE TITLE
Kosmos --init still ask to generate words even when using ssh-agent

### ISSUE THREAD

**Issue by zaibon** [threefoldtecharchive/jumpscaleX_archived#313]
As far as I understand, kosmos has 2 modes for encryption.
Or you use the key in the ssh-agent or you let jumpscale generate a key for you.

But it seems that even when you choose to use the ssh-agent key, it still generate some mnemonic words but just don't use them.

**Comment by waleedhammam** [comment]
We need a private key to encrypt configurations, this private key is generated from the mnemonic words and saved on the file system encrypted with a secret. this secret is encrypted with ssh-agent key or provided secret.

**So the flow is**
- `ssh-agent key` or `provided secret` are used to generate an encrypted secret.
- secret used to encrypt/decrypt the generated private key by some mnemonic words .

So words are a must and will always be generated.
