### ISSUE TITLE
test all available builders 

### ISSUE THREAD

**Issue by 0xIslamTaha** [threefoldtecharchive/jumpscaleX_archived#316]
**Description**
As there is a new version of builders we need to test all of them and the first step should goes manually. 

**Verification Steps**
- Get a fresh JSX from development
- Check all available methods 

- [ ] build()
- [ ] build(reset=True)
- [ ] install()
- [ ] start()
- [ ] stop()

**Builders list**

 - [ ] apps
   - [ ] BuilderDigitalME.py
   - [ ] BuilderFreeflow.py
   - [ ] BuilderGitea.py
 - [ ] blockchain
   - [ ] BuilderAtomicswap.py
   - [x] BuilderBitcoin.py
   - [ ] BuilderElectrum.py
   - [x] BuilderEthereum.py
   - [ ] BuilderRipple.py
   - [ ] BuilderTFChain.py
 - [ ] db
   - [ ] BuilderARDB.py
   - [x] BuilderCockroachDB.py
   - [x] BuilderEtcd.py
   - [ ] BuilderPostgresql.py
   - [ ] BuilderRedis.py
   - [ ] BuilderRocksDB.py
   - [x] BuilderTIDB.py
   - [x] BuilderZdb.py
 - [ ] libs
   - [ ] BuilderBrotli.py
   - [x] BuilderCapnp.py
   - [ ] BuilderCmake.py
   - [ ] BuilderLibffi.py
   - [ ] BuilderLibs.py
   - [ ] BuilderOpenSSL.py
 - [ ] monitoring
   - [ ] BuilderGrafanaFactory.py
 - [ ] network
   - [x] BuilderCoreDns.py
   - [ ] BuilderZeroBoot.py
   - [x] BuilderZerotier.py
 - [ ] runtimes
   - [x] BuilderGolang.py
   - [x] BuilderLua.py
   - [x] BuilderNIM.py
   - [ ] BuilderNodeJS.py
   - [ ] BuilderPEP8.py
   - [ ] BuilderPHP.py
   - [x] BuilderPython.py
   - [x] BuilderRust.py
 - [ ] storage
   - [x] BuilderMinio.py
   - [ ] BuilderRestic.py
   - [ ] BuilderS3Scality.py
   - [ ] BuilderSyncthing.py
 - [x] web
     - [x] BuilderCaddyFilemanager.py
     - [x] BuilderCaddy.py
     - [x] BuilderNGINX.py
     - [x] BuilderOpenResty.py
     - [x] BuilderTraefik.py

**Comment by Dina-Abd-Elrahman** [comment]
- install new docker with fresh JSX installation ( development branch & with in system option )

**Comment by Dina-Abd-Elrahman** [comment]
- working on Nginx Builder.

**Comment by Dina-Abd-Elrahman** [comment]
- finished nginx builder, i tested ( build , build(reset=True) , install , start , stop, sandbox) 
- it's working fine.

**Comment by Dina-Abd-Elrahman** [comment]
will work on Traefik builder

**Comment by Dina-Abd-Elrahman** [comment]
- finished Traefik , i tested ( build, build(reset=True), start , stop, sandbox ) .
- it's working fine

**Comment by 0xIslamTaha** [comment]
caddy build, build(reset=True), start, stop functions are going well

**Comment by 0xIslamTaha** [comment]
zdb build, build(reset=True), start, stop functions are going well

**Comment by Dina-Abd-Elrahman** [comment]
openresty, build,build(reset=True), install, but  i got an error on start the builder 
https://github.com/threefoldtech/jumpscaleX/issues/319

**Comment by Dina-Abd-Elrahman** [comment]
CaddyFilemanager build , build(reset=True), start, stop functions are going well

**Comment by Dina-Abd-Elrahman** [comment]
BuilderMinio build, build(reset=True), install and i got this error while trying to install https://github.com/threefoldtech/jumpscaleX/issues/320

**Comment by Dina-Abd-Elrahman** [comment]
- builderGoLang build, build(reset=True) , install

**Comment by Dina-Abd-Elrahman** [comment]
- lua build , build(reset=True), install , start , stop functions are going well

**Comment by Dina-Abd-Elrahman** [comment]
- nim build, build(reset=True), install functions are going well

**Comment by Dina-Abd-Elrahman** [comment]
python build ( error with build ) https://github.com/threefoldtech/jumpscaleX/issues/322

**Comment by Dina-Abd-Elrahman** [comment]
error with golang https://github.com/threefoldtech/jumpscaleX/issues/327

**Comment by Dina-Abd-Elrahman** [comment]
- zerotier build, build(reset=True), install , start , stop, test functions are going well

**Comment by Dina-Abd-Elrahman** [comment]
error with rust build https://github.com/threefoldtech/jumpscaleX/issues/332

**Comment by Dina-Abd-Elrahman** [comment]
Ethereum  Builder build, build(reset=True), install , start , stop, test functions are going well.

**Comment by Dina-Abd-Elrahman** [comment]
an error with capnp build https://github.com/threefoldtech/jumpscaleX/issues/333

**Comment by Dina-Abd-Elrahman** [comment]
bitcoin builder  build, build(reset=True), install , start , stop, test functions are going well.

**Comment by Dina-Abd-Elrahman** [comment]
tidb builder build, build(reset=True), install , start , stop, test methods are going well.

**Comment by Dina-Abd-Elrahman** [comment]
coredns  builder build, build(reset=True), install , start , stop, test methods are going well.

**Comment by Dina-Abd-Elrahman** [comment]
etcd builder build, build(reset=True), install , start , stop, test methods are going well.

**Comment by Dina-Abd-Elrahman** [comment]
error with DigitalMe builder https://github.com/threefoldtech/jumpscaleX/issues/335

**Comment by Dina-Abd-Elrahman** [comment]
I'm done with all ready builders, there are some builders which not done yet 
will come back to them once they are ready

**Comment by Dina-Abd-Elrahman** [comment]
- capnp , python and digitalme build, build(reset=True), install , start , stop, test methods  working good now.

**Comment by Dina-Abd-Elrahman** [comment]
- create  a script with help of @0xIslamTaha  to test all builders automatically. 

[test](https://github.com/threefoldtech/jumpscaleX/blob/development/Jumpscale/builder/test/builder/test_cases.py)

**Comment by Dina-Abd-Elrahman** [comment]
- i got an error on openresty builder it doesn't stop (https://github.com/threefoldtech/jumpscaleX/issues/456)

**Comment by Dina-Abd-Elrahman** [comment]
- all refactored builders are green now except coredns https://github.com/threefoldtech/jumpscaleX/issues/201

- wait for other builders to be refactored to be added for test case

**Comment by 0xIslamTaha** [comment]
openresty sandbox 16f1f63cbc096b1552e89c969cc7e864e4137a23
![image](https://user-images.githubusercontent.com/17981089/57852026-57bf9b80-77e2-11e9-9a86-487b747d1953.png)

**Comment by despiegk** [comment]
too generic list, we need to create separate FR issues
