### ISSUE TITLE
cannot start openresty builder 

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtecharchive/jumpscaleX_archived#319]
i got an error while trying to start openrety. 

![ff](https://user-images.githubusercontent.com/21218053/55789206-230d4580-5aba-11e9-925d-db4403b750df.png)

**Comment by DylanVerstraete** [comment]
Cannot reproduce

**Comment by Dina-Abd-Elrahman** [comment]
- it's working now with me, and i cannot reproduce it.
