### ISSUE TITLE
have an error with minio install 

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtecharchive/jumpscaleX_archived#320]
i found this error while i'm trying to install minio

![ff](https://user-images.githubusercontent.com/21218053/55798932-6b376280-5ad0-11e9-8fd6-550e49ee1653.png)

**Comment by AhmedHanafy725** [comment]
still searching why minio build method has no error and binary is not generated.

**Comment by AhmedHanafy725** [comment]
Building minio needs this var `GO111MODULE=on`, so I couldn't use `j.builder.runtimes.golang.get` as if golang is not installed the profile will be sandbox (not builder) and can't see this var.
And it takes too much time to build, so it was needed to increase the timeout of execution.
commit 0c109665dc8231247be12c0a97577677b3835237

**Comment by Dina-Abd-Elrahman** [comment]
- i tested it and it works fine now 

build, build(reset=True), install , start , stop
