### ISSUE TITLE
mail client

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#33]
## make sure client is properly implemented 

- implement j.client using our new config mgmt
    - [learn how to do it in template for client](https://github.com/threefoldtech/jumpscale10/tree/master/Jumpscale/clients/TEMPLATE)

**Comment by waleedhammam** [comment]
- Follows the new config manager
- added minor fix and test on branch: `development_jumpscale` :https://github.com/threefoldtech/jumpscaleX/commit/2681ddcbcab00b3e3058432cc77fa8ebc8371352

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
