### ISSUE TITLE
include macro matches entire doc when marker is not found

### ISSUE THREAD

**Issue by rkhamis** [threefoldtecharchive/jumpscaleX_archived#331]
Currently the include macro includes the entire doc when a marker is not found.

I believe it makes more sense in this case that nothing is returned since the specified part is not available in the doc

@abom please advice if you think otherwise

**Comment by abom** [comment]
Sure, that should be the normal behavior! thank you and @0xIslamTaha.

**Comment by abom** [comment]
Should be fixed by https://github.com/threefoldtech/jumpscaleX/commit/3fa9669ae3b987008cdd8d1bcb387c0b080cfdd8

**Comment by john-kheir** [comment]
Verified as part of https://github.com/threefoldtech/digitalmeX/issues/42
