### ISSUE TITLE
error with rust builder

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtecharchive/jumpscaleX_archived#332]
i got an error while trying to build rust builder 
![ff](https://user-images.githubusercontent.com/21218053/55873402-da27c080-5b8f-11e9-95d9-8f95850b13ba.png)

**Comment by delandtj** [comment]
either way, that's not a way to set up a rust build env.
Check `curl https://sh.rustup.rs -sSf |less` and work from there

**Comment by DylanVerstraete** [comment]
Fixed in https://github.com/threefoldtech/jumpscaleX/pull/340

**Comment by Dina-Abd-Elrahman** [comment]
- it's working fine now.
