### ISSUE TITLE
error with digitalme builder while trying to use build method 

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtecharchive/jumpscaleX_archived#335]
j.builder.apps.digitalme.build()

![error](https://user-images.githubusercontent.com/21218053/55885132-a78ac180-5ba9-11e9-9144-a8a72aeea6b5.png)

**Comment by andrewayoub** [comment]
this is an issue in capnp builder blocking digitalme builder which uses it

**Comment by andrewayoub** [comment]
j.builder.runtimes.python.build() works now

**Comment by AhmedHanafy725** [comment]
The problem still exists
I think this problem in python builder

**Comment by Dina-Abd-Elrahman** [comment]
- digitalme and python are working good now .
