### ISSUE TITLE
error while starting kosmos or js_shell inside Docker

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtecharchive/jumpscaleX_archived#339]
- I installed JSX (insystem option inside docker) , and was trying to build some builders ( one of them is pyton builder)
after that I found the docker stopped and when i started it and was trying to login to kosmos or js_shell it gavs this error

![error](https://user-images.githubusercontent.com/21218053/56133500-d7144200-5f8c-11e9-8361-63ee1a73cf6f.png)

- output of ```/sandbox/env.sh```

``` # environment variables
export LC_ALL=en_US.UTF-8
export LD_LIBRARY_PATH="/sandbox/lib:/sandbox/bin"
export PYTHONHOME="/sandbox/var/build/python3"
export LUALIB="/sandbox/openresty/lualib"
export LANG=en_US.UTF-8
export LUA_PATH="?.lua;/sandbox/openresty/lualib/?/init.lua;/sandbox/openresty/lualib/?.lua;/sandbox/openresty/lualib/?/?.lua;/sandbox/openresty/lualib/?/core.lua;/sandbox/openresty/lapis/?.lua"
export PBASE="/sandbox"
export LUA_CPATH="/sandbox/openresty/lualib/?.so;./?.so"
export GOPATH="/sandbox/go_proj"
export PYTHONHTTPSVERIFY=0
export HOME="/root"
export GOROOT="/sandbox/go"
export HOST="9da83b85e0b8"
export LIBRARY_PATH="/sandbox/var/build/openssl/lib:/sandbox/lib:/sandbox/bin"
export PYTHONPATH=/sandbox/var/build/python3/lib/python3.7/site-packages:/sandbox/var/build/python3/lib/python3.7:/sandbox/var/build/python3/lib:/sandbox/bin:sandbox/lib/python3.7/lib-dynload:/sandbox/lib/python3.7/site-packages:/sandbox/lib/python3.7:/sandbox/lib/python.zip:/sandbox/lib:/sandbox/lib/jumpscale:$PYTHONPATH
export CPPPATH="/sandbox/var/build/openssl/include:/sandbox/var/build/python3/include/python3.7m"
export LDFLAGS="-L/sandbox/lib:/sandbox/bin"
export PATH=/sandbox/go/bin:/sandbox/go_proj/bin:/sandbox/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
export PS1="3BOTDEVEL:9da83b85e0b8:\W: "
export LAPIS_OPENRESTY="/sandbox/bin/openresty"
# includes
```

**Comment by DylanVerstraete** [comment]
Having the same issue here

output of `/sandbox/env.sh`
```
# environment variables
export LC_ALL=en_US.UTF-8
export LUALIB="/sandbox/openresty/lualib"
export LANG=en_US.UTF-8
export LUA_PATH="?.lua;/sandbox/openresty/lualib/?/init.lua;/sandbox/openresty/lualib/?.lua;/sandbox/openresty/lualib/?/?.lua;/sandbox/openresty/lualib/?/core.lua;/sandbox/openresty/lapis/?.lua"
export PBASE="/sandbox"
export LUA_CPATH="/sandbox/openresty/lualib/?.so;./?.so"
export GOPATH="/sandbox/go_proj"
export PYTHONHTTPSVERIFY=0
export HOME="/root"
export GOROOT="/sandbox/go"
export HOST="default"
export PYTHONPATH=/sandbox/bin:sandbox/lib/python3.7/lib-dynload:/sandbox/lib/python3.7/site-packages:/sandbox/lib/python3.7:/sandbox/lib/python.zip:/sandbox/lib:/sandbox/lib/jumpscale:$PYTHONPATH
export PATH=/sandbox/go/bin:/sandbox/go_proj/bin:/sandbox/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
export PS1="3BOTDEVEL:default:\W: "
export LAPIS_OPENRESTY="/sandbox/bin/openresty"
export PYTHONHOME=/sandbox
export LIBRARY_PATH=/sandbox/lib:/sandbox/bin
export LD_LIBRARY_PATH=/sandbox/lib:/sandbox/bin
export LDFLAGS=-L'/sandbox/lib:/sandbox/bin'
# includes
```

**Comment by DylanVerstraete** [comment]
I can confirm this occures after running the python builder.
`j.builder.runtimes.python.install()`

It has to something to do with `PYTHONHOME` envrionment variable, which in my case has been set to: `/sandbox`. How and why this happend I don't know. If you remove the `PYTHONHOME` like:
`unset PYTHONHOME` kosmos start but crashes with error:
```
EXCEPTION

        /sandbox/bin/kosmos                                          : 149 : if n.load(die=False) is False:
        /sandbox/lib/jumpscale/Jumpscale/data/nacl/NACL.py           : 199 : r = j.core.db.get(redis_key)

Tue 16 11:42:10 NACL.py          - 183 - load                               : EXCEPTION: 'NoneType' object has no attribute 'get'
CANNOT CONTINUE
```

To get past this I used `kosmos --init`

**Comment by DylanVerstraete** [comment]
After some research, many articles online say that setting the `PYTHONHOME` variable might not be a good idea. Its better to modify the `PYTHONPATH` variable (since we are already doing that). I think we should leave out the `PYTHONHOME` env var setters which might occur in the pythonbuilder.

Also a temporary fix for this issue is dropping the `PYTHONHOME` by calling:

`unset PYTHONHOME`

**Comment by abom** [comment]
@DylanVerstraete Great, can you check if python builder set `PYTHONHOME` anywhere and why?

**Comment by DylanVerstraete** [comment]
@abom Is there a reason why we manipulate this environment variable for the builder profiles? 

Also i've tried setting `PYTHONHOME` to multiple locations within `sandbox` and nothing seemed to work. So only unsetting this variable does the trick. I'm currently looking where I can unset this in the builder if needed.

**Comment by abom** [comment]
I checked python builder, no need to set it at all, what actually needed is copying binaries to `/sandbox`.

I think `BuilderPython.profile_sandbox_set` need to be refactored, as it manipulates current `/sandbox/env.sh` without a reason (only needed if some one is going to install python using `PythonBuilder.install`)

**Comment by DylanVerstraete** [comment]
I removed the `self.profile.env_set("PYTHONHOME","/sandbox")` and tested the builder and now it seems to work fine.

**Comment by abom** [comment]
@Dina-Abd-Elrahman Could you please verify that after successfully building python builder, kosmos can be started normally?

**Comment by Dina-Abd-Elrahman** [comment]
Estimate time ```one hour```

### Verification Steps:

1- build the python builder ```j.builder.runtimes.python.build(reset=True)```
2-  stop the docker. 
3- start it again. 
4- check the kosmos ```kosmos --init``` and i can use it without any problem. 

It's working fine, we can close the issue .
