### ISSUE TITLE
mongodbclient

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#34]
## make sure client is properly implemented 

- implement j.client using our new config mgmt
    - [learn how to do it in template for client](https://github.com/threefoldtech/jumpscale10/tree/master/Jumpscale/clients/TEMPLATE)

**Comment by waleedhammam** [comment]
Needs https://github.com/threefoldtech/jumpscaleX/issues/526

**Comment by waleedhammam** [comment]
branch: development_builder: @ https://github.com/threefoldtech/jumpscaleX/commit/dc372ef3d474039033bc7ff536532897e3128445
- Client follows the new config manager
- added test & start & stop
- check readme at: https://github.com/threefoldtech/jumpscaleX/blob/development_builder/Jumpscale/clients/mongodbclient/README.md

**Comment by Dina-Abd-Elrahman** [comment]
#### Branch: development_builder, commit: 13f187fa9c50b83483674d7bfa72e381a881e7d0

#### Verification steps:
`build and install and start mongodb server`
- j.builders.db.mongodb.build(reset=True)
- j.builders.db.mongodb.install(reset=True)
- j.builders.db.mongodb.start()

`test mongodb client`
- mcl = j.clients.mongodb.get("new_client", host="localhost", port=27017, ssl=False, replicaset="")
- mongo_client = mcl.client
- db = mongo_client.test_database
- collection = db.test_collection
- clients = db.clients
- client_id = clients.insert_one(test_doc).inserted_id
- client_id                                                                                                                                                                                              
ObjectId('5d08fbd3c4417d75c37972ab')
- db.list_collection_names() 
['clients']
