### ISSUE TITLE
Secret is lost when restarting JSX docker

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtecharchive/jumpscaleX_archived#346]
JSX branch **development**

Kosmos initialised without `ssh-agent`.

After restarting JSX docker on MacOs the secret is lost and gives me following error

```
python
root@default:/# source /sandbox/env.sh
3BOTDEVEL:default:/: kosmos


EXCEPTION

        /sandbox/bin/kosmos                                          : 149 : if n.load(die=False) is False:
        /sandbox/lib/jumpscale/Jumpscale/data/nacl/NACL.py           : 199 : r = j.core.db.get(redis_key)

Tue 16 14:59:11 NACL.py          - 183 - load                               : EXCEPTION: 'NoneType' object has no attribute 'get'
CANNOT CONTINUE
```

Can be fixed by using `kosmos --init`, but this behavious is not wanted.

**Comment by DylanVerstraete** [comment]
Following PR makes the error better: https://github.com/threefoldtech/jumpscaleX/pull/341

**Comment by GlenDC** [comment]
I have the same problem on my MacOS (where I mean with MacOS it being the host environment of the docker container where this JSX environment runs in).

**Comment by zaibon** [comment]
I tracked down the why of the error `'NoneType' object has no attribute 'get'`
it seems this patch could solve it:
```diff
diff --git a/Jumpscale/__init__.py b/Jumpscale/__init__.py
index d766efba..4f9aca55 100644
--- a/Jumpscale/__init__.py
+++ b/Jumpscale/__init__.py
@@ -66,12 +66,10 @@ class Core():
         self._db_fakeredis = False
 
 
-    @property
-    def _db_fake(self):
-        # print("CORE_MEMREDIS")
+    def _load_fake_redis(self):
         import fakeredis
-        self._db = fakeredis.FakeStrictRedis()
         self._db_fakeredis = True
+        return fakeredis.FakeStrictRedis()
 
     @property
     def db(self):
@@ -81,7 +79,7 @@ class Core():
             self._db = MyEnv.db
 
             if not self._db:
-                self._db = self._db_fake
+                self._db = self._load_fake_redis()
 
         return self._db
 
~
```
But I'm really not sure this doesn't have other side effects on the rest of the loading of the secrets cause I also found:
https://github.com/threefoldtech/jumpscaleX/blob/master/Jumpscale/data/nacl/NACL.py#L130-L131
which seems to expect to have `j.core.db` to None... So I'm very confused

**Comment by zaibon** [comment]
This is not limited to OSX anymore. I also had the case with a container running on linux.
Which make sense since in the container the host system doesn't matter.

**Comment by ranatrk** [comment]
**Scenario to test**
I tested by creating the secret initially by `kosmos --init` with the following options:
- don't use ssh-agent
- generate private key

Then restarted the container and accessed it using `ssh root@ip_of_container`


**Attempt to fix**
When trying the change below, the db is returned successfully as it wasn't returned initially.

(**file: Jumpscale/\_\_init__.py** )
![Screenshot from 2019-05-12 15-48-58](https://user-images.githubusercontent.com/17128393/57583143-d7d9be80-74cd-11e9-96cb-4b0a2ad12fd0.png)

But this results in another issue where the secret retrieved from the database doesnt match the one added and the exception below is raised:
![Screenshot from 2019-05-12 15-52-24](https://user-images.githubusercontent.com/17128393/57583158-fdff5e80-74cd-11e9-8a65-ba0e14d4c0a2.png)

Therefore still investigating.

**Comment by ranatrk** [comment]
The encrypted secret that is saved is not equal to the secret that is loaded when the restart of the container occurs. Still investigating what causes the changes in the file with the saved secret.

**Comment by despiegk** [comment]
please make sure you develop op development branch

**Comment by ranatrk** [comment]
The issue is that redis didn't have persistence option enabled. Therefore the secret was lost once the restarting of the container occured and redis was closed.
**Proposed solution 1**: add persistence option to redis

**Comment by ranatrk** [comment]
**Issue with solution 1**: the secret shouldn't be saved anywhere on disk for security reasons

**Proposed solution 2**: When no ssh agent is used, and the key is not found, then the user is prompted to input the secret key they chose before

**Comment by ranatrk** [comment]
Fix according to **proposed solution 2** : https://github.com/threefoldtech/jumpscaleX/commit/02ba7660d3707caf7bf8c561654dd2180871668b (new branch created development_bcdb)

When ssh-agent is not used, and the docker container is restarted, once the secret is not found the user will be prompted to enter the key. It should be the same as the old one to be able to retrieve the old data, otherwise `kosmos --init` should be used to reinitialize all keys

**Comment by zgorizzo69** [comment]
hello @ranatrk I made some comments on the fix 
on the global picture what I understood is that we ask for a secret or passphrase from the user to encrypt the privkey right ? 

But in the implementation we save that secret inside redis and to avoid saving it in clear text we encrypt it based on another secret generated and saved to a file in the container. 
So when we can't find that secret in memory anymore we ask the user for it. 

Wouldn't it be more efficient to just not save the secret and ask for it when it is not in the memory ?

Also I think we don't encrypt the privkey based on the user secret but based on the generated secret stored as a file. see the `configure` and `load` methods from NACL.py.  we have `self._box = nacl.secret.SecretBox(key)` and then in the encryptSymmetric function box = self.box

**Comment by ranatrk** [comment]
> on the global picture what I understood is that we ask for a secret or passphrase from the user to encrypt the privkey right ?

What I understood from the implementation is that the key is the one used to encrypt the private key not the secret

> Wouldn't it be more efficient to just not save the secret and ask for it when it is not in the memory ?

If that happens then it wont be ever in memory and so will need to be added whenever needed by the user. Other than the issue of too many prompts, using scripts will be an issue.



> Also I think we don't encrypt the privkey based on the user secret but based on the generated secret stored as a file. see the `configure` and `load` methods from NACL.py. we have `self._box = nacl.secret.SecretBox(key)` and then in the encryptSymmetric function box = self.box

Yes that is true. I understood from the code the use of the key to encrypt/decrypt instead of the secret, but I'm not sure if that is the correct implementation. I paused on working on this for now as @despiegk is currently working on changes as mentioned before that affect this part.

**Comment by ranatrk** [comment]
With the changes according to https://github.com/threefoldtech/jumpscaleX/issues/515 , this issue no longer appears when restarting the docker container
