### ISSUE TITLE
mysql client

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#35]
## make sure client is properly implemented 

- implement j.client using our new config mgmt
    - [learn how to do it in template for client](https://github.com/threefoldtech/jumpscale10/tree/master/Jumpscale/clients/TEMPLATE)

**Comment by ranatrk** [comment]
Fixed some errors in the function `get()`  when running the following to abide by the new configuration mgmt (have a schema):
`j.clients.mysql.get(ipaddr="ipaddr",port=port,login="login",passwd="passwd",dbname="dbname") `

Current status:
When running the previous command the following error is triggered:
![Screenshot from 2019-06-09 17-56-20](https://user-images.githubusercontent.com/17128393/59161230-626b0900-8ae0-11e9-9d8b-2d60d3241bfe.png)
Even though mysql can be accessed with ` mysql -u root -p `.
Therefore still investigating

**Comment by ranatrk** [comment]
**note:** [development_clients] -> new branch created with PR
### Progress:
Can get client, connect to MySQL server, select rows and delete rows.

###  Steps:
- Create db and table manually in MySQL server
- Add some test rows to the table created manually
- Get a new client instance which connects to the MySQL server running(using the db created)
- Select rows from the table in the db using the client
- Delete row from the table in the db using the client (with WHERE clause)
- Select the deleted rows from the table in the db using the client to get nothing as they were deleted successfully 
![Screenshot from 2019-06-10 17-50-48](https://user-images.githubusercontent.com/17128393/59208173-dcff5b80-8ba8-11e9-8129-4bc82eee14ed.png)

**Comment by ranatrk** [comment]
The following was used in MySQL to allow connection by the user:
`GRANT ALL PRIVILEGES ON *.* TO 'test'@'localhost' IDENTIFIED BY 'password';`

**Comment by Pishoy** [comment]
got issue when delete a record is not deleted as below 
```
JSX> cl.select1('tasks','*',"task_id=2")                                                             
[(2, 'test client2', datetime.date(2019, 6, 10), datetime.date(2019, 6, 11), 1, 1, 'nodesc')]

JSX> cl.deleteRow('tasks','task_id=2')  

mysql> select * from tasks ;
+---------+--------------+------------+------------+--------+----------+-------------+
| task_id | title        | start_date | due_date   | status | priority | description |
+---------+--------------+------------+------------+--------+----------+-------------+
|       2 | test client2 | 2019-06-10 | 2019-06-11 |      1 |        1 | nodesc      |
+---------+--------------+------------+------------+--------+----------+-------------+
```

- another suggest to make the where clause  as optional , is that valid ? as below gives error 
```
JSX> cl.select1('tasks','*')                                                                                                                                                                                
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: select1() missing 1 required positional argument: 'whereclause'

select1() missing 1 required positional argument: 'whereclause'
```
- what about adding methods like insert, update, ... ?

**Comment by ranatrk** [comment]
- Fixed deletion issue
- Where clause in **_select1_** is now optional, if not given then `SELECT fieldname FROM tablename` is used
- **_insert_** row function is added 

Fixes : https://github.com/threefoldtech/jumpscaleX/commit/0eda984ea462754e0538d4ce3c7ed7e8b97c492b
**Branch:  [development_jumpscale]**

**Comment by Pishoy** [comment]
verified 
```
JSX> cl.select1('tasks','*')                                                                         
[(2, 'test client2', datetime.date(2019, 6, 10), datetime.date(2019, 6, 11), 1, 1, 'nodesc'), (3, 'mytile', datetime.date(2019, 6, 12), datetime.date(2019, 6, 13), 1, 1, 'thridone')]

JSX> cl.deleteRow('tasks','task_id=2')                                                               
JSX> cl.select1('tasks','*')                                                                         
[(3, 'mytile', datetime.date(2019, 6, 12), datetime.date(2019, 6, 13), 1, 1, 'thridone')]

JSX> cl.deleteRow('tasks','task_id=3')                                                               
JSX> cl.select1('tasks','*')                                                                         
JSX> cl.insert('tasks',"4,'mytile','2019-06-12','2019-06-13', 1,1,'fouthone'")                       
JSX> cl.select1('tasks','*')                                                                         
[(4, 'mytile', datetime.date(2019, 6, 12), datetime.date(2019, 6, 13), 1, 1, 'fouthone')]

```
