### ISSUE TITLE
Any change in schema force to delete the all bcdb database use for config manager

### ISSUE THREAD

**Issue by zaibon** [threefoldtecharchive/jumpscaleX_archived#350]
As shown by https://github.com/threefoldtech/jumpscaleX/issues/211
If there are any change in a schema, some very weird an unpredictable behavior starts to appears.

#221 is an example where we couldn't delete a client anymore while no error was ever raised or any error message printed.

completely deleting `/sandbox/var/bcdb/system` seems to be solution proposed to solve the issue.
This is not a valid fix, since doing that similar to loosing all your data.

We need a process where we can upgrade a schema and still be able to continue using our data. Without that, config manager cannot be ever used in production.

**Comment by BolaNasr** [comment]
@zaibon  now should works good you don't need anymore to delete all bcdb data when change schema it's made migration of meta and database by itself

**Comment by AhmedHanafy725** [comment]
1- Create schema 
```
scm = """@url=test.schema.1 
name = "test" (S) 
number = 10 (I) 
""" 
```
2- Make model and save

```
model = j.application.bcdb_system.model_get_from_schema(scm)
schema = model.new()
schema.save()
```
3- Change in schema
```
scm = """@url=test.schema.1 
name = "test" (S) 
number = 10 (I) 
new = "test2" (S)
""" 
```
4- Make model again
```
model = j.application.bcdb_system.model_get_from_schema(scm)
```

**Got this error**
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDB.py", line 280, in model_get_from_schema
    model = myclass(reset=self._need_to_reset, bcdb=self, schema=schema)
  File "/sandbox/var/codegen/_4919009dcd530c8c5ed265d0b611a29f.py", line 21, in __init__
    MODEL_CLASS.__init__(self, bcdb=bcdb,schema=schema,reset=reset)
  File "/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDBModel.py", line 68, in __init__
    self._init_()
  File "/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDBModel.py", line 99, in _init_
    self.schema = self.bcdb.meta.schema_set(self.schema)
  File "/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDBMeta.py", line 163, in schema_set
    self.migrate_data(schema)
  File "/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDBMeta.py", line 194, in migrate_data
    m = model.new()
AttributeError: 'ModelOBJ' object has no attribute 'new' 
```

**Comment by despiegk** [comment]
think is no longer relevant, new code in development branch

**Comment by rkhamis** [comment]
This is obsolete now with the new installer https://github.com/threefoldtech/jumpscaleX/pull/546
