### ISSUE TITLE
builder base class has a lot of bugs

### ISSUE THREAD

**Issue by serboctor** [threefoldtecharchive/jumpscaleX_archived#354]
The `builder_method` decorator which is used for all builder functions has a lot of problems:
1) it supports passing args and kwargs but for the zhub_client it explicitly checks the kwargs while it actually may be passed in args. And if it is passed in args you can't really know its location in the args because the `sandbox` function signatures doesn't seem to be consistent across all builders. https://github.com/threefoldtech/jumpscaleX/blob/development/Jumpscale/builder/system/BuilderBaseClass.py#L52
And the same goes for https://github.com/threefoldtech/jumpscaleX/blob/development/Jumpscale/builder/system/BuilderBaseClass.py#L70 which I kept like that to at least be consistent with the first check.
A possible solution is may be to not allow args to at least avoid bugs or unexpected behavior.

2) If your `sandbox` function has `flist_create` argument with a default `True` value and you don't explicitly set the argument to True in your call `builder.sandbox()`, the `builder_method` only sees the kwargs you sent, and accordingly it will consider that the flist_create is not True and won't create the flist even though in your builder's signature it defaults to True. This is of course applicable to any kwargs that have a default value in the signature and is used in `builder_method` decorator.

**Comment by abom** [comment]
For (1): I think as you proposed, using only kwargs would solve the problem.
For (2): Don't know for sure what should be done here, now checking current behavior again with any variable that's passed to the decorated method.

I'm also trying to figure out how arguments like reset should be propagated to other builders used withing the decorated method (dependency?)

**Comment by abom** [comment]
As we cannot ensure the user will just use keyword arguments with `builder_method` decorated methods, i'm trying to find a simpler way.

This won't work too:
~Another complex way of doing it, is by getting argument spec by example using `inspect.getargspec`, and re-construct the positional arguments to know the order/location of passed parameters...etc.~

**Comment by abom** [comment]
Inspecting decorated function arguments and convert all of positional arguments to keyword arguments is implemented at https://github.com/threefoldtech/jumpscaleX/pull/450.

But after the discussion, @rkhamis and @serboctor proposed forcing the usage of keyword arguments by the caller, then we will need to look for any call that uses positional arguments to make sure we don't break anything.

For now, the solution at https://github.com/threefoldtech/jumpscaleX/pull/450 should be tested.

**Comment by abom** [comment]
The second point is not done yet, defaults are ignored.

**Comment by abom** [comment]
The seconds point should be fixed now (https://github.com/threefoldtech/jumpscaleX/pull/450/commits/92678e5d27ca2b2f067309c01c43ad6351c193dc)

**Comment by despiegk** [comment]
is this now done or not?
it has always been intended to use as kwargs which should be default way of calling methods in python anyway

**Comment by abom** [comment]
@despiegk You closed https://github.com/threefoldtech/jumpscaleX/pull/450, then merged the commits into another branch, without saying why, i don't even know where the commits are now :)

**Comment by despiegk** [comment]
it was impossible to know which branches do what and you guys were on holiday
progress had to be made
we are changing way how we work with projects so it becomes easier, close for now
