### ISSUE TITLE
self.__jslocation__  -> class 

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#4]
look for all instances of 

self.__jslocation__ =

needs to become like

# BEFORE

```
from Jumpscale import j


class PacketNetFactory(j.application.JSFactoryBaseClass):

    def __init__(self):
        self.__jslocation__ = "j.clients.packetnet"
        self.__imports__ = "packet"
        self.connections = {}
        JSConfigFactory.__init__(self, PacketNet)

    def interactive_test(self):
        from IPython import embed
        embed(colors='Linux')
```

# NEEDS TO BECOME

```
from Jumpscale import j
from .PacketNet import PacketNet

class PacketNetFactory(j.application.JSFactoryBaseClass):
    __jslocation__ = "j.clients.packetnet"
    _CHILDCLASS = PacketNet


    def __init(self):
        self.connections = {}


```
- notice: _init

**Comment by rkhamis** [comment]
clients that need changing:
 
 - [x] blockchain 
 - [x] btc_alpha
 - [x] coredns
 - [x] currencylayer
 - [x] etcd
 - [ ] gdrive ( doesn't have location , template , factory )
 - [x] git
 - [x] gitea
 - [x] github
 - [x] google_compute
 - [x] grafana
 - [x] graphite
 - [x] http
 - [x] influxdb
 - [x] intercom
 - [x] ipmi
 - [x] itsyouonline
 - [x] kraken
 - [x] kubernetes
 - [x] mail
 - [x] mongodbclient
 - [x] mysql
 - [x] oauth
 - [x] openvcloud
 - [x] ovh
 - [x] packetnet
 - [x] peewee
 - [x] portal
 - [x] postgresql
 - [x] racktivity
 - [x] redis
 - [x] redisconfig
 - [x] rogerthat
 - [x] s3
 - [x] sqlalchemy
 - [x] ssh
 - [x] sshagent
 - [x] sshkey
 - [x] syncthing
 - [x] tarantool
 - [x] telegram_bot
 - [x] threefold_directory
 - [x] traefik
 - [x] trello
 - [x] virtualbox
 - [x] webgateway
 - [x] zdb
 - [x] zero_boot
 - [x] zero_hub 
 - [x] zero_hub_direct
 - [x] zero_os_protocol
 - [ ] zero_stor (Not Implemented)
 - [x] zerotier

**Comment by despiegk** [comment]
suggest to just do a search on self.__jslocation__
easy to find & fix
