### ISSUE TITLE
postgresql client

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#40]
## make sure client is properly implemented 

- implement j.client using our new config mgmt
    - [learn how to do it in template for client](https://github.com/threefoldtech/jumpscale10/tree/master/Jumpscale/clients/TEMPLATE)

**Comment by waleedhammam** [comment]
- Uses the new config manager
- Fix and test on branch `development_jumpscale`: https://github.com/threefoldtech/jumpscaleX/commit/ceaa2e9beb9e9aa3bf0a57f07dabb4eaf3b25a15

**Comment by Dina-Abd-Elrahman** [comment]
cannot build postgres builder https://github.com/threefoldtech/jumpscaleX/issues/603 
so i'm blocked till we solve this issue

**Comment by Dina-Abd-Elrahman** [comment]
- postgresql builder is working fine on development_builder branch, and i'm testing now postgresql client on development branch.

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
