### ISSUE TITLE
trello client

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#44]
## make sure client is properly implemented 

- implement j.client using our new config mgmt
    - [learn how to do it in template for client](https://github.com/threefoldtech/jumpscale10/tree/master/Jumpscale/clients/TEMPLATE)

**Comment by ranatrk** [comment]
client uses new config mgmt:
https://github.com/threefoldtech/jumpscaleX/commit/f4086b0d93c7b81ef5d3e7391bb919e2215d3e3b

**Comment by Dina-Abd-Elrahman** [comment]
## verification steps:

- j.clients.trello.new(name='test', api_key_ ='API_KEY', token_ = 'TOKEN', secret_ = "PASSWORD", token_secret_  = "PASSWORD") 
- client = _
- client.data_update()
- client.data
- client.save()
- client.edit()
-  client.data_update()
- client.delete()
