### ISSUE TITLE
TF Directory

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#45]
## make sure client is properly implemented 

- implement j.client using our new config mgmt
    - [learn how to do it in template for client](https://github.com/threefoldtech/jumpscale10/tree/master/Jumpscale/clients/TEMPLATE)

**Comment by waleedhammam** [comment]
works properly

**Comment by waleedhammam** [comment]
Current progress: Making a readme documentation.

**Comment by waleedhammam** [comment]
added readme at: https://github.com/threefoldtech/jumpscaleX/commit/0003dd63c3c506d5d363bd1b3d0a35f428910d20

**Comment by Dina-Abd-Elrahman** [comment]
### Branch: `development`, fda36c0c5f5a7836b1b037a1b87cbc600afc7cf3 .

### Verification Steps:

- making a client: 
`test_cl = j.clients.threefold_directory.test_cl`
`test_cl.save()`

- test some methods:
`j.clients.threefold_directory.farmers`
`j.clients.threefold_directory.capacity`
`j.clients.threefold_directory.resource_units()`

- test API:
`test_cl.api.ListCapacity()`
`test_cl.api.GetCapacity("NODE_ID")`
