### ISSUE TITLE
Make jumpscalex tests run green

### ISSUE THREAD

**Issue by rkhamis** [threefoldtecharchive/jumpscaleX_archived#451]
See logs in the chatbot:  https://t.me/jumpscaleX_tests

**Comment by AhmedHanafy725** [comment]
### Failed Tests:
- [x]  `j.data.bcdb.test()`
- [x] `j.clients.sshagent.test()`
- [x] `j.clients.sshkey.test()`
- [x] Sal.ubuntu `test_apt_install_version`
- [x] Markdown `test_include_from_other_repo`
- [x] Markdown `test_include_custom_link`
#### Builders
- [x] Openresty
- [x] Digitalme 
- [x] Python 
- [x] Bitcion
- [x] Etcd
- [x] Capnp
- [x] Coredns 
- [x] Syncthing
- [x] Minio

#### Schema
- [x] Ipport 
- [x] Iprange
- [x] Url
- [x] Numeric
- [x] Guid
- [x] Hash
- [x] Multiline
- [x] Yaml 
- [x] Enum
- [x] Binary 
- [x] Unique attributes

**Comment by AhmedHanafy725** [comment]
commit: 9c455233a8e70154adc41bac92e934fd3b00799f 
Fix Sal.ubuntu `test_apt_install_version`
Fix schema unique attributes

**Comment by Dina-Abd-Elrahman** [comment]
- problem with openresty builder https://github.com/threefoldtech/jumpscaleX/issues/456

**Comment by AhmedHanafy725** [comment]
Commit: f0152cb25eb7070ad387b7ada07c508fd0b310dc
Fix capnp builder and python builder
Commit: a59f27d6a5c898d33fc62405737dab4065e2e00f & f0152cb25eb7070ad387b7ada07c508fd0b310dc
Fix bitcion builder

**Comment by Dina-Abd-Elrahman** [comment]
Commit: https://github.com/threefoldtech/jumpscaleX/commit/2adab7c0d71a6068e696d23120cff04af5de103f
fix openresty problem https://github.com/threefoldtech/jumpscaleX/issues/456

**Comment by AhmedHanafy725** [comment]
schema tests #460

**Comment by AhmedHanafy725** [comment]
@BolaNasr 
He fixed bcdb test commit: 790e0297c37813b72bb6677e0e15834927b38f85
@Dina-Abd-Elrahman 
She fixed syncthing builder (stop method) commit: 1ae45f66cd4aebc0997d716394cba84e4c29db87
@abom 
He fixed etcd builder (start method) commit: 315c65806ca8702e3437623d5e51234268082dfe

**Comment by AhmedHanafy725** [comment]
Now we have all tests passed except schema and ssh tests
[Result](http://188.165.233.148:6010/8942e74.log)

**Comment by BolaNasr** [comment]
@AhmedHanafy725  now schema tests Green

**Comment by AhmedHanafy725** [comment]
@rkhamis @ramezsaeed 
Now we have all tests passed except sshkey.test()
But builder tests sometimes fail because:
- it couldn't pull a repo.
- timeout (time limit = 10 min per execution).

Another thing builder tests take at least (in case of one single push) about one hour and if there are more pushes it takes about 1-2 hours.
So I suggest not to run builder tests with every push and run them once a day.

**Comment by ranatrk** [comment]
sshKey test fix : https://github.com/threefoldtech/jumpscaleX/commit/608e96c0cf5acf0f8f533cce3cda7f7b95072635

**Comment by rkhamis** [comment]
@AhmedHanafy725 build tests should only run nightly, I agree

**Comment by AhmedHanafy725** [comment]
Tests passed now [here](http://188.165.233.148:6010/e1e4828.log).
Going to make nightly test for builders

**Comment by AhmedHanafy725** [comment]
Nightly test script for builders b65fde9adfe4c4f8c5c50f216c1e798d7319f83c

**Comment by AhmedHanafy725** [comment]
Nightly builders test passed [here](http://188.165.233.148:6010/2019-05-09_builders.log)
