### ISSUE TITLE
RuntimeError: myenv should have been inited by system

### ISSUE THREAD

**Issue by MathiasDeWeerdt** [threefoldtecharchive/jumpscaleX_archived#455]
When attempting to install jumpscale using the following command:
- python3 /tmp/install.py -3  -d --image=hub

I receive the following error:
- RuntimeError: myenv should have been inited by system

Sidenote: The two links inside the install.md guide point to the same install.py file. 

OS: Ubuntu 18.04
Trying to run jumpscale inside a docker container.

**Comment by arahmanhamdy** [comment]
Please make sure that you are using the development branch
