### ISSUE TITLE
sshagent client test raise an error

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtecharchive/jumpscaleX_archived#458]
#### Steps:
`j.clients.sshagent.test()`

#### Result
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sandbox/lib/jumpscale/Jumpscale/clients/sshagent/SSHAgent.py", line 469, in test
    skey.load()
  File "/sandbox/lib/jumpscale/Jumpscale/clients/sshkey/SSHKey.py", line 112, in load
    j.clients.sshagent.key_load(self.path, passphrase=self.passphrase, duration=duration)
  File "/sandbox/lib/jumpscale/Jumpscale/clients/sshagent/SSHAgent.py", line 236, in key_load
    j.sal.process.execute(C, showout=False)
  File "/sandbox/lib/jumpscale/Jumpscale/sal/process/SystemProcess.py", line 87, in execute
    env=env,interactive=interactive,replace=replace)
  File "/sandbox/lib/jumpscale/Jumpscale/core/InstallTools.py", line 1007, in execute
    timeout=timeout,die=die,env=env,self=self,interactive=interactive,asfile=False,original_command=command )
  File "/sandbox/lib/jumpscale/Jumpscale/core/InstallTools.py", line 1151, in execute
    raise RuntimeError(msg)
RuntimeError: 
Could not execute: 'bash /tmp/jumpscale/scripts/41942.sh'stderr:
    Error connecting to agent: No such file or directory

```

**Comment by AhmedHanafy725** [comment]
#451

**Comment by ranatrk** [comment]
When running the script using bash only outside kosmos the key is loaded to the agent, but when using the j.process.execute(cmd) command in kosmos the error is raised. Still investigating why.

**Comment by ranatrk** [comment]
- **ISSUE 1:** The issue was in using `kill()` and `start()` functions of the sshagent where the sshagent was not accessible after killing it even if restarted a process. A flag was no updated correctly when starting the ssh agent again. (Fixed)

- **ISSUE 2:** `sshkey.is_loaded()` doesnt return a correct result. still investigating.

**Comment by ranatrk** [comment]
- **ISSUE 2(Update):** sshkey.is_loaded() doesnt return a correct result. The `j.clients.sshagent.keys_list()` doesnt update the list if _inited flag is already True when the agent was first started.

- **ISSUE 3:** The _inited needs to be updated to False in the `check()` function in the case of the agent being killed unexpectedly and then check recalled to try and start the agent. Still investigating how this can be done without resulting in an infinite loop when there is a permenant issue in starting the agent

**Comment by ranatrk** [comment]
https://github.com/threefoldtech/jumpscaleX/commit/4ea4e106ac15c7c9565574aaf731ea5684c5b6e5

Fixes :
-  **ISSUE 2:** if _inited is True, then get_key_list() is called again thereby updating the keys_list
- **ISSUE 3**: If the agent is killed unexpectedly then starting it again fails, then the flag `_inited` will be reset to False then `check()` is called again . If the start is failed this time then an error will be raised.
- j.clients.sshagent.test() is successfully completed

**Comment by AhmedHanafy725** [comment]
**Verified** 
it works fine
