### ISSUE TITLE
telegram bot

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#46]
## make sure client is properly implemented 

- implement j.client using our new config mgmt
    - [learn how to do it in template for client](https://github.com/threefoldtech/jumpscale10/tree/master/Jumpscale/clients/TEMPLATE)

**Comment by ranatrk** [comment]
Client config implemented:
https://github.com/threefoldtech/jumpscaleX/commit/9ce65b7246314c1ec24da6d038f6a1d3781a6dac

**Comment by Dina-Abd-Elrahman** [comment]
## Verification steps:

- j.clients.telegram_bot.new(name='NAME", bot_token_ = "BOT_TOKEN")
- client = _
- client.save()
- client.data_update()
- client.view() 
- client.data
- client.edit()
- client.data
- client.data_update()
- client.delete()
