### ISSUE TITLE
Schema unit tests fails

### ISSUE THREAD

**Issue by andrewayoub** [threefoldtecharchive/jumpscaleX_archived#460]
schema unit tests fails

**Comment by despiegk** [comment]
on which branch?

**Comment by BolaNasr** [comment]
@despiegk  at development branch , and i will try to fix it

**Comment by BolaNasr** [comment]
it's Now work Good

**Comment by AhmedHanafy725** [comment]
I can see that All tests passed, but there are 3 tests skipped with no issue.
Can you check them?

**Comment by BolaNasr** [comment]
@AhmedHanafy725  now all tests works

**Comment by AhmedHanafy725** [comment]
**verified** on commit: a9cdee03217422c511d862efb3b5677d55626291
