### ISSUE TITLE
Can't create docker using sal

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtecharchive/jumpscaleX_archived#468]
Try to create docker using sal but raise the following error 
do = j.sal.docker.create(name="test", ports="22:8080")                                                                                                                                                 
```
Thu 09 07:12:25 Docker.py        - 247 - j.sal.docker:docker                : create:test
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sandbox/lib/jumpscale/Jumpscale/tools/docker/Docker.py", line 249, in create
    running = [item.name for item in self.containers_running]
  File "/sandbox/lib/jumpscale/Jumpscale/tools/docker/Docker.py", line 97, in containers_running
    for container in self.containers:
  File "/sandbox/lib/jumpscale/Jumpscale/tools/docker/Docker.py", line 43, in containers
    for obj in self.client.containers():
  File "/root/.local/lib/python3.6/site-packages/docker/api/container.py", line 208, in containers
    res = self._result(self._get(u, params=params), True)
  File "/root/.local/lib/python3.6/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/root/.local/lib/python3.6/site-packages/docker/api/client.py", line 230, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
JSX>  
```

**Comment by serboctor** [comment]
This error happens because docker is not installed. I am creating a builder for docker and fixing other bugs in the sal.

**Comment by serboctor** [comment]
relates to https://github.com/threefoldtech/jumpscaleX/issues/501

**Comment by serboctor** [comment]
The docker sal works fine now. However, to test this, if your jumpscale will already be running inside a docker then this docker needs to be started with `--privilaged` AND `-v <any local dir>:/var/lib/docker` otherwise having a docker inside a docker won't work.

For more info about using docker inside docker and why we need these arguments, please check this https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/

Since this task is coupled with the docker builder, the fixes are pushed on `development_builder` not `development_jumpscale`.

**Comment by Dina-Abd-Elrahman** [comment]
error with `container_get_by_id` method

![error](https://user-images.githubusercontent.com/21218053/58763024-59b18a80-8556-11e9-8de5-4da60ce392f6.png)

**Comment by serboctor** [comment]
@Dina-Abd-Elrahman  I fixed the function to return the correct error if the id doesn't exist. Please pull and check again.

**Comment by Dina-Abd-Elrahman** [comment]
the problem in functionality not in syntax only,  it cannot find the docker even if the id exists. 

![error](https://user-images.githubusercontent.com/21218053/58863352-fab55800-86b2-11e9-8138-892cac436bf7.png)

**Comment by serboctor** [comment]
I tried it with the Id yesterday and it was working fine. But I was using the full Id not the shortened one. Can you try the full Id and let me know.  @Dina-Abd-Elrahman

**Comment by Dina-Abd-Elrahman** [comment]
- it's working fine with full ID
