### ISSUE TITLE
conflicted BuilderRedis.py on development-bcdb

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#479]
/sandbox/lib/jumpscale/Jumpscale/builder/db/BuilderRedis.py

I commented the code but its a lot of conflicts after merge from development in development-bcdb, need to fix

**Comment by AhmedHanafy725** [comment]
Outdated the branch already had been merged and I can see `/sandbox/lib/jumpscale/Jumpscale/builder/db/BuilderRedis.py` has no conflict now.
