### ISSUE TITLE
zdb builder/client

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#48]
## make sure client is properly implemented 

- implement j.client using our new config mgmt
    - [learn how to do it in template for client](https://github.com/threefoldtech/jumpscale10/tree/master/Jumpscale/clients/TEMPLATE)   

- builder see templates in builder dir

**Comment by ranatrk** [comment]
zdb client config implementations: zdb client now has get, save, delete, and data_update

- https://github.com/threefoldtech/jumpscaleX/commit/6bab3e4432ad988adce8fcd2bf4dcb18c53c3a78
- https://github.com/threefoldtech/jumpscaleX/commit/9f2cd480e63a6d59d72e14c3eb5ce70dd2201b7e
- https://github.com/threefoldtech/jumpscaleX/commit/95f9a6b61b12fbf863dcbd74054671d3c9a2f139

**Comment by ranatrk** [comment]
Builder : https://github.com/threefoldtech/jumpscaleX/issues/299

**Comment by AhmedHanafy725** [comment]
#### Client:
> zdb client config implementations: zdb client now has get, save, delete, and data_update
> 
> * [6bab3e4](https://github.com/threefoldtech/jumpscaleX/commit/6bab3e4432ad988adce8fcd2bf4dcb18c53c3a78)
> * [9f2cd48](https://github.com/threefoldtech/jumpscaleX/commit/9f2cd480e63a6d59d72e14c3eb5ce70dd2201b7e)
> * [95f9a6b](https://github.com/threefoldtech/jumpscaleX/commit/95f9a6b61b12fbf863dcbd74054671d3c9a2f139)

**I see that these changes has been removed.**
So it is not follow the [template](https://github.com/threefoldtech/jumpscale10/tree/master/Jumpscale/clients/TEMPLATE).

But the test `j.clients.zdb.test()` is working well.
**Note**: After the test has been finished, the server is still running. (I think **it should be stopped**)
zdb client has start_test_instance but it doesn't have stop.

**Comment by rkhamis** [comment]
Indeed, the zdb client will not have the configmanager setup because we then have a chicken/egg problem where we need the zdb client to store the config.

Instead, the zdb will be without config.

To finish this task, zdb test should be complete (tests that connection works, creating a namespace works, adding, retrieving and deleting - where applicable-) on all modes work

zdb client should indeed stop the server it starts at the end of the test

**Comment by ranatrk** [comment]
**Basic test:**
(With zdb running on port=9901) 
- Admin client instance can be created
![Screenshot from 2019-04-24 15-47-52](https://user-images.githubusercontent.com/17128393/56664520-88f7f080-66a8-11e9-84d9-020b50b884c8.png)
- Using the admin client, a new namespace is created and retrieved, with a new non admin zdb client returned
![Screenshot from 2019-04-24 15-50-53](https://user-images.githubusercontent.com/17128393/56664696-d96f4e00-66a8-11e9-9aa8-fe0dd6a2b3f3.png)
- Using non admin client: setting, getting, updating, and deleting
![Screenshot from 2019-04-24 15-53-28](https://user-images.githubusercontent.com/17128393/56664936-5e5a6780-66a9-11e9-9058-d7a33aff6146.png)

**Add server stop in test:**
- Added stop_test_instance function, where it is called at the end of the test https://github.com/threefoldtech/jumpscaleX/commit/50d3fe3175807b6551803a3ead8d6e6f39493b8f

**Comment by AhmedHanafy725** [comment]
### 1- Admin client
**Get client and list namespaces**
```
JSX> cl = j.clients.zdb.client_admin_get(port=9901)
JSX> cl.namespaces_list()                                                                            
['default']
```
**Create namespace and list**
```
JSX> ns = cl.namespace_new('test')
JSX> cl.namespaces_list()                                                                            
['default', 'test']
```
**Set, get and delete data**
```
JSX> ns.set('test1')                                                                                 
0

JSX> ns.set('test2')                                                                                 
1

JSX> ns.get(0)                                                                                       
b'test1'

JSX> ns.get(1)                                                                                       
b'test2'

JSX> ns.get(2)                                                                                       
JSX>

JSX> ns.delete(0)                                                                                    
JSX> ns.get(0)                                                                                       
JSX> ns.get(1)                                                                                       
b'test2'
```
**Delete namespace and list**
```
JSX> cl.namespace_delete('test')
JSX> cl.namespaces_list()                                                                            
['default']
```
### 2- Non admin client 
**Get client**
```
cl = j.clients.zdb.client_get(port=9901, secret='')
```
**Set, get and delete data**
```
JSX> cl.set('test3')                                                                                 
0

JSX> cl.set('test4')                                                                                 
1

JSX> cl.get(0)                                                                                       
b'test3'

JSX> cl.get(1)                                                                                       
b'test4'

JSX> cl.get(2)                                                                                       
JSX> cl.delete(0)                                                                                    
JSX> cl.get(0)                                                                                       
JSX> cl.get(1)                                                                                       
b'test4'
```
`j.clients.zdb.test()` works fine and server is stopped at the end of test.

### verified
