### ISSUE TITLE
redis test in BCDB fails for ZDB

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#481]
/sandbox/lib/jumpscale/Jumpscale/data/bcdb/tests/7_redis.py

```
# zdb_test()
```

need to uncomment & fix

**Comment by BolaNasr** [comment]
Fix in zdb connection with redis , but still have problem ( any set start with id 7 not 2 ) in zdb 
i will fix it tomorrow

**Comment by BolaNasr** [comment]
NOW it works fine 
```
kosmos "j.data.bcdb.test()"
```
