### ISSUE TITLE
autocomplete issue in kosmos [development-bcdb]

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#482]
```python
j.clients.ssh.test.[TAB] 
```

should show properties of the sshclient

```python
j.clients.sshkey.s
```
also issue here

in branch: development-bcdb

**Comment by abom** [comment]
`j.clients.ssh.test` is a method, not an instance, choose another name e.g. `j.clients.ssh.mine`.

The second does not has any problems too.
