### ISSUE TITLE
define builders we need to work on now and attach to project

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#487]
old list see https://github.com/threefoldtech/jumpscaleX/issues/316

we need to create separate FR on JSX and link to this project with right prio's

**Comment by andrewayoub** [comment]
I have reviewed all the builders and created issues with what needs to be done for each one, but I need to talk to @despiegk or any other stakeholder if exist to set the priorities

**Comment by andrewayoub** [comment]
Done here https://github.com/orgs/threefoldtech/projects/29
