### ISSUE TITLE
syncthing builder,client

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#49]
- implement j.client
    - [learn how to do it in template for client](https://github.com/threefoldtech/jumpscale10/tree/master/Jumpscale/clients/TEMPLATE)   
- implement j.builder....
    - [learn how to do it in template](https://github.com/threefoldtech/jumpscale10/tree/master/Jumpscale/builders/TEMPLATE)

**Comment by ranatrk** [comment]
Client config implemented:
https://github.com/threefoldtech/jumpscaleX/commit/e7f21e1f8dd59f882e617a14441e67c61c13432f

**Comment by rkhamis** [comment]
builder done as well
