### ISSUE TITLE
Builder for gitea [development_gitea]

### ISSUE THREAD

**Issue by rkhamis** [threefoldtecharchive/jumpscaleX_archived#492]

**Comment by andrewayoub** [comment]
why should this be in a separate branch, shouldn't it be in development_builders ?

**Comment by abom** [comment]
Updated some references to older methods such as `j.sal.process.execute`...etc.

**Comment by abom** [comment]
Build fails, postgres compilation has errors, posgres builder need to be updated.

https://github.com/threefoldtech/jumpscaleX/issues/20 is related (the builder part).

@rkhamis  As this task is set to be [next](https://github.com/threefoldtech/jumpscaleX/milestone/6), should i pick another one form [now](https://github.com/threefoldtech/jumpscaleX/milestone/5)?

**Comment by abom** [comment]
Branch: development_builder (#511).

Build is working now, install too, but the binary gave me some errors regarding paths when starting it from another place than the build directory.

Build directory: $GOPATH//src/code.gitea.io/gitea

When starting the soft-linked binary from `/sandbox/bin`, but just doing:

`gitea web`

It gives this error:

```
2019/05/22 14:40:52 [W] Custom config '/sandbox/go_proj/bin/custom/conf/app.ini' not found, ignore this if you're running first time
2019/05/22 14:40:52 [T] AppPath: /sandbox/go_proj/bin/gitea
2019/05/22 14:40:52 [T] AppWorkPath: /sandbox/go_proj/bin
2019/05/22 14:40:52 [T] Custom path: /sandbox/go_proj/bin/custom
2019/05/22 14:40:52 [T] Log path: /sandbox/go_proj/bin/log
panic: fail to set message file(en-US): open conf/locale/locale_en-US.ini: no such file or directory

goroutine 1 [running]:
code.gitea.io/gitea/vendor/github.com/go-macaron/i18n.initLocales(0xc00014c7d5, 0x0, 0x11dad53, 0xb, 0xc000121080, 0x11e65e2, 0x12, 0xc00019a420, 0x15, 0x15, ...)
        /sandbox/go_proj/src/code.gitea.io/gitea/vendor/github.com/go-macaron/i18n/i18n.go:57 +0x6de
code.gitea.io/gitea/vendor/github.com/go-macaron/i18n.I18n(0xc000122300, 0x1, 0x1, 0x0, 0x0)
        /sandbox/go_proj/src/code.gitea.io/gitea/vendor/github.com/go-macaron/i18n/i18n.go:158 +0xed
code.gitea.io/gitea/routers/routes.NewMacaron(0xc0000f4640)
        /sandbox/go_proj/src/code.gitea.io/gitea/routers/routes/routes.go:93 +0x8c9
code.gitea.io/gitea/cmd.runWeb(0xc0000f4640, 0x0, 0x0)
        /sandbox/go_proj/src/code.gitea.io/gitea/cmd/web.go:65 +0xae
code.gitea.io/gitea/vendor/github.com/urfave/cli.HandleAction(0x105ef20, 0x12246a8, 0xc0000f4640, 0xc000134a00, 0x0)
        /sandbox/go_proj/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/app.go:471 +0xad
code.gitea.io/gitea/vendor/github.com/urfave/cli.Command.Run(0x11cebc9, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x11ecabe, 0x16, 0x0, ...)
        /sandbox/go_proj/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/command.go:191 +0x928
code.gitea.io/gitea/vendor/github.com/urfave/cli.(*App).Run(0xc0000b2820, 0xc00000e080, 0x2, 0x2, 0x0, 0x0)
        /sandbox/go_proj/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/app.go:241 +0x658
main.main()
        /sandbox/go_proj/src/code.gitea.io/gitea/main.go:48 +0x32f
```

**Comment by abom** [comment]
The binary produced at the build directory (`$GOPATH/src/code.gitea.io/gitea`) contains the assets bundled with it using bindata, while the binary at `$GOPATH/bin` does not.

Copying the binary at the build directory to `$GOPATH/bin` solved the [issue mentioned above](https://github.com/threefoldtech/jumpscaleX/issues/492#issuecomment-494842299), now starting `gitea` can be done from anywhere using `gitea web`.


To configure gitea with iyo authentication:

```
j.builder.apps.gitea.install()
j.builder.apps.gitea.configure('iyo_client_id', 'iyo_client_secret')  
```

**Comment by abom** [comment]
Tried to create an flist and start it, but seems like some libraries are missing, maybe something is still wrong with `j.sandboxer.libs_sandbox()` or something.


Flist: https://hub.grid.tf/abdelrahman/psql.flist.md

```python
from 
from zeroos.core0.client import Client

cl = Client('node_ip_goes_here')
cont_cl = cl.container.client(container_id_goes_here)
cont_cl.system('/sandbox/bin/pg_ctl start -D /sandbox/apps/psql/data',env={'LD_LIBRARY_PATH':'/sandbox/lib:/lib'}).get()
```

[Output:

STATE: 0 ERROR
STDOUT:

STDERR:

DATA:
fork/exec /sandbox/bin/pg_ctl: no such file or directory
](url)

**Comment by abom** [comment]
Will test the flist when the zos container of postgres is working as it has some problems, see https://github.com/threefoldtech/jumpscaleX/issues/527#issuecomment-497368647.

**Comment by abom** [comment]
Was testing this flist https://hub.grid.tf/abdelrahman/gitea1.1-psql9.6-ubuntu18.04.flist.md

But we fogot about git itself!

```python
In [99]: cont_cl.bash('/sandbox/bin/gitea web').get()                                                                                                 
Out[99]: 
STATE: 1002 ERROR
STDOUT:

STDERR:
panic: Git version missing: exec: "git": executable file not found in $PATH

goroutine 1 [running]:
code.gitea.io/gitea/vendor/code.gitea.io/git.init.0()
        /sandbox/go_proj/src/code.gitea.io/gitea/vendor/code.gitea.io/git/git.go:76 +0x1a3

DATA:

```

@andrewayoub Do we have a `git` builder?

**Comment by abom** [comment]
Will merge with jumpscalex flist instead of ubuntu.

**Comment by abom** [comment]
Now we have a [working flist](https://hub.grid.tf/abdelrahman/gitea1.1-psql9.6-jumpscalex-development.flist.md) (merged with psql and jumpscalex).

I added init scripts and `startup.toml` (`development_builder` branch), the init scripts and gitea need to run in [a specific order](https://github.com/threefoldtech/jumpscaleX/blob/68a545b556acb201cbecfed30a0f55d4e9b3afdd/Jumpscale/builder/apps/templates/gitea_startup.toml) with postgres, also to configure the custom login method (IYO).

**Comment by Dina-Abd-Elrahman** [comment]
#### Branch: Development_builder, Commit: 074ed0dd74efc3affaa347004e2d924f5f3271cd

#### Verification steps:
- j.builders.apps.gitea.build(reset=True)
- j.builders.apps.gitea.install(reset=True)
- j.builders.apps.gitea.configure("org_client_id", "org_client_secret")
- j.builders.apps.gitea.start()
- j.builders.apps.gitea.stop()
- j.builders.apps.gitea.sandbox(zhub_client=zhub_client, flist_create=True, reset=True) 
` Note: gitea flist must be merged with psql & jumpscaleX-development flists`
