### ISSUE TITLE
Builder for ARDB

### ISSUE THREAD

**Issue by rkhamis** [threefoldtecharchive/jumpscaleX_archived#493]

**Comment by waleedhammam** [comment]
- Implemented Build, Install, Start, Stop methods
- On implementing sandbox and test methods

**Comment by waleedhammam** [comment]
Refactored at: https://github.com/threefoldtech/jumpscaleX/commit/b48bd916e19dfdad5a7fa9911256c1b47d54dbbb on  development_builder #511

**Comment by AhmedHanafy725** [comment]
I can see that (build, install, start, stop and test) works fine but sandbox after creating the flist, deploying a container with it and trying to use the binary, there was a missing libs.
```
./ardb-server: error while loading shared libraries: libaio.so.1: cannot open shared object file: No such file or directory
```

**Comment by waleedhammam** [comment]
should be fixed at: https://github.com/threefoldtech/jumpscaleX/commit/16653d7ad18ecf40bc1ae5cb4367aedc17b09b0d

**Comment by AhmedHanafy725** [comment]
**branch:** development_builder
**commit:** d9384cdc8c92cdce3ebecc2ed042df5ec29dddbd
It works fine now
**Verified**
