### ISSUE TITLE
Builder for Brotli

### ISSUE THREAD

**Issue by rkhamis** [threefoldtecharchive/jumpscaleX_archived#497]

**Comment by waleedhammam** [comment]
Implemented build method, will continue after fixing the installer

**Comment by waleedhammam** [comment]
Refactored at: https://github.com/threefoldtech/jumpscaleX/pull/511

**Comment by AhmedHanafy725** [comment]
**branch:** development_builder **commit:** 22eb5a5caa2482f8a6150003fd4cd56d39daf5f8 
It works fine
