### ISSUE TITLE
Builder for s3 [development_s3]

### ISSUE THREAD

**Issue by rkhamis** [threefoldtecharchive/jumpscaleX_archived#499]

**Comment by despiegk** [comment]
is this for minio & everything related?

**Comment by rkhamis** [comment]
Just for ScalityS3, Minio should be a separate builder in my opinion

**Comment by serboctor** [comment]
blocked on #545

**Comment by serboctor** [comment]
The build and install are working fine but the start is failing, I am still trying to figure out why.

**Comment by serboctor** [comment]
Everything is working except for sandbox. It depends on python sandbox which doesn't seem to be working fine. I'll park the sandbox for now since we don't really have a use case for this builder so far.

**Comment by Dinaamagdy** [comment]
test s3 main methods 
- build (works)
- install (works)
- start(works)
- stop (doesn't work)
when I tried stop ```j.builder.storage.s3scality.stop()``` it didn't stop the server as shown 
   
![image](https://user-images.githubusercontent.com/24386802/58803250-3b5b9580-860f-11e9-9c7d-2ca121a0e2ce.png)

**Comment by Dinaamagdy** [comment]
> now stop working well but when I ried to start again, I get the following error 
![image](https://user-images.githubusercontent.com/24386802/58870972-774f3300-86c1-11e9-9e12-4d21b4531172.png)

**Comment by Dina-Abd-Elrahman** [comment]
- I got this error while trying to start the s3 

##### Note:

the test is done on fresh installed container

![error](https://user-images.githubusercontent.com/21218053/58891258-78498a00-86ec-11e9-9df9-88cb0aba6b13.png)

**Comment by Dina-Abd-Elrahman** [comment]
and when i stop and start again i got this error 

![error](https://user-images.githubusercontent.com/21218053/58891400-b9da3500-86ec-11e9-8540-95d802ad819b.png)
![ff](https://user-images.githubusercontent.com/21218053/58891491-e5f5b600-86ec-11e9-87fb-3cc545c3f6ef.png)

**Comment by serboctor** [comment]
I fixed the start after the stop. However, there are still errors in the logs when we start but everything keeps running. I checked with Reem, and this is not a very high priority. @Dina-Abd-Elrahman can you verify this status.

**Comment by Dinaamagdy** [comment]
start after stop works now on development_builder branch
