### ISSUE TITLE
zerohub client

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#50]
## make sure client is properly implemented 

- implement j.client using our new config mgmt
    - [learn how to do it in template for client](https://github.com/threefoldtech/jumpscale10/tree/master/Jumpscale/clients/TEMPLATE)   

- add test

**Comment by serboctor** [comment]
@rkhamis  isn't this the same as #6?

**Comment by serboctor** [comment]
It seems to be using the right classes already. I went over most of the client's functions, and they are working fine.
I added a test.

**Comment by Dina-Abd-Elrahman** [comment]
### Verification steps:

- cl = j.clients.zhub.get("test") 
- cl.username = "abdelrad"
- cl.token = "$MY_TOKEN"

- cl.authenticate()
- cl.save()

-  cl.upload('/tmp/my-upload-file.tar.gz') 
- cl.list('abdelrad')
- cl.rename('my-upload-file.flist', 'my-super-flist.flist')

- cl.repositories()
- cl.delete_flist('my-super-flist.flist') , i got an error while trying to delete flist 
![error](https://user-images.githubusercontent.com/21218053/59275395-881d1d00-8c5c-11e9-9a50-7bc691a5cebc.png)

**Comment by Dina-Abd-Elrahman** [comment]
- cl.delete_flist('my-super-flist.flist') works fine now , without changing anything. 
- cl.promote('abdelrahman', 'psql.flist', 'abdelrad')
- cl.merge("test_merge", ["abdelrad/abdelrad.flist", "abdelrad/influxd.flist"])
