### ISSUE TITLE
Builder for Docker

### ISSUE THREAD

**Issue by serboctor** [threefoldtecharchive/jumpscaleX_archived#501]

**Comment by serboctor** [comment]
Docker builder is now on `development_builder` branch.

**Comment by Dina-Abd-Elrahman** [comment]
commit : 9ff6e2d530f34b9a52aae65be026b7f3e8d3e8cb

### Verification steps:

-  j.builder.virtualization.docker.build()
- j.builder.virtualization.docker.install() 
- j.builder.virtualization.docker.start()
, but i cannot start docker using start method 

![error](https://user-images.githubusercontent.com/21218053/58484027-9863d100-8161-11e9-8993-bb3469fc4a78.png)

**Comment by serboctor** [comment]
@Dina-Abd-Elrahman I get this if the docker daemon is already running. Please make sure it is not running before testing and try again.

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
