### ISSUE TITLE
digitalme builder has an issue 

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtecharchive/jumpscaleX_archived#503]
cannot build digitalme builder

` j.builder.apps.digitalme.build(reset=True)`

commit id : aaaedd6d11dd37f68732236b3502590b74ea35a2

![error](https://user-images.githubusercontent.com/21218053/58007325-534cf880-7aea-11e9-8294-013a76f85b18.png)

**Comment by waleedhammam** [comment]
depends on: https://github.com/threefoldtech/jumpscaleX/issues/502

**Comment by Dina-Abd-Elrahman** [comment]
commit: 6e332c4 , branch: development_builder

### verification steps :

- j.builder.apps.digitalme.build(reset=True)

the previous error is based, but we faced another error with `Lua Builder` 

![error](https://user-images.githubusercontent.com/21218053/58086672-5f56ba00-7bbf-11e9-94a4-449827f09766.png)

**Comment by Dina-Abd-Elrahman** [comment]
- it was timeout issue when i tried again it worked correctly.
