### ISSUE TITLE
cannot install freeflow builder

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtecharchive/jumpscaleX_archived#504]
` j.builder.apps.freeflow.install(reset=True) `

commit id : aaaedd6d11dd37f68732236b3502590b74ea35a2

![error](https://user-images.githubusercontent.com/21218053/58008796-6f9e6480-7aed-11e9-8ae4-1513bff5ecab.png)

**Comment by Pishoy** [comment]
above is issue as u are running another app on the same port of apache2 which is 80, please stop it before start freeflow builder 
last commit of ffp builder is https://github.com/threefoldtech/jumpscaleX/commit/e83db91c6f8b01cd564752ab0432dca75727d249

**Comment by Dina-Abd-Elrahman** [comment]
- commit : 5e8826a414cb56e453270e8811c0ddbfec2c4b93 .

- it's working now, we can close this issue.
