### ISSUE TITLE
cannot start capnp builder 

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtecharchive/jumpscaleX_archived#506]
cannot start capnp builder. 

commit id : aaaedd6d11dd37f68732236b3502590b74ea35a2

`  j.builder.libs.capnp.build(reset=True)`
` j.builder.libs.capnp.install(reset=True) `
` j.builder.libs.capnp.start() `

![error](https://user-images.githubusercontent.com/21218053/58009144-184cc400-7aee-11e9-9ebe-bd3851d5603e.jpg)

**Comment by waleedhammam** [comment]
Fixed at: https://github.com/threefoldtech/jumpscaleX/pull/511

**Comment by Dina-Abd-Elrahman** [comment]
no start and stop methods again. ( not needed in capnp builder )
