### ISSUE TITLE
Builders : create sandbox

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtecharchive/jumpscaleX_archived#514]
create sandbox for the following  builders :
BuilderBitcoin
BuilderEthereum
BuilderRipple
BuilderMinio
BuilderRestic 
BuilderSyncthing
BuilderOpenResty

**Comment by rkhamis** [comment]
@Dinaamagdy , please update this card

**Comment by Dinaamagdy** [comment]
finished and can find code here 
8fe86d202d74fe4e38e614a1924ae4f6ae3ce89c
