### ISSUE TITLE
Builders: mariadb

### ISSUE THREAD

**Issue by andrewayoub** [threefoldtecharchive/jumpscaleX_archived#524]
- doesn't follow builders guidlines

**Comment by waleedhammam** [comment]
Implemented build, still on install

**Comment by waleedhammam** [comment]
Implemented Build, install, start, stop, sandbox, test
now testing flist on a container

**Comment by waleedhammam** [comment]
refactored at: https://github.com/threefoldtech/jumpscaleX/commit/517167918ca112a65c2596fe5db200940e6de699

**Comment by Dina-Abd-Elrahman** [comment]
- verified
