### ISSUE TITLE
Builders: builder php

### ISSUE THREAD

**Issue by andrewayoub** [threefoldtecharchive/jumpscaleX_archived#534]
- doesn't follow builders guidlines

**Comment by AhmedHanafy725** [comment]
Still working on building from source.

**Comment by AhmedHanafy725** [comment]
Was getting this error in build
```
configure: error: Package requirements (oniguruma) were not met:

No package 'oniguruma' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables ONIG_CFLAGS
and ONIG_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```
After installing this package and other system packages, build method is working fine.

**Comment by AhmedHanafy725** [comment]
Now `build`, `install`, `start` and `stop` is working fine and `sandbox` is added but not tested yet.

**Comment by AhmedHanafy725** [comment]
`sandbox` is tested and works fine.

**Comment by Dinaamagdy** [comment]
j.builders.runtimes.php.test() doesn't work with the following error 
![image](https://user-images.githubusercontent.com/24386802/59184434-66de0300-8b6e-11e9-97a1-c594ce013ac0.png)

**Comment by AhmedHanafy725** [comment]
Fix test to install `nginx` first and fix (`php` and `nginx`) config files

**Comment by Dinaamagdy** [comment]
works now, test, start, build ,install and sandbox flist
