### ISSUE TITLE
Builders: NodeJs Builder

### ISSUE THREAD

**Issue by andrewayoub** [threefoldtecharchive/jumpscaleX_archived#545]
- doesn't follow builders guidlines

**Comment by serboctor** [comment]
Reorganized the code to match the new structure and I am trying to make the install work.

**Comment by serboctor** [comment]
The build and install now work fine without any errors and I can run npm. However, I am getting a message that bower is deprecated, so I am looking at other alternatives to be used instead. I also upgraded the node version but yet to find out if it will work out well with scality.

**Comment by Dina-Abd-Elrahman** [comment]
-verified.
