### ISSUE TITLE
cannot build ripple builder 

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtecharchive/jumpscaleX_archived#547]
- cannot build ripple builder. 

` j.builder.blockchain.ripple.build(reset=True) ` 

![error_1](https://user-images.githubusercontent.com/21218053/58117767-9947b080-7bff-11e9-8a1b-292264f74e84.png)
![error_2](https://user-images.githubusercontent.com/21218053/58117797-b0869e00-7bff-11e9-8413-1f0e38eb110c.png)

**Comment by waleedhammam** [comment]
Fixed timeout and minor fixes at: https://github.com/threefoldtech/jumpscaleX/commit/539a3ed6ab34f9fb008ddb225567a5e6b1e608b3
on branch development_builder

**Comment by Dina-Abd-Elrahman** [comment]
verified
