### ISSUE TITLE
cannot create cmake sandbox

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtecharchive/jumpscaleX_archived#548]
cannot create cmake sandbox, 

`j.builder.libs.cmake.sandbox(reset=True, zhub_client=zhub_client, create_flist=True) `

![error](https://user-images.githubusercontent.com/21218053/58119175-aade8780-7c02-11e9-9286-a72b49d6ae1f.png)

**Comment by AhmedHanafy725** [comment]
```
iyo = j.clients.itsyouonline.get( "iyo_hub",baseurl="https://itsyou.online/api",application_id=<>,secret=<>)
token = iyo.jwt_get().jwt 
zhub_client = j.clients.zhub.get("hub_instance2",token_=token,username=<>)
zhub_client.authenticate()
j.builder.libs.cmake.sandbox(zhub_client=zhub_client ,flist_create=True, merge_base_flist='tf-autobuilder/threefoldtech-jumpscaleX-development.flist')
``` 
I did these steps and it works fine

**Comment by Dina-Abd-Elrahman** [comment]
i missed this steps 

```zhub_client.authenticate()```

i can create container now using merged cmake flist  
https://hub.grid.tf/abdelrad/cmake_merged_tf-autobuilder_threefoldtech-jumpscaleX-development.flist

and check if cmake exists or not
