### ISSUE TITLE
SAL disklayout

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#55]
- [read instructions](https://github.com/threefoldtech/jumpscale10/tree/master/Jumpscale/sal)

- dont use executor/prefab (port)

**Comment by Dina-Abd-Elrahman** [comment]
- j.sal.disklayout.findDisk
- j.sal.disklayout.getDisks

```
TypeError: __init__() takes 1 positional argument but 2 were given
```

**Comment by Dina-Abd-Elrahman** [comment]
## verification steps: 

-  j.sal.disklayout.getDisks()                                                                                                           
```
 [/dev/sda 240057409536]
```

-  j.sal.disklayout.findDisk(name='/dev/sda')                                                                                            
```
/dev/sda 240057409536
```
