### ISSUE TITLE
cannot start restic builder

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtecharchive/jumpscaleX_archived#550]
cannot start restic builder 

- j.builder.storage.restic.build(reset=True)
- j.builder.storage.restic.install(reset=True)
- j.builder.storage.restic.start()

![error](https://user-images.githubusercontent.com/21218053/58121893-b59c1b00-7c08-11e9-88b8-51eaa4316931.png)

**Comment by waleedhammam** [comment]
Restic is not a server so no need to start nor stop, fixed at: https://github.com/threefoldtech/jumpscaleX/commit/539a3ed6ab34f9fb008ddb225567a5e6b1e608b3
on development_builder

**Comment by Dina-Abd-Elrahman** [comment]
- verified
