### ISSUE TITLE
can't retrieve any clients after killing redis-server [development_installer]

### ISSUE THREAD

**Issue by 0xIslamTaha** [threefoldtecharchive/jumpscaleX_archived#551]
**Description**
I can't retrieve any clients after killing redis-server.

**Steps**
- access JSX container
```bash
source /sandbox/env.sh
eval `ssh-agent`
ssh-add
kosmos
```
- Create any client, like
```python
zos = j.clients.zos.get(name="random0", host="10.102.136.183")
zos.save()
zos.ping()
```
![image](https://user-images.githubusercontent.com/17981089/58158143-1f084200-7c7a-11e9-817b-b36c034f2e35.png)
- exit kosmos
- Restart the container or execute `pkill -9 redis` to kill the running redis server
- Start kosmos again and try to retrieve the client
```python
zos = j.clients.zos.get(name="random10")
zos.ping()
```
**Actual Result**
it hangs
![image](https://user-images.githubusercontent.com/17981089/58158276-65f63780-7c7a-11e9-8466-0b053b276f95.png)

**Hint**
- I can see that the latest scenario was working in this commit 9be6d79cd14cc7d240de479f4f75410cbb7b6675

 - When I checked /sandbox/var I found that it created the client files

**Comment by arahmanhamdy** [comment]
Relates to #559

**Comment by rkhamis** [comment]
see comment on #559

**Comment by despiegk** [comment]
will fix this today

**Comment by despiegk** [comment]
see #559
