### ISSUE TITLE
Builder base unit tests and documentation

### ISSUE THREAD

**Issue by andrewayoub** [threefoldtecharchive/jumpscaleX_archived#557]
Builder base class has the core functionality of the builders, it needs to be tested very well in order to make sure we have a reliable building tool.
this task requires:
- [x] Writing unit tests for builder base class and builder method decorator
- [x] Writing proper code documentation for builder base class and builder_method decorator
- [x] Review and finalize the builders guidelines, making sure it has enough examples and define the best practices and the limitations.

**Comment by andrewayoub** [comment]
unit tests covering the main functionalities of the builder_method decorator was added

**Comment by andrewayoub** [comment]
code documentation for builder base class and builder_method decorator was added

**Comment by Dinaamagdy** [comment]
- docs for builders
https://github.com/threefoldtech/jumpscaleX/blob/8217f1b18ccc148aeb81da98efd74c0a61c8ca88/docs/Internals/builders/Builders.md
- docs for builder base 
https://github.com/threefoldtech/jumpscaleX/blob/development_builder/Jumpscale/builder/system/BuilderBaseClass.py#L12
- unit tests for base class
https://github.com/threefoldtech/jumpscaleX/blob/development_builder/Jumpscale/builder/test/builder/test_builder_base_class.py
