### ISSUE TITLE
Kosmos docstrings are not working with builder_method decorated methods

### ISSUE THREAD

**Issue by abom** [threefoldtecharchive/jumpscaleX_archived#558]
Any `builder_method` decorated method will show the `wrapper_function` docstring instead of the original decorated method's.

For example, try

```
j.builder.runtimes.golang.install?
```

This will show

`wrapper_action(*args, **kwargs)`

**Comment by AhmedHanafy725** [comment]
**branch:** development_builder **commit:** 9aec0b76024d16b5e2f3d78b14ab4dc0b9e1f3e9

**Verified** 

![image](https://user-images.githubusercontent.com/41957921/58406347-ae8e6600-8069-11e9-8eea-3a3be2f56e22.png)
