### ISSUE TITLE
AttributeError: 'Types' object has no attribute 'duration'

### ISSUE THREAD

**Issue by zaibon** [threefoldtecharchive/jumpscaleX_archived#564]
This issue is related to https://github.com/threefoldtech/jumpscaleX/issues/563

One of the test from tfchain client raises `AttributeError: 'Types' object has no attribute 'duration'`

So it seems `j.data.types.duration` does not exists anymore. What should we use as a replacement ?

**Comment by serboctor** [comment]
@despiegk is there a reason why it was removed? I couldn't find any useful info in the history.
@zaibon the class was still there, so I re-added it to the types and fixed a couple of bugs. It is pushed on `development_jumpscale`.

**Comment by zaibon** [comment]
@serboctor ok good, thx.
When is `development_jumpscale` branch planned to be merged?

**Comment by zaibon** [comment]
branch as been merged. Test are passing now, Thx @serboctor
