### ISSUE TITLE
fix & test export/import feature of BCDB [development_installer]

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#567]
Description : 
it will allow to backup and restore of all your data (configuration and more)
for instance it will be a way to migrate between 3bots

**Comment by despiegk** [comment]
need to test for mysqlite client as well

**Comment by zgorizzo69** [comment]
migrate between 3bot 
3 bot backup and restore of all your data

**Comment by despiegk** [comment]
working
