### ISSUE TITLE
zerostor builder [development_zstor]

### ISSUE THREAD

**Issue by ranatrk** [threefoldtecharchive/jumpscaleX_archived#576]
Implement j.builder....

## remarks
- call j.builders.golang.install()
-  build the server & client
- implement some tests
- call the client

**Comment by ranatrk** [comment]
Finished `build`,` install`.
Currently working on `start/stop` using `startup_cmds()`

**Comment by ranatrk** [comment]
- Finished start,stop, clean, uninstall, and test
https://github.com/threefoldtech/jumpscaleX/commit/77f9b20792de97515e67c3a54ab18aec3f520764
on branch _development_zstor_
- Need to add dependecies(zdb , etcd in build and start)

**Comment by ranatrk** [comment]
Added dependencies (zdb, etcd) in install, startup_cmds, and sandbox
https://github.com/threefoldtech/jumpscaleX/commit/e7e6d031d6a6dc72c79ab5972d841eb67fa65ae6

**Comment by Dinaamagdy** [comment]
verifying that the following builders working  in development zstor branch
- build
- install
- stop 
- start
- sandbox and flist 
- startup
