### ISSUE TITLE
Ensure reservation flow using tfchain client is not broken

### ISSUE THREAD

**Issue by zaibon** [threefoldtecharchive/jumpscaleX_archived#579]
Quite some changes and new code has been added to JSX recently.
I want to redo a full reservation flow to ensure nothing has been broken along the way.

Blocking bugs:
- [x] https://github.com/threefoldtech/jumpscaleX/issues/563
- [x] https://github.com/threefoldtech/digitalmeX/issues/259

**Comment by zgorizzo69** [comment]
On branch development_installer I tried to do a reservation  zos on testnet and got this [error](https://gist.github.com/zgorizzo69/a25356aee3c78cebba5b269aa31db70d)
