### ISSUE TITLE
make a get started documentation that will describe how to use:

### ISSUE THREAD

**Issue by zgorizzo69** [threefoldtecharchive/jumpscaleX_archived#581]
* docker run of the 3bot image
* web UI to follow the steps of wallet gen,tcchain connection, faucet, 3bot registration through 3bot api
* deployment of a container (a small website that display your name ?)
* connection to the deployed container on tf grid

**Comment by zaibon** [comment]
fixed in https://github.com/threefoldtech/jumpscaleX/pull/586
