### ISSUE TITLE
basic installer instructions should be already found in README itself

### ISSUE THREAD

**Issue by GlenDC** [threefoldtecharchive/jumpscaleX_archived#583]
It's custom that in order to do a "standard" install (that is any kind of install of your software that is not a special case) can be just read directly from the README.

Currently the README links just to a document. If we can, we should avoid that and just give  the one (or multi) liner(s) that allow you to install it easy and (hopefully) fast.

**Comment by despiegk** [comment]
will be revisited in newer release
