### ISSUE TITLE
failed to install JSX using the development_installer branch on MacOS

### ISSUE THREAD

**Issue by GlenDC** [threefoldtecharchive/jumpscaleX_archived#584]
step 1.

```
curl https://raw.githubusercontent.com/threefoldtech/jumpscaleX/development_installer/install/jsx.py\?$RANDOM > /tmp/jsx
```

step 2.

```
chmod 777 /tmp/jsx
```

step 3.

```
/tmp/jsx container-install



EXCEPTION

        /tmp/jsx                                                     : 524 : IT.MyEnv.init()  # will take into consideration the --configdir

Wed 05 10:17:04 jsx              -   2 - <module>                           : EXCEPTION: type object 'MyEnv' has no attribute 'init'
CANNOT CONTINUE
```

**Comment by despiegk** [comment]
you probably have an old version of InstallTools in your /sandbox/code/github/threefoldtech/jumpscaleX

can you let me know what branch is there?

**Comment by despiegk** [comment]
retest please, i've put extra test to check the branch. If you start from a wrong branch it should warn you.

**Comment by GlenDC** [comment]
Correct it does warn me:

```
development
cannot install, the branch of jumpscale in /sandbox/code/github/threefoldtech/jumpscaleX needs to be development_installer
```

Even better though would be that it can also automatically propose and handle it for me. Either we only allow one JSX installation per host system (not sure that is recommended) in which case it might just clean up the entire sandbox area.

**Comment by GlenDC** [comment]
Cleaning up my sandbox environment and all jsx-related repos fixes this issue and now it can install.
