### ISSUE TITLE
install script delete ~/.ssh/known_hosts file

### ISSUE THREAD

**Issue by zaibon** [threefoldtecharchive/jumpscaleX_archived#588]
Seen in InstallTools.py
https://github.com/threefoldtech/jumpscaleX/blob/f814ddd03319139252b823f3a966886d630e521f/install/InstallTools.py#L3063

In no case a script should ever touch to this file on the host system of the use. I don't see any case where you would have to empty this file for any reason.

**Comment by GlenDC** [comment]
AAAAh o.O My file is empty indeed now :'(

**Comment by despiegk** [comment]
this is not critical, I understand you might not like it but its not hurting anyone

**Comment by zaibon** [comment]
That's very much not true. This file contains public key of server the user trusts. Deleting it means the user is now completely blind and has no way to know if the server he usually access has not been compromised. This is is big security hold you are just creating on everyone computer.

Also, there nothing that requires to do that in the first place, so why do it at all ?

**Comment by despiegk** [comment]
problem is no longer there has been resolved
