### ISSUE TITLE
/tmp/jsx container-install asks for private key and than for ssh password for root@localhost

### ISSUE THREAD

**Issue by GlenDC** [threefoldtecharchive/jumpscaleX_archived#589]
The installer confuses me:

- First it asks me for a private key, I gave and confirm one;
- It continues, and later asks to add localhost:9122 to known hosts, I obey;
- Now it asks me the password for ssh'ing into `root@localhost`, I do not know the password, I try the empty password, as well as my private key that I gave at the beginning, but nothing works.

The installation stops:

```
Could not execute:    scp -P 9122 /tmp/jsx root@localhost:/tmp/
stderr:
    Warning: Permanently added '[localhost]:9122' (ECDSA) to the list of known hosts.
    Permission denied, please try again.
    Permission denied, please try again.
    root@localhost: Permission denied (publickey,password).
    lost connection
```

**Comment by GlenDC** [comment]
Tried again with a clean environment. Seems that it does work when I make sure an SSH key is loaded in and active. The loading of an ssh key (and perhaps even creation of it) should either be automated, or it should be checked at the start of the installer as a prerequisite so that it can abort the installer with a proper error if no ssh key is loaded in. Given that it seems to prevent the installation from happening otherwise.

**Comment by despiegk** [comment]
lets verify if still issue in 10.0.2

**Comment by despiegk** [comment]
do on #682

**Comment by waleedhammam** [comment]
fixed on development_jumpscale

**Comment by Dina-Abd-Elrahman** [comment]
- the installation is done successfully using `container-install` option when the key is loaded, but when i delete the key ` ssh-add -D` 
the script downloaded the docker then raise this error 

`Warning: Permanently added '[localhost]:9122' (ECDSA) to the list of known hosts.
root@localhost's password: `

- so we need to check the existence of ssh-key before to start in any installation step. @waleedhammam

**Comment by waleedhammam** [comment]
@ branch: **development_jumpscale** @ commit: **https://github.com/threefoldtech/jumpscaleX/commit/0f8315db548a67ce3b5c6aa35438a49d6a750f93**

**changelog:**
- raise error when ssh-key is not avaliable
- fix the dirty hack that removes host's known hosts and replaced with adding to it

**Comment by Dina-Abd-Elrahman** [comment]
- verified and it's working as expected.
