### ISSUE TITLE
post installation instructions unclear

### ISSUE THREAD

**Issue by GlenDC** [threefoldtecharchive/jumpscaleX_archived#590]
At the end of the installation it tells me right before exiting:

```
install succesfull:
# if you use a container do:
jsx container_kosmos
or
kosmos
```

Yet none of these commands work.

If I look at the installation instructions on GitHub it tells me something different:

```
$ /tmp/jsx container-kosmos
DOWNLOADED INSTALLTOOLS TO /tmp/InstallTools.py
OK
Sat 08 13:26:36 BCDB.py          - 204 - bcdb:bcdb                          : BCDB INIT DONE:system
JSX>
```

That does work as you can see from the output. Does that mean we always need to start kosmos from the `/tmp/jsx container-kosmos` script, or what should we do? If we do need to always start it like this than perhaps the post-installation explanation should be updated.

**Comment by despiegk** [comment]
update doc in the installer

**Comment by BolaNasr** [comment]
update doc in development_installer branch

**Comment by Dinaamagdy** [comment]
verified on development installer branch
