### ISSUE TITLE
create sonic builder and server [development_sonic]

### ISSUE THREAD

**Issue by andrewayoub** [threefoldtecharchive/jumpscaleX_archived#592]
- [x] create builder for sonic
- [x] create jumpscale server for starting and configuring sonic server

**Comment by Dinaamagdy** [comment]
verified by 
- test sonic in wikis and make sure it works successful by follow steps here 
https://github.com/threefoldtech/digitalmeX/tree/development/docs/publishing_platform
- test that sonic builder works by j.builders.appa.sonic.build/install()
