### ISSUE TITLE
[automation_testing] automate testcases for capacity_reservation

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtecharchive/jumpscaleX_archived#593]
# develop testsuit for capacity  reservation on the Threefold Grid
### Framework  which include:
- js installtion 
- utils 
- testcases

**Comment by Dinaamagdy** [comment]
## testcases :
### wallet creation
####  scenario1 
- Create  tfchain client  with "Test" network type , should succeed 
- Create  tfchain  client with wrong network type , should fail .

#### Scenario 2
- Create wallet with name [N1],should succeed.
- Get the wallet with give it name[N1], should return same wallet with same seed[S1]. 
- Get the wallet by seed[S1], should return same wallet with same name 
- Use get method without pass name or seed, should create new one with main name

**Comment by zaibon** [comment]
Before redoing something they already exists. Please check the [already existing testsuite](https://github.com/threefoldtech/jumpscaleX/tree/master/Jumpscale/clients/blockchain/tfchain/tests) there is for the tfchain client.
Most of the features already have tests. So before going any further on this issue, validate what you want to implements as tests doesn't already exists.

Also, everything you have written about the test case you want I create have nothing to do with capacity reservations. This is only basic tfchain client features...

**Comment by 0xIslamTaha** [comment]
https://github.com/threefoldtech/jumpscaleX/tree/master/Jumpscale/clients/blockchain/tfchain/tests
