### ISSUE TITLE
verify jsx new installation

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtecharchive/jumpscaleX_archived#598]
verifying the jumpscale installation according to the following docs 
https://github.com/threefoldtech/jumpscaleX/tree/development/docs/Installation

**Comment by Dinaamagdy** [comment]
asking for password for local host 
https://github.com/threefoldtech/jumpscaleX/issues/589
 missing click module
https://github.com/threefoldtech/jumpscaleX/issues/600
not clear post instruction 
https://github.com/threefoldtech/jumpscaleX/issues/590
install jsx local raise configuration error:
https://github.com/threefoldtech/jumpscaleX/issues/602

**Comment by Dinaamagdy** [comment]
https://github.com/threefoldtech/jumpscaleX/issues/590 
https://github.com/threefoldtech/jumpscaleX/issues/600 
verified and solved but the other still exist

**Comment by mdeecode** [comment]
@Dinaamagdy could you have a look a PR #631 ? 
Issues #589 and #600 are solved if the installation prerequisites are followed correctly as described in the doc [here](https://github.com/threefoldtech/jumpscaleX/blob/development_installer_doc_reorg/docs/Installation/install_prerequisites.md)

**Comment by despiegk** [comment]
lets just restart installer and create new bugs if relevant
above referred things seem to be ok
