### ISSUE TITLE
missing click module in jumpscalx installer 

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtecharchive/jumpscaleX_archived#600]
## Steps 
run `/tmp/jsx container-install `as mention here https://github.com/threefoldtech/jumpscaleX/tree/development/docs/Installation

## issue
```
root@dina-Inspiron-3576:/home/dina# /tmp/jsx container-install
Traceback (most recent call last):
  File "/tmp/jsx", line 5, in <module>
    import click
ModuleNotFoundError: No module named 'click'
```

**Comment by zgorizzo69** [comment]
please check the [get started documentation](https://github.com/threefoldtech/jumpscaleX/blob/development/docs/Installation/get_started.md)  for all the dependencies 
also note that we want to use [pyinstaller](https://github.com/threefoldtech/jumpscaleX/blob/development/install/build_installer.sh ) to have a binary and so to get ride of the dependencies

**Comment by BolaNasr** [comment]
@Dinaamagdy 
we just need install click ```pip3 install click```

**Comment by BolaNasr** [comment]
@zgorizzo69  
we need to link  [Get_started](https://github.com/threefoldtech/jumpscaleX/blob/development/docs/Installation/get_started.md) to [README](https://github.com/threefoldtech/jumpscaleX/blob/development/docs/Installation/README.md)

**Comment by Dinaamagdy** [comment]
verified that it exist in get started  docs
