### ISSUE TITLE
install jumpscalex  local raise error 

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtecharchive/jumpscaleX_archived#602]
## Steps
- curl https://raw.githubusercontent.com/threefoldtech/jumpscaleX/development/install/jsx.py?$RANDOM > /tmp/jsx
- python3 /tmp/jsx install 
as the steps here
https://github.com/threefoldtech/jumpscaleX/tree/development/docs/Installation
## Issue 
raise the  following error
```
DOWNLOADED INSTALLTOOLS TO /tmp/InstallTools.py


EXCEPTION

        /tmp/jsx                                                     : 552 : cli()
        /usr/local/lib/python3.6/dist-packages/click/core.py         : 764 : return self.main(*args, **kwargs)
        /usr/local/lib/python3.6/dist-packages/click/core.py         : 717 : rv = self.invoke(ctx)
        /usr/local/lib/python3.6/dist-packages/click/core.py         : 1137: return _process_result(sub_ctx.command.invoke(sub_ctx))
        /usr/local/lib/python3.6/dist-packages/click/core.py         : 956 : return ctx.invoke(self.callback, **ctx.params)
        /usr/local/lib/python3.6/dist-packages/click/core.py         : 555 : return callback(*args, **kwargs)
        /tmp/jsx                                                     : 271 : _configure(configdir=configdir, basedir="/sandbox", no_sshagent=no_sshagent)
        /tmp/jsx                                                     : 146 : configdir=configdir,
        /tmp/InstallTools.py                                         : 1992: st = os.stat(MyEnv.config["DIR_HOME"])

type object 'MyEnv' has no attribute 'config'
CANNOT CONTINUE
```

**Comment by BolaNasr** [comment]
i think we need execute this line ```/tmp/jsx configure``` before execute install 
@zgorizzo69  can please add this in docs of installation

**Comment by zgorizzo69** [comment]
on the documentation the command is python3 /tmp/jsx __container__-install
have you tried on development_installer branch ?
@BolaNasr normally you don't have to go through /tmp/jsx configure 
if you don't it will give you the standard configuration

**Comment by BolaNasr** [comment]
@zgorizzo69  i tried it in **development** branch but we need install it in local machine not in container so we use this command ```/tmp/jsx install``` and give us error **type object 'MyEnv' has no attribute 'config'** if didn't write this line ```/tmp/jsx configure ```before install

**Comment by zgorizzo69** [comment]
ok then try on the development_installer branch(as it is the one that is the most up to date for the installer script) if it is not working on that branch then we can assign this issue to kristof.
If it is working on development_installer then it should work when we merge/rebase into development.. right @rkhamis ?

**Comment by Dinaamagdy** [comment]
get same error on development_installer branch

**Comment by rkhamis** [comment]
@zgorizzo69 it indeed doesn't work on either branch, but already in progress

**Comment by waleedhammam** [comment]
fix with https://github.com/threefoldtech/jumpscaleX/pull/650
steps I made and works with following https://github.com/threefoldtech/jumpscaleX/tree/development/docs/Installation and https://github.com/threefoldtech/jumpscaleX/blob/development/docs/Installation/install_prerequisites.md on development branch :
```
# preparing a container
> docker run -itd --name=test_installer -p 2222:22 -p 8080:80 ubuntu:18.04
> docker attach jumpscalex
> apt update
> apt install sudo openssh-server locales curl vim git rsync unzip lsb python3-pip -y
> pip3 install click
> locale-gen "en_US.UTF-8"
> eval `ssh-agent`
> ssh-keygen
> ssh-add
> ssh-add -l
# installing jumpscale
> curl https://raw.githubusercontent.com/threefoldtech/jumpscaleX/development/install/jsx.py?$RANDOM > /tmp/jsx 
> chmod +x /tmp/jsx;
> /tmp/jsx install
```

**Comment by abom** [comment]
I've a similar issue, but when starting kosmos (branch `development_bcdb`).

```
3BOTDEVEL:3bot:jumpscaleX: kosmos
MYENV INIT


EXCEPTION

        /sandbox/bin/kosmos                                          : 5   : from Jumpscale import j
        /sandbox/lib/jumpscale/Jumpscale/__init__.py                 : 217 : j.dirs = Dirs(j)
        /sandbox/lib/jumpscale/Jumpscale/core/Dirs.py                : 12  : self.BASEDIR = self._j.core.myenv.config["DIR_BASE"]

Error in sys.excepthook:
Traceback (most recent call last):
  File "/sandbox/lib/jumpscale/Jumpscale/__init__.py", line 64, in my_excepthook
    Tools.log(msg=exception_obj, tb=tb, level=40)
  File "/sandbox/lib/jumpscale/Jumpscale/core/InstallTools.py", line 634, in log
    Tools.log2stdout(logdict, data_show=data_show)
  File "/sandbox/lib/jumpscale/Jumpscale/core/InstallTools.py", line 1081, in log2stdout
    msg = Tools.text_replace(LOGFORMAT, args=logdict, ignore_error=True)
  File "/sandbox/lib/jumpscale/Jumpscale/core/InstallTools.py", line 994, in text_replace
    for key, val in MyEnv.config.items():
AttributeError: type object 'MyEnv' has no attribute 'config'

Original exception was:
Traceback (most recent call last):
  File "/sandbox/bin/kosmos", line 5, in <module>
    from Jumpscale import j
  File "/sandbox/lib/jumpscale/Jumpscale/__init__.py", line 217, in <module>
    j.dirs = Dirs(j)
  File "/sandbox/lib/jumpscale/Jumpscale/core/Dirs.py", line 12, in __init__
    self.BASEDIR = self._j.core.myenv.config["DIR_BASE"]
AttributeError: type object 'MyEnv' has no attribute 'config'
```

**Comment by Dina-Abd-Elrahman** [comment]
#### Branch: `development_hotfix2`, 

the installation is done successfully, and `kosmos` is working fine but js_shell cannot start 

![ff](https://user-images.githubusercontent.com/21218053/60160200-241a5d00-97f5-11e9-8224-a4941c5b3499.png)

**Comment by waleedhammam** [comment]
js_shell fixed at: https://github.com/threefoldtech/jumpscaleX/pull/667

**Comment by despiegk** [comment]
too old, no longer relevant
lets restart the testing
