### ISSUE TITLE
error with postgresql builder 

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtecharchive/jumpscaleX_archived#603]
I got this error with postgresql builder

![ff](https://user-images.githubusercontent.com/21218053/59286152-7db84e80-8c6f-11e9-97c0-ed529fc52d93.png)

branch : development 
commit id : fda36c0c5f5a7836b1b037a1b87cbc600afc7cf3

**Comment by abom** [comment]
Seems like someone's changed isUbuntu, isMac properties..., this stuff is used a lot in builders.

**Comment by andrewayoub** [comment]
fixed in https://github.com/threefoldtech/jumpscaleX/pull/607

**Comment by Dina-Abd-Elrahman** [comment]
###### Branch: `development`, fda36c0c5f5a7836b1b037a1b87cbc600afc7cf3 .

###### verification steps:
- build,  install, stop, start, test methods.
