### ISSUE TITLE
/sandbox/lib/jumpscale/Jumpscale/data/bcdb/tests/7_redis.py fails [development_install]

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#605]
please check/fix the test

**Comment by despiegk** [comment]
![image](https://user-images.githubusercontent.com/6021844/59383894-34e0c280-8d61-11e9-9f44-987c1605aa31.png)

is working

**Comment by despiegk** [comment]
![image](https://user-images.githubusercontent.com/6021844/59386649-7f653d80-8d67-11e9-9455-853d2a024f4e.png)

**Comment by andrewayoub** [comment]
Can you stop gedis server running in tmux and try to run the test again plz

**Comment by despiegk** [comment]
![image](https://user-images.githubusercontent.com/6021844/59388411-eedd2c00-8d6b-11e9-968f-2dd41fe10fc8.png)

**Comment by despiegk** [comment]
![image](https://user-images.githubusercontent.com/6021844/59388454-0e745480-8d6c-11e9-8498-59692f760975.png)
in tmux

restarting gevent resolves nothing

**Comment by despiegk** [comment]
there is no gevent anyhow

**Comment by despiegk** [comment]
its an error in the BCDB running redis server

**Comment by andrewayoub** [comment]
Seems like something happened after my fix, it was working until I pulled, I will try to figure out what happened

**Comment by despiegk** [comment]
all new code for redis interface, so need to retest
