### ISSUE TITLE
odoo does not start (builder): [development_installer]

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#610]
kosmos 'j.builders.apps.odoo.install()'

then

kosmos 'j.builders.apps.odoo.start()'

in tmux:

![image](https://user-images.githubusercontent.com/6021844/59389829-b63f5180-8d6f-11e9-85c3-216633829f52.png)

looks like postgresql has issue

**Comment by abom** [comment]
The work is done on development_builder branch (not development_installer).

**Comment by abom** [comment]
https://github.com/threefoldtech/jumpscaleX/commit/b2822f1a14b3a4684bb04f6240bda239bda68397 and https://github.com/threefoldtech/jumpscaleX/commit/2f0beb3c8d85868e1e7a96ebc8641ace2e88aa70

**Comment by AhmedHanafy725** [comment]
**branch:** development_builder
**commit:** 2f0beb3c8d85868e1e7a96ebc8641ace2e88aa70
It is working fine (build, install, start, stop)
![image](https://user-images.githubusercontent.com/41957921/59425042-70b56f80-8dd5-11e9-97ef-b2ea49aae3cc.png)
