### ISSUE TITLE
in jsx console there is j.builder.db and j.builderS.db

### ISSUE THREAD

**Issue by zgorizzo69** [threefoldtecharchive/jumpscaleX_archived#615]
when in jsx you can do 
`JSX>j.builder.db.zdb.install()`
and 
`JSX>j.builders.db.zdb.install()`
There should not be any references to `j.builder` only to `j.builders`

expected behaviour:
in the jsx shell there should not be any completion possible with `j.builder`

**Comment by BolaNasr** [comment]
@zgorizzo69  
what is the branch ? 
should be all  ``` j.builders```

**Comment by despiegk** [comment]
do on #682

**Comment by BolaNasr** [comment]
i thinks we should close this issue ..
all we have ```j.builders```
not have ```j.builder``` any more
