### ISSUE TITLE
jsx.py container-install hangs forever and prompt 'Restart services during package upgrades without asking?'

### ISSUE THREAD

**Issue by mdeecode** [threefoldtecharchive/jumpscaleX_archived#619]
## affected branches
- development
- development_installer

## affected platform
 MacOsX and Ubuntu.

## actual behaviour
Install fails. Install script hangs forever and prompts: 
`Restart services during package upgrades without asking?`
User cannot answer the question since it is a non interactive mode.

<img width="1147" alt="Screenshot 2019-06-14 at 11 19 34" src="https://user-images.githubusercontent.com/26189002/59515674-eeee4080-8ebf-11e9-8d30-74cf852abb81.png">

## expected behaviour
the script should run till the end and the 3bot container should be created and ready to use.

## reason
[see apt upgrade step](https://github.com/threefoldtech/jumpscaleX/blob/development/install/InstallTools.py#L3293)
## steps to reproduce
- from a clean install (no ~/sandbox/cfg nor ~/sandbox/var folder)
-  `$ cd ~/sandbox/code/github/threefoldtech/jumpscaleX/install` 
- `$ python3 ./jsx.py container-install -d`

**Comment by Pishoy** [comment]
installation done successfully
```
python3 ./jsx.py install
```
- jumpscalex version 
```
3BOTDEVEL:42d77da805ab:install: git log -1
commit 09efbac79b07cba572c814c774fe428d21bb28db (HEAD -> development_installer, origin/development_installer)
Merge: 60e200b2 b870fe13
Author: Reem Khamis <khamisr@codescalers.com>
Date:   Wed Jun 19 16:36:01 2019 +0200

    Merge branch 'development' into development_installer
```
