### ISSUE TITLE
SAL nginx

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#62]
- [read instructions](https://github.com/threefoldtech/jumpscale10/tree/master/Jumpscale/sal)

**Comment by Dina-Abd-Elrahman** [comment]
# Verification steps:

- j.sal.nginx.get(path='/etc/nginx')
- cl.configPath                                                                                                                                                                                       
```Out[4]: Path('/etc/nginx/conf.d')```
-  cl.start()
```* Starting nginx nginx                                                                                                                                                                              [ OK ] ```
- cl.stop()
```* Stopping nginx nginx                                                                                                                                                                              [ OK ]```
- cl.restart()
``` * Restarting nginx nginx                                                                                                                                                                         [ OK ] ```
