### ISSUE TITLE
python sandbox not working properly

### ISSUE THREAD

**Issue by serboctor** [threefoldtecharchive/jumpscaleX_archived#622]
I was recently trying python builder sandbox and it produced an empty folder.

**Comment by waleedhammam** [comment]
Related to: https://github.com/threefoldtech/jumpscaleX/issues/612

**Comment by waleedhammam** [comment]
refactored @ branch: development_builder @ commit: https://github.com/threefoldtech/jumpscaleX/commit/5ef815b2922ce0f29f461270db710582f3aedb28
sample generated flist: https://hub.grid.tf/hammam/python3.flist.md for v3.6.8

**Comment by Dina-Abd-Elrahman** [comment]
#### Branch: `development`, Commit: 688ba59a635e50ed30551fe7ff37bdeecf84ffbd
