### ISSUE TITLE
0-hub Builder

### ISSUE THREAD

**Issue by BolaNasr** [threefoldtecharchive/jumpscaleX_archived#628]
Allow people to create their own hub: create flist + launch script which launches container who has everything which hub has so people can use this to develop full life cycle management

**Comment by BolaNasr** [comment]
it's finished at development_builder branch 
this is the doc

https://github.com/threefoldtech/jumpscaleX/blob/development_builder/Jumpscale/builder/apps/docs/BuilderHub.md

**Comment by ranatrk** [comment]
Updated in [development_builder] branch with the final specs and updated docs:
@waleedhammam 
https://github.com/threefoldtech/jumpscaleX/commit/94d27f1c1ab9143d79fc8f83a196abd12cf34018
https://github.com/threefoldtech/jumpscaleX/commit/b19bc0654603bd06bfcc9abdead8a93d54cdf254
https://github.com/threefoldtech/jumpscaleX/commit/173feb55a70db42beda45eb10c8c6dd352bc1d10
https://github.com/threefoldtech/jumpscaleX/commit/173feb55a70db42beda45eb10c8c6dd352bc1d10

**Docs:**
https://github.com/threefoldtech/jumpscaleX/blob/development_builder/Jumpscale/builder/apps/docs/BuilderHub.md

@Dina-Abd-Elrahman

**Comment by Dina-Abd-Elrahman** [comment]
#### Branch: `development_builder` , commit id: 

#### Verification steps:
- j.builders.apps.hub.in_docker("127.0.0.1:5555")
- j.builders.apps.hub.install()
- j.builders.apps.hub.test()
- j.builders.apps.hub.start()
- j.builders.apps.hub.stop()
- j.builders.apps.hub.sandbox(zhub_client=your_zhub_cleint, flist_create=True, reset=True)
