### ISSUE TITLE
docker builder doesn't have reset argument 

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtecharchive/jumpscaleX_archived#664]
## Steps 
j.builders.virtualization.docker.build(reset=True) 
 ## Issue
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: build() got an unexpected keyword argument 'reset'

```
## Branch
development_builder

**Comment by waleedhammam** [comment]
added on **development_builders** branch
commit: https://github.com/threefoldtech/jumpscaleX/commit/4f5c2d4abcec6a03d7f3a7ba1dc284f2e9c7667e

**Comment by Dina-Abd-Elrahman** [comment]
- verifed .
