### ISSUE TITLE
Golang builder missed sandbox method

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtecharchive/jumpscaleX_archived#678]
Golang builder missed `sandbox`, `start`, and `stop` methods. 

###### Branch: `development_builder` , Commit ID: `73933ea29f95e238c765344c01fe39e05e7348ea`

**Comment by despiegk** [comment]
not really needed?
its a requirement for builders to work, why would this have to be started/stopped/sandboxed?

**Comment by despiegk** [comment]
will not resolve, because not needed
