### ISSUE TITLE
merge development_baseclasses & other open branches into development_jumpscale

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#682]
development_jumpscale is the branch for 10.0.1
see project https://github.com/orgs/threefoldtech/projects/15

lets release this 10.0.1 release asap, merge all branches we need into this release

- [x] development_baseclasses
- [x] development_bcdb / vfs / redis / ...
- [x] development_builders
- [x] other open branches which are open too long

**lets make sure all tests and notified bugs are done on this branch !!!!**

check issues not tagged on a project and or make obsolete (close), or put on 10.0.1 or on 10.0.2 or on later (tag)

make sure at least following is working

- [x] all tests schema
- [x] all tests bcdb (redis interface also with RDM)
- [x] make sure all startup management is done by means of the updated startupcmd manager (so no tmux directly)
- [x] builder python/digitalme/jumpscale
- [x] installer on ub 1804 in docker and without docker
- [x] some other builders we use now: odoo, tcprouter, zdb, coredns, ...
- [x] digitalocean client -> ubuntu VM -> building cycle
- [x] the TF Grid features

**Comment by despiegk** [comment]
once development_jumpscale is enough tested it will become branch development and it will stay there until we have some weeks exposure and then it can go to master.

**Comment by rkhamis** [comment]
I'll close this since we're now all up to date with development_jumpscale
