### ISSUE TITLE
error in library versions after using install some builders 

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtecharchive/jumpscaleX_archived#684]
- after installing some builders we got errors in some library version , so for example we cannot open `kosmos shell` or using curl command we have to re-download new library with the correct version to solve this issue. 

##### detailed description :

- when we build `synching` or `python` builder we got this error with curl, 

![error](https://user-images.githubusercontent.com/21218053/60765679-63bb3180-a09e-11e9-95fd-effd54cd7be9.jpg)

 and to fix this we have to remove the current version of `libcurl` using this command `rm /usr/local/lib/libcurl.so.4`

and this error with kosmos shell 
![error](https://user-images.githubusercontent.com/21218053/60765728-1db29d80-a09f-11e9-9a30-0cddbe6401de.jpg)

and to fix this error we download some modules

**Comment by abom** [comment]
This problem nearly happens with any builder to a project that uses python, need to find a solution (in odoo builder for example, we use another user).

**Comment by serboctor** [comment]
but `syncthing` builder actually doesn't use python. It actually uses go. I installed python then syncthing and couldn't reproduce the issue.
However this is a list of other builders that use python and need to be refactored:

- [x] Odoo (already done by Ghanem)
- [x] MongoDb
- [x] Graphql 
- [ ] Tarantool (will be done as part of https://github.com/threefoldtech/jumpscaleX/issues/529)

**Comment by Dina-Abd-Elrahman** [comment]
- I cannot reproduce the error too, We can close it now and re-opened it if we face this error again.
