### ISSUE TITLE
autocompletion does not work for certain cases

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#688]
![image](https://user-images.githubusercontent.com/6021844/60787460-24eab180-a15a-11e9-9bad-3dfd028ac1c5.png)

**Comment by abom** [comment]
Which branch?

On development, docstrings are not working (fixed in #689), but auto-completion works fine.

![Screenshot from 2019-07-08 10-53-08](https://user-images.githubusercontent.com/511438/60796904-9a607d00-a16e-11e9-9892-e39c321b8655.png)

**Comment by abom** [comment]
Testing on development_jumpscale, it's working, thing's has changed in `JSBase`, i need more clarification of what's actually needed by these changes to get the right fix and to know where is the problem exactly (auto-completion code or new `JSBase` methods to list members...etc).

**Comment by abom** [comment]
@despiegk  Also, you disabled debug logs if any errors occurred when trying to get auto completions by using `_in_autocomplete` flag again, which i've already removed, we can improve it by only logging errors in debug mode, not disabling it at all.

**Comment by despiegk** [comment]
in autocompletion mode nothing should ever print to the stdout otherwise you get very ugly behaviour
errors we do (raise error) because there there is no choice
the aim was to do it in the debug window but that never worked properly

**Comment by Dina-Abd-Elrahman** [comment]
#### Branch: `jumpscale_development` .

#### Commit ID:   cd38553270bcb29e7cee2e348f39483cb1993823 , 8e8c6f0c864cf2a782546521d074c04ba1e88a8d .

- verified. with debugging mode on and off. 

```
j.tools.logger.debug = False
j.tools.logger.debug = True
```
