### ISSUE TITLE
JSX 10.0.1 needs to be used for TF Grid 

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#695]
- users should use our JSX 10.0.1 (current branch development_jumpscale) for deploying workloads
- are there certain central components we can use and move to JX 10.0.1

**Comment by zaibon** [comment]
> users should use our JSX 10.0.1 (current branch development_jumpscale) for deploying workloads 

Why this branch ? there has been nothing new on this branch regarding workload deployment.
Also the code that include extension of reservation is currently on development. Was planning to have a new JSX release when this got merge to master again.
Should I move this code in another branch ?
