### ISSUE TITLE
error in all clients bue to bcdb

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtecharchive/jumpscaleX_archived#697]
- I got this error when i tried to use any client in `development_jumpscale`, 
Ex: `j.client.github.`

![error_github](https://user-images.githubusercontent.com/21218053/60974846-1ef7fa80-a32b-11e9-88fa-3f3cfa9242f3.png)

**Comment by ranatrk** [comment]
The issue is due to switching from a branch to the current `development_jumpscale` branch without executing `js_init generate` as there is a conflict between old bcdb and new files.
**_Fix_**: executing `js_init generate`

**Comment by Dina-Abd-Elrahman** [comment]
- Fixed, thanks @ranatrk
