### ISSUE TITLE
mariadb server does not started using the generated flist by mariadb sandbox method 

### ISSUE THREAD

**Issue by Pishoy** [threefoldtecharchive/jumpscaleX_archived#699]
i have create and flist using mariadb sandbox method but when i ceate a container using generated flist, mariadb does not started correctly using startup.toml flist file 

```
iyo = j.clients.itsyouonline.get("bishoyiyo",baseurl="https://itsyou.online/api",application_id="nmUST7",secret="m")
token = iyo.jwt_get().jwt 
zhub_client = j.clients.zhub.get("hub_instance",token_=token,username="mikhaieb")
zhub_client.save() 
zhub_client.authenticate() 
zhub_client = j.clients.zhub.get("hub_instance")
j.builders.db.mariadb.sandbox(zhub_client=zhub_client, flist_create=True)
```
- then create container using flist `https://hub.grid.tf/mikhaieb/mariadb_merged_tf-autobuilder_threefoldtech-jumpscaleX-development.flist`
- ssh to container and find out mysql process but does not exist 
```
root@testmariadb:/root# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0 688304  9492 ?        Ssl  14:26   0:00 /coreX -hostname testmariadb -unprivileged
root       263  0.0  0.0  72296   744 ?        Ss   14:27   0:00 /usr/sbin/sshd
root       334  0.0  0.0 103852  4488 ?        Rs   14:27   0:00 sshd: root@pts/0
root       349  0.0  0.0  20180   464 pts/0    Ss   14:27   0:00 -bash
root      4194  0.0  0.0  36072  3080 pts/0    R+   14:35   0:00 ps aux
```

- jsx version 
```
3BOTDEVEL:3bot:jumpscaleX: git log -1
commit c8097475b1ff1863f2acbc3a424c13436ca23002 (HEAD -> development_builders, origin/development_builders)
Author: Waleed Hammam <waleed.hammam@gmail.com>
Date:   Thu Jul 11 14:32:17 2019 +0200

    add mariadb missing libs

```

**Comment by ranatrk** [comment]
Currently getting an error in installing mariadb and working on it, therefore still didn’t reach the current issue

**Comment by ranatrk** [comment]
- ssh to container and no mysql process running
- When manually running each line in the startup.toml script, the following occurred and so currently investigation:
_Command_:  `scripts/mysql_install_db --basedir=/sandbox/usr/local/mysql \ --datadir=/sandbox/usr/local/mysql/data` 
    - library missing (Fix: `apt-get install libaio1 libaio-dev`)
![Screenshot from 2019-07-16 12-49-25](https://user-images.githubusercontent.com/17128393/61289080-c9a76780-a7c8-11e9-979b-c8be1b58823a.png)
    - mysql.user table aready exists, cannot connect to mysql manually to delete it **(Current)**
     ![Screenshot from 2019-07-16 12-50-26](https://user-images.githubusercontent.com/17128393/61289163-fd828d00-a7c8-11e9-9755-2fb0fa34dfe8.png)

**Comment by ranatrk** [comment]
fix for issue when ldd results in 'statically linked' output:
https://github.com/threefoldtech/jumpscaleX/commit/de0c937ac46ae453bea019c07577746081126b5e

currently working on sandbox of dependencies correctly

**Comment by ranatrk** [comment]
`j.tools.sandboxer.libs_sandbox(src, dest)` currently doesn't work as expected, looking into it. It is used to get the missing libs that all bin files need.

**Comment by ranatrk** [comment]
Blocked as` j.tools.sandboxer.ldd()` doesn't work as expected, and it is used in `j.tools.sandboxer.libs_sandbox(src, dest) `. Looking into into it

**Comment by ranatrk** [comment]
Fix for ldd in expression check: https://github.com/threefoldtech/jumpscaleX/commit/2b3bd2e5ae310dcb924ad3e6726a4aad2670ffbb

**Comment by ranatrk** [comment]
Fix sandbox : https://github.com/threefoldtech/jumpscaleX/commit/303c8f12c76e08bcaf4a5bb79a0574a38bae3ee5

**Comment by Pishoy** [comment]
verified 
generated flist by mariadb sandbox is working well
