### ISSUE TITLE
builder/client traefik

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#70]
follow instructions in corresponding dirs

**Comment by abom** [comment]
The client is not ready/tested yet.
Also etcd builder is broken.

**Comment by abom** [comment]
Some remarks:

For go, **GOROOT** and **GOPATH** need to be set and added to **PATH**, in the current builder, we use default profile (~/.bash_profile), but this won't be available until next login session, so **execute()** is implemented to source it before doing any go related commands (as an alternative to profile=True in **j.sal.process.execute**, maybe it should be re-added).

A proposed solution was to add them to **env.sh** manually (as **j.tools.bash.Profile** cannot handle if statements for example).
