### ISSUE TITLE
JumpScale Documentation

### ISSUE THREAD

**Issue by rkhamis** [threefoldtecharchive/jumpscaleX_archived#701]
This storycard is about both technical and end user documentation regarding the following topics

- [x] Installations [Installation README](https://github.com/threefoldtech/jumpscaleX/blob/development_jumpscale/docs/Installation/README.md)
  - [x] in system installation
  - [x] docker installation

- [x] Security Layer [Security Layer README](https://github.com/threefoldtech/jumpscaleX/tree/development_jumpscale/docs/security_layer)
  - [x] NACL and configmanager
     - [x] with sshkey
     - [x] without sshkey
  - [x] functionality

 - [x] Core [BaseClasses README](https://github.com/threefoldtech/jumpscaleX/blob/development_jumpscale/docs/Internals/baseclasses/README_NEW.md)
   - [x] baseclasses (see:https://github.com/threefoldtech/jumpscaleX/blob/development_jumpscale/docs/Internals/baseclasses/readme.md)

 - [ ] Data Layer
    - [ ] schemas
   - [ ] BCDB

- [ ] SALs

 - [ ] Tools

 - [ ] TFChain

 - [ ] Clients
 - [ ] Servers
 - [x] Builders [Builders Readme](https://github.com/threefoldtech/jumpscaleX/blob/development_jumpscale/Jumpscale/builders/README.md)

 - [ ] DigitalMe
   - [ ] server rack
   - [ ] Actors
   - [ ] jsclient (see: https://github.com/threefoldtech/digitalmeX/blob/development/docs/webserver/websocket-gedis.md)
   - [ ] gundbjs integration

**Comment by waleedhammam** [comment]
Will start with Installation docs.
- Todo:
- add/enhance readmes
- simple demo/tutorial

**Comment by waleedhammam** [comment]
Changelog: Installer
- updated install readme; branch **development_jumpscale**; commit: https://github.com/threefoldtech/jumpscaleX/commit/c52a2c4f9725330070cdc7e76ef002cde7c54002
file https://github.com/threefoldtech/jumpscaleX/blob/development_jumpscale/docs/Installation/README.md

**Comment by waleedhammam** [comment]
Changelog: Security Layer
* Updated readme; branch: **development_jumpscale** commit: https://github.com/threefoldtech/jumpscaleX/commit/2dc8e901238aeb1afa254595bb5a92ce1c5365a5
file: https://github.com/threefoldtech/jumpscaleX/tree/development_jumpscale/docs/security_layer

**Comment by waleedhammam** [comment]
Now, working on updating baseclasses docs.

**Comment by waleedhammam** [comment]
Changelog: Installation, Security Layer:
- some updates due to new changes at: commit: https://github.com/threefoldtech/jumpscaleX/commit/8b85aac3dc05e3e4e8ee9b7de7f2818fcfa187df ; branch: development_jumpscale

**Comment by waleedhammam** [comment]
Now back on baseclasses docs.

**Comment by waleedhammam** [comment]
**Changelog**: **branch**: development_jumpscale; **commit**:  https://github.com/threefoldtech/jumpscaleX/commit/0c559bab3add9be22bf974ca928868240b0abdc4
JSBase first docs at: https://github.com/threefoldtech/jumpscaleX/blob/0c559bab3add9be22bf974ca928868240b0abdc4/docs/Internals/baseclasses/README_NEW.md

**Comment by waleedhammam** [comment]
**Changelog**
**Branch**: development_jumpscale; **Commit**: https://github.com/threefoldtech/jumpscaleX/commit/b7ba69271f515d109f732cb3b8393db435e9d886
- Add JSAttr, JSFactoryConfig, JSConfigs classes docs @ https://github.com/threefoldtech/jumpscaleX/blob/development_jumpscale/docs/Internals/baseclasses/README_NEW.md

**Currently**
- Working on JSConfig class

**Comment by waleedhammam** [comment]
**Changelog**
**Branch**: development_jumpscale; **Commit**: https://github.com/threefoldtech/jumpscaleX/commit/2abbbb889077146af30df628222653b46e6a02d6
- docs @ https://github.com/threefoldtech/jumpscaleX/blob/development_jumpscale/docs/Internals/baseclasses/README_NEW.md

**Comment by waleedhammam** [comment]
Builders docs at: https://github.com/threefoldtech/jumpscaleX/blob/development_jumpscale/Jumpscale/builders/README.md
