### ISSUE TITLE
servers.dns needs some fixes [development_jumpscale_dns]

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#702]
```kosmos 'j.servers.dns.test()'``` still fails

the DNS client does not connect on the custom port 5354?

we also need to refactor some logic in resolver

have refactored the classes to use our config manager 
the resolver was too limited, had to insert 1 layer means we now need to fix the resolver to use this updated schema

**Comment by despiegk** [comment]
is not to do with the port, its to do with the refactoring
![image](https://user-images.githubusercontent.com/6021844/61169554-649d0900-a55f-11e9-8ef3-79177fca5fee.png)

**Comment by despiegk** [comment]
the basic test works now, but we still need to refactor putting records in
and put also these tests in the test() method

add some records to a chosen domain

use branch [development_jumpscale_dns]

**Comment by xmonader** [comment]
I'll check it tomorrow morning, was doing on lots of fixes on gundb server protocol and backend

**Comment by rkhamis** [comment]
Done here: https://github.com/threefoldtech/digitalmeX/pull/273/files

**Comment by Dina-Abd-Elrahman** [comment]
- Verified.
