### ISSUE TITLE
sonic client/server gives an issue still somewhere

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#703]
![image](https://user-images.githubusercontent.com/6021844/61169734-3caea500-a561-11e9-925a-2bad1e1b97d2.png)

just when using the shell

**Comment by despiegk** [comment]
use kosmos 'j.servers.sonic.test()' to test

**Comment by serboctor** [comment]
@despiegk I am not sure why you're getting this error, this attribute actually exists. I hardened the test and everything seems to be working fine.

**Comment by siddiquagig** [comment]
I get the following error:

![sonic](https://user-images.githubusercontent.com/25789724/61632867-e3e8b600-ac9e-11e9-95eb-cd986e98a17e.jpg)

**Comment by rkhamis** [comment]
@siddiquagig I think your issue is that sonic wasn't installed. I've tested this again and it works.

**Comment by siddiquagig** [comment]
Verified, working now
