### ISSUE TITLE
redis server not there yet

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#707]
![image](https://user-images.githubusercontent.com/6021844/61181058-020c4180-a621-11e9-89ca-e330048bd0b2.png)

lots of duplication

![image](https://user-images.githubusercontent.com/6021844/61181066-26681e00-a621-11e9-99a7-687f570526ca.png)

doesn't seem right
should be a hset of data:$sid:$id

does not fetch info

**Comment by zgorizzo69** [comment]
![image](https://user-images.githubusercontent.com/16853695/61182317-9e3e4480-a631-11e9-8a47-f40dc2d688db.png)
Indeed when pausing the redis test for bcdb `j.data.bcdb.test('redis')` every entry is doubled except for entry sid:1

**Comment by zgorizzo69** [comment]
![image](https://user-images.githubusercontent.com/16853695/61182362-1f95d700-a632-11e9-8ac9-21274e8cee8d.png)
there is an error shown in redis log

**Comment by zgorizzo69** [comment]
fix in this commit d1907a37ecb3be9144bb05d87cc6af41155d8f47
we still have more url than sid and hashes but it is not related  to redis server that why I close that issue
