### ISSUE TITLE
get markdowndocs to work

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#710]
- see with Andrew he needs it in #709 
- check include/link macro's
- need some more tests

**Comment by abom** [comment]
Initial working config was added

```
openresty = j.servers.openresty.default 
wiki = openresty.wikis.new(name="foundation", giturl="https://github.com/threefoldfoundation/info_foundation", branch="development", domain="mywiki2.com") 
wiki.update(generate=True) 
openresty.start()
```

Then going to `mywiki2.com/wiki/foundation` (mywiki2.com points to container ip in `/etc/hosts`).
