### ISSUE TITLE
finish threebot server factory

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#711]
need to wait for #709  (openresty)

todo

- [x] test chatbot
- [ ] authentication through openresty (need add on there probably) for chatbot
- [ ] packaging (kristof)
- [ ] integration of gundb client (need auth with master passwd)
- [ ] integration graphql client (need auth with master passwd)
- tbd

**Comment by BolaNasr** [comment]
i have error when get openresty to start it ( and test is fail ```j.servers.openresty.test()``` )
jumpscaleX ( development_jumpscale)
DigitalMeX ( development_jumpscale)
![image](https://user-images.githubusercontent.com/10259267/61473672-29e40800-a987-11e9-8ac3-cc9ee2cd4b16.png)

**Comment by BolaNasr** [comment]
i passed the error above but have problem 
![image](https://user-images.githubusercontent.com/10259267/61641186-f95de000-ac9e-11e9-8dae-464779f0ab04.png)

it can't serve index.etlua if i add index.html it works good  in ```/sandbox/var/web/html/chat```

@abom  any suggestion for that i think the problem in config somehow

**Comment by abom** [comment]
That's a configuration problem for sure, you need use to openresty directives like `content_by_lua_block` if you running a lapis app, not serving etlua files as html.

See https://leafo.net/lapis/reference/getting_started.html#creating-an-application/nginx-configuration

**Comment by BolaNasr** [comment]
chatbot doc : https://github.com/threefoldtech/digitalmeX/blob/development_jumpscale/DigitalMe/servers/threebot/README.md

branch ```development_jumpscale```
