### ISSUE TITLE
BCDB tests need to be redone

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#714]

**Comment by BolaNasr** [comment]
Still working on it but have problem in JSconfig when save data because it didn't have model
![image](https://user-images.githubusercontent.com/10259267/61186232-28eb6780-a663-11e9-840e-42d7cb06367f.png)

**Comment by BolaNasr** [comment]
Now it works good
![image](https://user-images.githubusercontent.com/10259267/61217345-c308e980-a70f-11e9-8937-add01f5d33b0.png)

**Comment by siddiquagig** [comment]
Verified

```JSX> j.data.bcdb.test()```

```
Mon 22 11:55:12 Startupcmd.py		    - 342 - startupcmd		: IS HALTED based on TCP/UDP webdav_test
Mon 22 11:55:12 BCDBFactory.py		    - 341 - bcdbfactory		: All TESTS DONE
```

```
3BOTDEVEL:3bot:jumpscaleX: git log -1
commit 706ae7063c28f7848ec64ce0bd3966d97fa4c452 (HEAD -> development_jumpscale, origin/development_jumpscale)
Author: despiegk <kristof@incubaid.com>
Date:   Mon Jul 22 11:54:16 2019 +0200

    install improvements
```
