### ISSUE TITLE
test install on ubuntu1804 with container option

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#716]
# check

- [x] there was no need to install docker, was autoinstalled by installer
- [x] install worked
- [x] could install web components
- [x] try option -r -d so we restart from scratch

test using digital ocean client
make test script paste it here

**Comment by waleedhammam** [comment]
blocked on: https://github.com/threefoldtech/jumpscaleX/issues/720 will try to fix it

**Comment by waleedhammam** [comment]
Did some fixes on starting installation,
The script runs ok but stucks for i/os
Need to make the installer non-interactive to complete it.

**Comment by waleedhammam** [comment]
Current progress:
- With digital ocean client created a machine
- using ssh client to access it
- installed jsx with nothing else on the system in container
- installation works OK non-interactivly
  Working on:
- installing web components and testing it
- trying options r and d
- completing the running script

**Comment by waleedhammam** [comment]
Fixed no-interactive installation
now continue on the script

**Comment by waleedhammam** [comment]
script done in here: https://gist.github.com/waleedhammam/dbc786fdf33b25547f548467f0ec1743

**Comment by Pishoy** [comment]
needs https://github.com/threefoldtech/jumpscaleX/issues/738

**Comment by Pishoy** [comment]
verified 
 - case droplet already exist append below lines  

```
digitalocean_machine_name = "jumpscalxtestBishoy"
digitalocean_token_="b59.......................f05"
digitalocean_project_name="codescalers"
ssh_key_docker = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC8o0jEGYqe2k7J0TNL6Gg8h86ic3ReiC6THlBnOKPDiKProj/4uMTmi1Qf5OcLIdeHgcP+zy+ZL4kpP7N6VTALRPiTn6Lty6ZP+5mQocaJYosoGLzB6+lx1NW/zXtscv4V3goULiDEx9SBzSuD8wS0k00iHcRjmuFUIfERyYR8mjmWC/sRf1Y7qk9kQjFOLW5Sw0+RLrxr4l2ur/n8bDVgGVpzWypKIsqRU6Rf1HdXWmdAMCucPAkxR5WNies5QFOkyllxI6Fq+G9M0Uf+EubpfpC1oOMWjNFy781M4KZF+FXODcBlwevfvk0HH/5mTHOymIfwVV8vjRzycxjuQib3 pishoy@Bishoy-laptop"


my_test = JSXtest(digitalocean_machine_name, digitalocean_token_, digitalocean_project_name, ssh_key_docker)

my_test.install()

```
- case create a new droplet append below lines
```
digitalocean_machine_name = "jumpscalxtestBishoy2"
digitalocean_token_="b59278d................2c7f05"
digitalocean_project_name="codescalers"
ssh_key=  'Bishoy'
my_test = JSXtest(digitalocean_machine_name, digitalocean_token_, digitalocean_project_name, ssh_key)
my_test.create_digitalocean_machine()
my_test.install()

```
