### ISSUE TITLE
make sure all startup cmd usage is fixed with the new interface

### ISSUE THREAD

**Issue by rkhamis** [threefoldtecharchive/jumpscaleX_archived#727]

**Comment by ranatrk** [comment]
Fix: change `cmd` in `startup_cmds()` to `cmd_start`
https://github.com/threefoldtech/jumpscaleX/commit/d67141f0a751200f0847a3862ef3c4f4839fb026

**Comment by ranatrk** [comment]
branch: _[jumpscale_development]_

**Comment by siddiquagig** [comment]
Verified and tested with a builder

```
3BOTDEVEL:3bot:jumpscaleX: git log -1
commit ce2806ac1b2b07cc96021c43f1e1b5ad30d9646a (HEAD -> development_jumpscale, origin/development_jumpscale)
Author: Reem Khamis <khamisr@codescalers.com>
Date:   Thu Jul 18 10:51:15 2019 +0200

    Move builders under builders
```

**Comment by siddiquagig** [comment]
It is not working for  servers with ports : 

![rana](https://user-images.githubusercontent.com/25789724/61792541-0f4ddb00-ae2e-11e9-9e93-a1b82216df6a.JPG)

**Comment by ranatrk** [comment]
Fix for servers with ports : https://github.com/threefoldtech/jumpscaleX/commit/25ba825f909229bf359febb1e42b5259df531f42

**Comment by siddiquagig** [comment]
Working now for redis.start() but not for nginx.start()

```JSX> j.builders.db.redis.start()```

![redis1](https://user-images.githubusercontent.com/25789724/61805641-3238b900-ae47-11e9-835d-7858ebff91a3.JPG)

nginx.start() : 

![nginx1](https://user-images.githubusercontent.com/25789724/61806116-31eced80-ae48-11e9-8378-e40495703a69.JPG)

**Comment by ranatrk** [comment]
Fix : use `exec -a cmd_name` when starting to use the name rather than the cmd itself when checking if running or getting pid.
https://github.com/threefoldtech/jumpscaleX/commit/7369315ecea52fe29ed9c7ada0d9fc7306702ebf

**Comment by siddiquagig** [comment]
Verified for nginx also, its working now:

![nginx2](https://user-images.githubusercontent.com/25789724/61868825-4d5d0480-aeeb-11e9-957d-592f98e23d61.JPG)

```
commit 011a7bc4f589a42f6f969abd1a9fb4ef5fa7dfa5 (HEAD -> development_jumpscale, origin/development_jumpscale)
Author: Reem Khamis <khamisr@codescalers.com>
Date:   Thu Jul 25 12:45:34 2019 +0200

    Add resty-auto-ssl dependency to luabuilder

```
