### ISSUE TITLE
startup cmd only works with ports

### ISSUE THREAD

**Issue by rkhamis** [threefoldtecharchive/jumpscaleX_archived#728]
startup cmd needs to be able to tell a process is running even if no port is satisfied (use process id)

**Comment by ranatrk** [comment]
Fix in https://github.com/threefoldtech/jumpscaleX/issues/727 
commit : https://github.com/threefoldtech/jumpscaleX/commit/7369315ecea52fe29ed9c7ada0d9fc7306702ebf

**Comment by Dinaamagdy** [comment]
fixed on development_jumpscale 
## Steps 
- try start command on builders need  ports like caddy and redis and both works
