### ISSUE TITLE
URGENT: js_shell 'j.tools.syncer.test()'

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#76]
finish, so people can use this to sync to remote machines

**Comment by arahmanhamdy** [comment]
https://github.com/threefoldtech/jumpscaleX/commit/0c2c835b246f20382dd05c146bd7eab196741a62 

though, the ExecutorBase needs to be refactored

**Comment by despiegk** [comment]
https://github.com/threefoldtech/jumpscaleX/blob/master/Jumpscale/tools/syncer/SyncerFactory.py#L50
is working
