### ISSUE TITLE
Links from home page readme are all broken

### ISSUE THREAD

**Issue by zaibon** [threefoldtecharchive/jumpscaleX_archived#79]

**Comment by Dina-Abd-Elrahman** [comment]
- all links in this link in GitHub repositories are broken except jumpscale core one

https://github.com/threefoldtech/jumpscaleX/tree/master/docs

**Comment by ahmadnazih** [comment]
Links are now fixed.., only one link can't fix which is the Q-Layer in that readme.md here https://github.com/threefoldtech/jumpscaleX/tree/master/docs

**Comment by Dina-Abd-Elrahman** [comment]
https://github.com/threefoldtech/jumpscaleX/tree/master/docs#what-is-jumpscale 

Q-Layer in this part still gaves 404 error 

- and please check the mail writen here 
https://github.com/threefoldtech/jumpscaleX/tree/master/docs#help-us-improve-jumpscale
are we still use   info@incubaid.com

**Comment by Dina-Abd-Elrahman** [comment]
https://github.com/threefoldtech/jumpscaleX/tree/master/docs#what-is-jumpscale
fix ```Q-Layer``` link

**Comment by Dina-Abd-Elrahman** [comment]
- only need to know if we still use this email or not ```info@incubaid.com``` for contact 

https://github.com/threefoldtech/jumpscaleX/tree/master/docs#help-us-improve-jumpscale

**Comment by rkhamis** [comment]
@Dina-Abd-Elrahman please contact @VonSub or @sabrinasadik for which contact to use

**Comment by Dina-Abd-Elrahman** [comment]
the contact mail is updated to info@threefold.tech
