### ISSUE TITLE
j.clients.btc_alpha

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#8]
- new config mgr
- basic test to connect
- readme

**Comment by despiegk** [comment]
## make sure client is properly implemented 

- implement j.client using our new config mgmt
    - [learn how to do it in template for client](https://github.com/threefoldtech/jumpscale10/tree/master/Jumpscale/clients/TEMPLATE)

**Comment by ranatrk** [comment]
Client now uses the new config manager:
https://github.com/threefoldtech/jumpscaleX/commit/f4086b0d93c7b81ef5d3e7391bb919e2215d3e3b

**Comment by waleedhammam** [comment]
@ branch: development_jumpscale @ commit: https://github.com/threefoldtech/jumpscaleX/commit/df2f9023c4282e8cd00cccd0308ca2582e02e3d4
- client follows the new config manager
- added readme at: https://github.com/threefoldtech/jumpscaleX/blob/df2f9023c4282e8cd00cccd0308ca2582e02e3d4/Jumpscale/clients/btc_alpha/README.md
- works ok with `https://btc-alpha.com/api/` endpoint

**Comment by Dina-Abd-Elrahman** [comment]
#### Branch: `development_jumpscale` , commit: ab20081c6b6964e18c4e3e316198dc50e8f06099
