### ISSUE TITLE
can't start ufw inside the sandbox

### ISSUE THREAD

**Issue by andrewayoub** [threefoldtecharchive/jumpscaleX_archived#80]
When I try to do any operation using ufw inside the sandbox I'm getting this error 
```python
Traceback (most recent call last):
  File "/usr/sbin/ufw", line 26, in <module>
    import ufw.frontend
ModuleNotFoundError: No module named 'ufw'

```
I tried to install ufw pip package but it doesn't work
```bash
$ pip3 install ufw
Collecting ufw
  Could not find a version that satisfies the requirement ufw (from versions: )
No matching distribution found for ufw
```
to overcome this issue I just copied ufw package from dist-packages of my system to dis-packages of the sandbox and it worked, but i believe this is not the solution

**Comment by serboctor** [comment]
It can be installed using `apt-get install python-ufw`. I added it and the ufw to the installer. https://github.com/threefoldtech/jumpscaleX/commit/6c715b9e104b79e4e8bc2d96eaacc0e1c4003228
and working on adding the binaries to the sandbox repo.

**Comment by serboctor** [comment]
Added ufw to the ubuntu sandbox too https://github.com/threefoldtech/sandbox_ubuntu/commit/ccf2567abb1b5ebe9d0a91aa32fe92a0e3de8760

**Comment by Dina-Abd-Elrahman** [comment]
## Verification steps:

- try to import ufw, from sandbox. 
```
import ufw
```
